#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Apply','Verify','Rollback','Finalize')][string]$Action='Plan',
  [string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,[string]$ConfirmHostname,[string]$ConfirmLanBindAddress,[string]$ConfirmReleaseId,[string]$RenewalRoot,[string]$ExpectedRenewalManifestSha256,
  [string]$PreOpenClientTrustEvidencePath,[string]$ExpectedPreOpenClientTrustEvidenceSha256,
  [string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,[string]$ExpectedFilesystemDescriptorDigest,
  [string]$NodePath,[string]$ExpectedNodeSha256,[string]$TlsVerifierPath,[string]$ExpectedTlsVerifierSha256,
  [string]$HttpsVerifierPath,[string]$ExpectedHttpsVerifierSha256,
  [string]$CurrentReleaseRoot,[string]$ExpectedReleaseManifestSha256,[string]$DrainStatePath,[string]$ExpectedDrainStateSha256,
  [string]$EdgeDrainHelperPath,[string]$ExpectedEdgeDrainHelperSha256,[string]$AttestationVerifierPath,[string]$ExpectedAttestationVerifierSha256,[string]$EdgeSigningPublicKeyPath,[string]$ExpectedEdgeSigningPublicKeySha256,
  [string]$ActivationJournalPath,[string]$ExpectedActivationJournalSha256,
  [ValidateSet('Apply','Rollback','Finalize')][string]$PlannedAction,[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
$edgeDrainHelper=if($EdgeDrainHelperPath){[IO.Path]::GetFullPath($EdgeDrainHelperPath)}else{[IO.Path]::GetFullPath((Join-Path $PSScriptRoot 'edge-drain-identity.ps1'))};. (Import-PinnedHelperScriptBlock $edgeDrainHelper $ExpectedEdgeDrainHelperSha256 'EDGE_DRAIN_HELPER_HASH_MISMATCH')
$edgeService='MetaAdsPerformanceEdge'
function Existing([string]$Path,[bool]$Directory,[string]$Code){$kind=if($Directory){'Container'}else{'Leaf'};if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType $kind)){throw $Code};$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');$cursor=Get-Item -LiteralPath $full -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'CERTIFICATE_ACTIVATION_REPARSE_REJECTED'};$cursor=$cursor.Parent};return $full}
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function ExpectedHash([string]$Path,[string]$Expected,[string]$Code){if($Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $Path)-cne$Expected.ToLowerInvariant()){throw $Code}}
function Under([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');return @($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function AtomicCopy([string]$Source,[string]$Target){$pending="$Target.pending";Copy-Item -LiteralPath $Source -Destination $pending;Move-Item -LiteralPath $pending -Destination $Target -Force}
function Wait-State([string]$Name,[string]$State,[int]$Seconds=30){$deadline=(Get-Date).AddSeconds($Seconds);do{if((Get-Service -Name $Name -ErrorAction Stop).Status-eq$State){return};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw 'SERVICE_STATE_TIMEOUT'}
function Assert-MaintenanceAndDrain($Config){$root=if($Config.data.root){[IO.Path]::GetFullPath([string]$Config.data.root)}else{[IO.Path]::GetFullPath((Join-Path $(if($env:ProgramData){$env:ProgramData}else{$env:LOCALAPPDATA}) 'MetaAdsPerformance'))};$flag=Existing (Join-Path $root 'runtime-control\maintenance.enabled') $false 'MAINTENANCE_REQUIRED';$value=Get-Content -Raw -LiteralPath $flag|ConvertFrom-Json;if($value.version-ne1-or$value.enabled-ne$true-or$value.releaseId-cne$Config.release.id){throw 'MAINTENANCE_EVIDENCE_REJECTED'};$identity=Assert-ExactEdgeDrainIdentity -EdgeServiceName $edgeService -RuntimeConfigPath $RuntimeConfigPath -ExpectedRuntimeConfigSha256 $ExpectedRuntimeConfigSha256 -ReleaseRoot $CurrentReleaseRoot -ExpectedReleaseManifestSha256 $ExpectedReleaseManifestSha256 -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -DrainStatePath $DrainStatePath -ExpectedDrainStateSha256 $ExpectedDrainStateSha256 -AttestationVerifierPath $AttestationVerifierPath -ExpectedAttestationVerifierSha256 $ExpectedAttestationVerifierSha256 -EdgeSigningPublicKeyPath $EdgeSigningPublicKeyPath -ExpectedEdgeSigningPublicKeySha256 $ExpectedEdgeSigningPublicKeySha256;if($approvedCertificatePlan-and$identity.IdentityDigest-cne$approvedCertificatePlan.exactParameters.currentDrainIdentityDigest){throw 'CERTIFICATE_ACTIVATION_DRAIN_IDENTITY_DRIFT'};return $identity}
function Probe($Config){&$node $httpsVerifier "--connect-address=$($Config.lan.bindAddress)" "--hostname=$($Config.lan.hostname)" "--ca=$($Config.tls.caCertificatePath)" "--certificate=$($Config.tls.serverCertificatePath)" "--release-id=$($Config.release.id)" '--expected-status=503' 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw 'HTTPS_CERTIFICATE_ACTIVATION_VERIFY_FAILED'}}
function IsPrivateIpv4([string]$Address){try{$p=$Address.Split('.')|ForEach-Object{[int]$_};return $p.Count-eq4-and($p|Where-Object{$_-lt0-or$_-gt255}).Count-eq0-and($p[0]-eq10-or($p[0]-eq172-and$p[1]-ge16-and$p[1]-le31)-or($p[0]-eq192-and$p[1]-eq168))}catch{return $false}}
function New-CertificateActivationApprovalPlan([string]$IntendedAction){
  if($IntendedAction-notin@('Apply','Rollback','Finalize')){throw 'PLANNED_ACTION_REQUIRED'}
  if($ConfirmHostname-notmatch'^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])$'-or-not(IsPrivateIpv4 $ConfirmLanBindAddress)-or$ConfirmReleaseId-notmatch'^[a-z0-9][a-z0-9._-]{0,62}$'){throw 'CERTIFICATE_ACTIVATION_PLAN_IDENTITY_INVALID'}
  $parameters=[ordered]@{runtimeConfigPath=(Get-ApprovalPath $RuntimeConfigPath 'CERTIFICATE_ACTIVATION_PLAN_RUNTIME_PATH_REQUIRED');runtimeConfigSha256=(Get-ApprovalHash $ExpectedRuntimeConfigSha256 'CERTIFICATE_ACTIVATION_PLAN_RUNTIME_HASH_REQUIRED');hostname=$ConfirmHostname;lanBindAddress=$ConfirmLanBindAddress;releaseId=$ConfirmReleaseId;edgeServiceName=$edgeService;filesystemEvidencePath=(Get-ApprovalPath $FileSystemEvidencePath 'CERTIFICATE_ACTIVATION_PLAN_FILESYSTEM_EVIDENCE_PATH_REQUIRED');filesystemEvidenceSha256=(Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'CERTIFICATE_ACTIVATION_PLAN_FILESYSTEM_EVIDENCE_HASH_REQUIRED');filesystemDescriptorDigest=(Get-ApprovalHash $ExpectedFilesystemDescriptorDigest 'CERTIFICATE_ACTIVATION_PLAN_FILESYSTEM_DESCRIPTOR_REQUIRED');nodePath=(Get-ApprovalPath $NodePath 'CERTIFICATE_ACTIVATION_PLAN_NODE_PATH_REQUIRED');nodeSha256=(Get-ApprovalHash $ExpectedNodeSha256 'CERTIFICATE_ACTIVATION_PLAN_NODE_HASH_REQUIRED');httpsVerifierPath=(Get-ApprovalPath $HttpsVerifierPath 'CERTIFICATE_ACTIVATION_PLAN_HTTPS_VERIFIER_PATH_REQUIRED');httpsVerifierSha256=(Get-ApprovalHash $ExpectedHttpsVerifierSha256 'CERTIFICATE_ACTIVATION_PLAN_HTTPS_VERIFIER_HASH_REQUIRED')}
  $parameters.currentReleaseRoot=Get-ApprovalPath $CurrentReleaseRoot 'CERTIFICATE_ACTIVATION_PLAN_RELEASE_ROOT_REQUIRED';$parameters.releaseManifestSha256=Get-ApprovalHash $ExpectedReleaseManifestSha256 'CERTIFICATE_ACTIVATION_PLAN_RELEASE_MANIFEST_HASH_REQUIRED';$parameters.drainStatePath=Get-ApprovalPath $DrainStatePath 'CERTIFICATE_ACTIVATION_PLAN_DRAIN_PATH_REQUIRED';$parameters.drainStateSha256=Get-ApprovalHash $ExpectedDrainStateSha256 'CERTIFICATE_ACTIVATION_PLAN_DRAIN_HASH_REQUIRED';$parameters.edgeDrainHelperPath=Get-ApprovalPath $edgeDrainHelper 'CERTIFICATE_ACTIVATION_PLAN_DRAIN_HELPER_PATH_REQUIRED';$parameters.edgeDrainHelperSha256=Get-ApprovalHash $ExpectedEdgeDrainHelperSha256 'CERTIFICATE_ACTIVATION_PLAN_DRAIN_HELPER_HASH_REQUIRED';$parameters.attestationVerifierPath=Get-ApprovalPath $AttestationVerifierPath 'CERTIFICATE_ACTIVATION_PLAN_ATTESTATION_PATH_REQUIRED';$parameters.attestationVerifierSha256=Get-ApprovalHash $ExpectedAttestationVerifierSha256 'CERTIFICATE_ACTIVATION_PLAN_ATTESTATION_HASH_REQUIRED';$parameters.edgeSigningPublicKeyPath=Get-ApprovalPath $EdgeSigningPublicKeyPath 'CERTIFICATE_ACTIVATION_PLAN_EDGE_PUBLIC_KEY_PATH_REQUIRED';$parameters.edgeSigningPublicKeySha256=Get-ApprovalHash $ExpectedEdgeSigningPublicKeySha256 'CERTIFICATE_ACTIVATION_PLAN_EDGE_PUBLIC_KEY_HASH_REQUIRED';$planDrain=Assert-ExactEdgeDrainIdentity -EdgeServiceName $edgeService -RuntimeConfigPath $RuntimeConfigPath -ExpectedRuntimeConfigSha256 $ExpectedRuntimeConfigSha256 -ReleaseRoot $CurrentReleaseRoot -ExpectedReleaseManifestSha256 $ExpectedReleaseManifestSha256 -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -DrainStatePath $DrainStatePath -ExpectedDrainStateSha256 $ExpectedDrainStateSha256 -AttestationVerifierPath $AttestationVerifierPath -ExpectedAttestationVerifierSha256 $ExpectedAttestationVerifierSha256 -EdgeSigningPublicKeyPath $EdgeSigningPublicKeyPath -ExpectedEdgeSigningPublicKeySha256 $ExpectedEdgeSigningPublicKeySha256;$parameters.currentDrainIdentityDigest=$planDrain.IdentityDigest;$parameters.currentDrainEdgeProcessId=$planDrain.EdgeProcessId;$parameters.currentDrainEdgeProcessStartedAt=$planDrain.EdgeProcessStartedAt;$parameters.currentDrainListenerAddress=$planDrain.ListenerAddress;$parameters.currentDrainListenerPort=$planDrain.ListenerPort;$parameters.currentDrainCompletedAt=$planDrain.DrainCompletedAt
  if($IntendedAction-eq'Apply'){$parameters.renewalRoot=Get-ApprovalPath $RenewalRoot 'CERTIFICATE_ACTIVATION_PLAN_RENEWAL_ROOT_REQUIRED';$parameters.renewalManifestSha256=Get-ApprovalHash $ExpectedRenewalManifestSha256 'CERTIFICATE_ACTIVATION_PLAN_RENEWAL_HASH_REQUIRED';$parameters.preOpenClientTrustEvidencePath=Get-ApprovalPath $PreOpenClientTrustEvidencePath 'CERTIFICATE_ACTIVATION_PLAN_TRUST_PATH_REQUIRED';$parameters.preOpenClientTrustEvidenceSha256=Get-ApprovalHash $ExpectedPreOpenClientTrustEvidenceSha256 'CERTIFICATE_ACTIVATION_PLAN_TRUST_HASH_REQUIRED';$parameters.tlsVerifierPath=Get-ApprovalPath $TlsVerifierPath 'CERTIFICATE_ACTIVATION_PLAN_TLS_VERIFIER_PATH_REQUIRED';$parameters.tlsVerifierSha256=Get-ApprovalHash $ExpectedTlsVerifierSha256 'CERTIFICATE_ACTIVATION_PLAN_TLS_VERIFIER_HASH_REQUIRED'}
  else{$parameters.activationJournalPath=Get-ApprovalPath $ActivationJournalPath 'CERTIFICATE_ACTIVATION_PLAN_JOURNAL_PATH_REQUIRED';$parameters.activationJournalSha256=Get-ApprovalHash $ExpectedActivationJournalSha256 'CERTIFICATE_ACTIVATION_PLAN_JOURNAL_HASH_REQUIRED'}
  $target="Exact Edge certificate generation for release $ConfirmReleaseId at https://$ConfirmHostname ($ConfirmLanBindAddress):443"
  $impact=if($IntendedAction-eq'Apply'){'Under maintenance and a fresh drain, stops only Edge, atomically swaps exact same-CA certificate/key/trust artifacts, restarts Edge, and verifies HTTPS'}elseif($IntendedAction-eq'Rollback'){'Restores only the journal-bound previous certificate/key/trust artifacts and restarts Edge'}else{'Deletes only the verified certificate activation journal and previous rollback artifacts'}
  $rollback=if($IntendedAction-eq'Apply'){'Use a separately approved Rollback plan to restore hash-pinned previous artifacts'}elseif($IntendedAction-eq'Rollback'){'Re-apply the renewal only through a new approved Apply plan'}else{'Finalize is irreversible by this script; recover from the separately retained release/recovery kit'}
  return New-ApprovalPlan $PSCommandPath $IntendedAction $parameters $target $impact $rollback
}
if($Action-eq'Plan'){New-CertificateActivationApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0}
$certificateMutation=if($Action-in@('Apply','Rollback','Finalize')){$Action}else{$null};$approvedCertificatePlan=$null;if($certificateMutation){$approvedCertificatePlan=New-CertificateActivationApprovalPlan $certificateMutation;Assert-ApprovedPlan $approvedCertificatePlan ([bool]$Approved) $ApprovedPlanSha256}
$runtime=Existing $RuntimeConfigPath $false 'RUNTIME_CONFIG_NOT_FOUND';$config=Get-Content -Raw -LiteralPath $runtime|ConvertFrom-Json
ExpectedHash $runtime $ExpectedRuntimeConfigSha256 'RUNTIME_CONFIG_HASH_MISMATCH';if(-not$config.lan.enabled-or-not$config.tls.clientTrustVerified-or$config.lan.hostname-cne$ConfirmHostname-or$config.lan.bindAddress-cne$ConfirmLanBindAddress-or$config.release.id-cne$ConfirmReleaseId){throw 'FULL_LAN_RUNTIME_REQUIRED'}
$activeCert=[IO.Path]::GetFullPath([string]$config.tls.serverCertificatePath);$activeKey=[IO.Path]::GetFullPath([string]$config.tls.serverPrivateKeyPath);$activeTrust=[IO.Path]::GetFullPath([string]$config.tls.clientTrustEvidencePath);$ca=Existing ([string]$config.tls.caCertificatePath) $false 'CA_CERTIFICATE_NOT_FOUND'
foreach($active in @($activeCert,$activeKey,$activeTrust)){Existing $active $false 'ACTIVE_CERTIFICATE_ARTIFACT_NOT_FOUND'|Out-Null}
$journal=Join-Path (Split-Path -Parent $activeCert) 'certificate-activation.json';$previousCert="$activeCert.previous";$previousKey="$activeKey.previous";$previousTrust="$activeTrust.previous"
if($Action-in@('Rollback','Finalize')){if([IO.Path]::GetFullPath($ActivationJournalPath)-ine[IO.Path]::GetFullPath($journal)){throw 'CERTIFICATE_ACTIVATION_JOURNAL_PATH_MISMATCH'};ExpectedHash $journal $ExpectedActivationJournalSha256 'CERTIFICATE_ACTIVATION_JOURNAL_HASH_MISMATCH'}
if($Action-in@('Verify','Rollback','Finalize')){
  $node=Existing $NodePath $false 'NODE_NOT_FOUND';$httpsVerifier=Existing $HttpsVerifierPath $false 'HTTPS_VERIFIER_NOT_FOUND';ExpectedHash $node $ExpectedNodeSha256 'NODE_HASH_MISMATCH';ExpectedHash $httpsVerifier $ExpectedHttpsVerifierSha256 'HTTPS_VERIFIER_HASH_MISMATCH'
  $journalPath=Existing $journal $false 'CERTIFICATE_ACTIVATION_JOURNAL_NOT_FOUND';$j=Get-Content -Raw -LiteralPath $journalPath|ConvertFrom-Json
  if($j.version-ne2-or$j.releaseId-cne$config.release.id-or$j.currentDrainIdentityDigest-notmatch'^[a-f0-9]{64}$'-or[int]$j.currentDrainEdgeProcessId-le0-or-not$j.currentDrainEdgeProcessStartedAt-or$j.currentDrainListenerAddress-cne$config.lan.bindAddress-or$j.currentDrainListenerPort-ne443-or-not$j.signedFreshDrainVerified){throw 'CERTIFICATE_ACTIVATION_JOURNAL_REJECTED'}
  $fsPath=Existing $FileSystemEvidencePath $false 'FILESYSTEM_EVIDENCE_NOT_FOUND';ExpectedHash $fsPath $ExpectedFileSystemEvidenceSha256 'FILESYSTEM_EVIDENCE_HASH_MISMATCH';$fs=Get-Content -Raw -LiteralPath $fsPath|ConvertFrom-Json
  if($fs.result-ne'PASS'-or-not$fs.exactAcl-or$fs.descriptorDigest-cne$ExpectedFilesystemDescriptorDigest-or-not(Under $node $fs.classRoots.SHARED_RUNTIME)-or-not(Under $httpsVerifier $fs.classRoots.SHARED_RUNTIME)-or-not(Under $activeCert $fs.classRoots.EDGE_READ)-or-not(Under $activeKey $fs.classRoots.EDGE_READ)-or-not(Under $activeTrust $fs.classRoots.ADMIN_EVIDENCE)-or-not(Under $journalPath $fs.classRoots.EDGE_READ)){throw 'CERTIFICATE_ACTIVATION_FILESYSTEM_REJECTED'}
  if($Action-eq'Verify'){
    if((Hash $activeCert)-cne$j.targetCertificateSha256-or(Hash $activeKey)-cne$j.targetPrivateKeySha256-or(Hash $activeTrust)-cne$j.targetTrustSha256){throw 'ACTIVE_CERTIFICATE_HASH_MISMATCH'}
    $service=Get-Service -Name $edgeService -ErrorAction Stop;if($service.Status-ne'Running'){throw 'EDGE_SERVICE_NOT_RUNNING'};Probe $config
    [pscustomobject]@{Result='PASS';CertificateActivated=$true;RollbackAvailable=$true;ClientTrustStoreChanged=$false}|ConvertTo-Json;exit 0
  }
  foreach($entry in @(@{Path=$previousCert;Hash=$j.previousCertificateSha256;Class='EDGE_READ'},@{Path=$previousKey;Hash=$j.previousPrivateKeySha256;Class='EDGE_READ'},@{Path=$previousTrust;Hash=$j.previousTrustSha256;Class='ADMIN_EVIDENCE'})){Existing $entry.Path $false 'CERTIFICATE_ACTIVATION_ROLLBACK_NOT_AVAILABLE'|Out-Null;if(-not(Under $entry.Path $fs.classRoots.($entry.Class))-or(Hash $entry.Path)-cne$entry.Hash){throw 'CERTIFICATE_ACTIVATION_ROLLBACK_HASH_MISMATCH'}}
  if($Action-eq'Finalize'){
    [void](Assert-MaintenanceAndDrain $config)
    if((Hash $activeCert)-cne$j.targetCertificateSha256-or(Hash $activeKey)-cne$j.targetPrivateKeySha256-or(Hash $activeTrust)-cne$j.targetTrustSha256){throw 'ACTIVE_CERTIFICATE_HASH_MISMATCH'}
    foreach($file in @($previousCert,$previousKey,$previousTrust,$journal)){Remove-Item -LiteralPath $file -Force};[pscustomobject]@{Result='FINALIZED';RollbackAvailable=$false}|ConvertTo-Json;exit 0
  }
  $actionDrain=Assert-MaintenanceAndDrain $config
  Stop-Service $edgeService;Wait-State $edgeService 'Stopped';try{AtomicCopy $previousCert $activeCert;AtomicCopy $previousKey $activeKey;AtomicCopy $previousTrust $activeTrust;Start-Service $edgeService;Wait-State $edgeService 'Running';if((Hash $activeCert)-cne$j.previousCertificateSha256-or(Hash $activeKey)-cne$j.previousPrivateKeySha256-or(Hash $activeTrust)-cne$j.previousTrustSha256){throw 'CERTIFICATE_ACTIVATION_ROLLBACK_HASH_MISMATCH'};Probe $config}catch{throw 'CERTIFICATE_ACTIVATION_ROLLBACK_FAILED'}
  [pscustomobject]@{Result='ROLLED_BACK';MaintenanceStillEnabled=$true;ClientTrustStoreChanged=$false}|ConvertTo-Json;exit 0
}
$renewal=Existing $RenewalRoot $true 'RENEWAL_ROOT_NOT_FOUND';$manifestPath=Existing (Join-Path $renewal 'renewal-manifest.json') $false 'RENEWAL_MANIFEST_NOT_FOUND';ExpectedHash $manifestPath $ExpectedRenewalManifestSha256 'RENEWAL_MANIFEST_HASH_MISMATCH';$manifest=Get-Content -Raw -LiteralPath $manifestPath|ConvertFrom-Json
$targetCert=Existing (Join-Path $renewal 'server.pem') $false 'RENEWAL_CERTIFICATE_NOT_FOUND';$targetKey=Existing (Join-Path $renewal 'server-key.pem') $false 'RENEWAL_KEY_NOT_FOUND';$trust=Existing $PreOpenClientTrustEvidencePath $false 'PREOPEN_CLIENT_TRUST_NOT_FOUND';ExpectedHash $trust $ExpectedPreOpenClientTrustEvidenceSha256 'PREOPEN_CLIENT_TRUST_HASH_MISMATCH'
$node=Existing $NodePath $false 'NODE_NOT_FOUND';$tlsVerifier=Existing $TlsVerifierPath $false 'TLS_VERIFIER_NOT_FOUND';$httpsVerifier=Existing $HttpsVerifierPath $false 'HTTPS_VERIFIER_NOT_FOUND';ExpectedHash $node $ExpectedNodeSha256 'NODE_HASH_MISMATCH';ExpectedHash $tlsVerifier $ExpectedTlsVerifierSha256 'TLS_VERIFIER_HASH_MISMATCH';ExpectedHash $httpsVerifier $ExpectedHttpsVerifierSha256 'HTTPS_VERIFIER_HASH_MISMATCH'
if($manifest.version-ne2-or$manifest.hostname-cne$config.lan.hostname-or$manifest.files.certificate-cne(Hash $targetCert)-or$manifest.files.privateKey-cne(Hash $targetKey)-or[datetime]$manifest.renewAfter-le(Get-Date).ToUniversalTime()){throw 'RENEWAL_MANIFEST_REJECTED'}
$fsPath=Existing $FileSystemEvidencePath $false 'FILESYSTEM_EVIDENCE_NOT_FOUND';ExpectedHash $fsPath $ExpectedFileSystemEvidenceSha256 'FILESYSTEM_EVIDENCE_HASH_MISMATCH';$fs=Get-Content -Raw -LiteralPath $fsPath|ConvertFrom-Json;if($fs.result-ne'PASS'-or-not$fs.exactAcl-or$fs.descriptorDigest-cne$ExpectedFilesystemDescriptorDigest-or-not(Under $node $fs.classRoots.SHARED_RUNTIME)-or-not(Under $tlsVerifier $fs.classRoots.SHARED_RUNTIME)-or-not(Under $httpsVerifier $fs.classRoots.SHARED_RUNTIME)-or-not(Under $renewal $fs.classRoots.EDGE_READ)-or-not(Under $activeCert $fs.classRoots.EDGE_READ)-or-not(Under $activeKey $fs.classRoots.EDGE_READ)-or-not(Under $activeTrust $fs.classRoots.ADMIN_EVIDENCE)-or-not(Under $trust $fs.classRoots.ADMIN_EVIDENCE)){throw 'CERTIFICATE_ACTIVATION_FILESYSTEM_REJECTED'}
&$node $tlsVerifier $ca $targetCert $targetKey $config.lan.hostname 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw 'RENEWAL_CRYPTOGRAPHIC_VERIFY_FAILED'}
$trustValue=Get-Content -Raw -LiteralPath $trust|ConvertFrom-Json;$caCertificate=New-Object Security.Cryptography.X509Certificates.X509Certificate2($ca);try{$caThumb=$caCertificate.Thumbprint}finally{$caCertificate.Dispose()}
if($trustValue.version-ne4-or$trustValue.result-ne'PASS'-or$trustValue.phase-ne'PREOPEN'-or$trustValue.hostname-cne$config.lan.hostname-or$trustValue.caThumbprint-ine$caThumb-or$trustValue.serverCertificateSha256-cne(Hash $targetCert)-or$trustValue.verifiedClientCount-ne$config.lan.expectedClientCount-or$trustValue.clientSetDigest-cne$config.lan.expectedClientSetDigest-or-not$trustValue.clientAddressMappingVerified-or-not$trustValue.clientAddressOwnershipVerified-or$trustValue.verificationPlanSetDigest-notmatch'^[0-9a-f]{64}$'-or((@($trustValue.allowedClientCidrs)|Sort-Object)-join'|')-cne((@($config.lan.allowedCidrs)|Sort-Object)-join'|')-or$trustValue.httpsVerified-ne$false){throw 'PREOPEN_CLIENT_TRUST_REJECTED'}
$actionDrain=Assert-MaintenanceAndDrain $config
foreach($file in @($previousCert,$previousKey,$previousTrust,$journal)){if(Test-Path -LiteralPath $file){throw 'UNFINISHED_CERTIFICATE_ACTIVATION_PRESENT'}}
Copy-Item -LiteralPath $activeCert -Destination $previousCert;Copy-Item -LiteralPath $activeKey -Destination $previousKey;Copy-Item -LiteralPath $activeTrust -Destination $previousTrust
$record=[ordered]@{version=2;previousCertificateSha256=Hash $previousCert;previousPrivateKeySha256=Hash $previousKey;previousTrustSha256=Hash $previousTrust;targetCertificateSha256=Hash $targetCert;targetPrivateKeySha256=Hash $targetKey;targetTrustSha256=Hash $trust;releaseId=$config.release.id;currentDrainIdentityDigest=$actionDrain.IdentityDigest;currentDrainStateSha256=$actionDrain.DrainStateSha256;currentDrainEdgeProcessId=$actionDrain.EdgeProcessId;currentDrainEdgeProcessStartedAt=$actionDrain.EdgeProcessStartedAt;currentDrainListenerAddress=$actionDrain.ListenerAddress;currentDrainListenerPort=$actionDrain.ListenerPort;currentDrainCompletedAt=$actionDrain.DrainCompletedAt;signedFreshDrainVerified=$true;activatedAt=(Get-Date).ToUniversalTime().ToString('o')};[IO.File]::WriteAllText($journal,($record|ConvertTo-Json),(New-Object Text.UTF8Encoding($false)))
Stop-Service $edgeService
try{AtomicCopy $targetCert $activeCert;AtomicCopy $targetKey $activeKey;AtomicCopy $trust $activeTrust;Start-Service $edgeService;Wait-State $edgeService 'Running';Probe $config}catch{try{AtomicCopy $previousCert $activeCert;AtomicCopy $previousKey $activeKey;AtomicCopy $previousTrust $activeTrust;if((Get-Service $edgeService).Status-ne'Running'){Start-Service $edgeService;Wait-State $edgeService 'Running'};Probe $config}catch{throw 'CERTIFICATE_ACTIVATION_AND_ROLLBACK_FAILED'};throw 'CERTIFICATE_ACTIVATION_ROLLED_BACK'}
[pscustomobject]@{Result='APPLIED';MaintenanceStillEnabled=$true;EdgeRestarted=$true;RollbackAvailable=$true;ClientTrustStoreChanged=$false;FirewallChanged=$false;LegacyProcessesChanged=$false}|ConvertTo-Json
