#Requires -Version 7.2

function Get-EdgeDrainSha256([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Get-EdgeDrainTextSha256([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function Assert-EdgeDrainPinned([string]$Path,[string]$Expected,[string]$Code){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw $Code};$cursor=Get-Item -LiteralPath ([IO.Path]::GetFullPath($Path)) -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'EDGE_DRAIN_REPARSE_REJECTED'};$cursor=$cursor.Parent};if($Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(Get-EdgeDrainSha256 $Path)-cne$Expected.ToLowerInvariant()){throw $Code}}
function Get-EdgeServiceTreeIds([int]$RootId){$all=@(Get-CimInstance Win32_Process -ErrorAction Stop);$ids=[Collections.Generic.HashSet[int]]::new();[void]$ids.Add($RootId);do{$added=$false;foreach($item in $all){if(-not$ids.Contains([int]$item.ProcessId)-and$ids.Contains([int]$item.ParentProcessId)){[void]$ids.Add([int]$item.ProcessId);$added=$true}}}while($added);return @($ids)}
function Invoke-EdgeDrainSignatureVerifier([string]$Node,[string]$Verifier,[string]$PublicKey,[string]$Evidence){
  $start=[Diagnostics.ProcessStartInfo]::new();$start.FileName=$Node;$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true
  foreach($argument in @($Verifier,$PublicKey,$Evidence,'edge-drain')){[void]$start.ArgumentList.Add($argument)}
  $process=[Diagnostics.Process]::new();$process.StartInfo=$start
  try{if(-not$process.Start()){throw 'EDGE_DRAIN_SIGNATURE_VERIFIER_START_FAILED'};$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not$process.WaitForExit(15000)){try{$process.Kill($true)}catch{};if(-not$process.WaitForExit(5000)-or-not$process.HasExited){throw 'EDGE_DRAIN_SIGNATURE_VERIFIER_CLEANUP_FAILED'};throw 'EDGE_DRAIN_SIGNATURE_VERIFIER_TIMEOUT'};$out=$stdout.GetAwaiter().GetResult();$err=$stderr.GetAwaiter().GetResult();if($out.Length+$err.Length-gt65536-or$process.ExitCode-ne0){throw 'EDGE_DRAIN_SIGNATURE_REJECTED'}}finally{$process.Dispose()}
}
function Assert-ExactEdgeDrainIdentity {
  param([string]$EdgeServiceName,[string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,[string]$ReleaseRoot,[string]$ExpectedReleaseManifestSha256,[string]$NodePath,[string]$ExpectedNodeSha256,[string]$DrainStatePath,[string]$ExpectedDrainStateSha256,[string]$AttestationVerifierPath,[string]$ExpectedAttestationVerifierSha256,[string]$EdgeSigningPublicKeyPath,[string]$ExpectedEdgeSigningPublicKeySha256,[int]$MaximumAgeSeconds=300)
  foreach($pin in @(@($RuntimeConfigPath,$ExpectedRuntimeConfigSha256,'EDGE_DRAIN_RUNTIME_HASH_MISMATCH'),@((Join-Path $ReleaseRoot 'release-manifest.json'),$ExpectedReleaseManifestSha256,'EDGE_DRAIN_RELEASE_MANIFEST_HASH_MISMATCH'),@($NodePath,$ExpectedNodeSha256,'EDGE_DRAIN_NODE_HASH_MISMATCH'),@($DrainStatePath,$ExpectedDrainStateSha256,'EDGE_DRAIN_STATE_HASH_MISMATCH'),@($AttestationVerifierPath,$ExpectedAttestationVerifierSha256,'EDGE_DRAIN_VERIFIER_HASH_MISMATCH'),@($EdgeSigningPublicKeyPath,$ExpectedEdgeSigningPublicKeySha256,'EDGE_DRAIN_PUBLIC_KEY_HASH_MISMATCH'))){Assert-EdgeDrainPinned $pin[0] $pin[1] $pin[2]}
  $config=Get-Content -Raw -LiteralPath $RuntimeConfigPath|ConvertFrom-Json;$manifest=Get-Content -Raw -LiteralPath (Join-Path $ReleaseRoot 'release-manifest.json')|ConvertFrom-Json;if($manifest.files.'deploy/local/verify-attestation.mjs'-cne$ExpectedAttestationVerifierSha256.ToLowerInvariant()-or[IO.Path]::GetFullPath($EdgeSigningPublicKeyPath)-ine[IO.Path]::GetFullPath([string]$config.hostSecurity.edgeSigningPublicKeyPath)){throw 'EDGE_DRAIN_VERIFIER_OR_PUBLIC_KEY_ROUTE_REJECTED'};$drainBytesHash=Get-EdgeDrainSha256 $DrainStatePath;$drain=Get-Content -Raw -LiteralPath $DrainStatePath|ConvertFrom-Json
  Invoke-EdgeDrainSignatureVerifier $NodePath $AttestationVerifierPath $EdgeSigningPublicKeyPath $DrainStatePath
  $service=Get-CimInstance Win32_Service -Filter "Name='$EdgeServiceName'" -ErrorAction Stop;if(-not$service-or$service.State-cne'Running'-or[int]$service.ProcessId-le0){throw 'EDGE_DRAIN_SERVICE_NOT_RUNNING'}
  $tree=Get-EdgeServiceTreeIds ([int]$service.ProcessId);$launcher=[IO.Path]::GetFullPath((Join-Path $ReleaseRoot 'deploy\local\start-edge.mjs'));$runtimeFull=[IO.Path]::GetFullPath($RuntimeConfigPath);$nodeFull=[IO.Path]::GetFullPath($NodePath)
  $matches=@(Get-CimInstance Win32_Process -ErrorAction Stop|Where-Object{$tree-contains[int]$_.ProcessId-and$_.ExecutablePath-and[IO.Path]::GetFullPath([string]$_.ExecutablePath)-ieq$nodeFull-and[string]$_.CommandLine-and([string]$_.CommandLine).IndexOf($launcher,[StringComparison]::OrdinalIgnoreCase)-ge0});if($matches.Count-ne1){throw 'EDGE_DRAIN_NODE_PROCESS_IDENTITY_REJECTED'}
  $nodeProcess=Get-Process -Id ([int]$matches[0].ProcessId) -ErrorAction Stop;$completed=[DateTimeOffset]::Parse([string]$drain.completedAt).UtcDateTime;$now=[DateTime]::UtcNow
  $listeners=@(Get-NetTCPConnection -State Listen -LocalPort 443 -ErrorAction Stop|Where-Object{[int]$_.OwningProcess-eq$nodeProcess.Id-and$_.LocalAddress-ceq[string]$config.lan.bindAddress})
  if($drain.attestationType-cne'edge-drain'-or$drain.version-ne2-or$drain.result-cne'DRAINED'-or$drain.activeRequests-ne0){throw 'EDGE_DRAIN_ATTESTATION_FIELDS_REJECTED'}
  if([int]$drain.processId-ne$nodeProcess.Id){throw 'EDGE_DRAIN_PROCESS_ID_MISMATCH'}
  if($drain.releaseId-cne$config.release.id-or$manifest.releaseId-cne$config.release.id-or$drain.runtimeConfigSha256-cne$ExpectedRuntimeConfigSha256.ToLowerInvariant()-or$drain.nodeExecutableSha256-cne$ExpectedNodeSha256.ToLowerInvariant()){throw 'EDGE_DRAIN_RELEASE_RUNTIME_IDENTITY_REJECTED'}
  if($drain.listenerAddress-cne$config.lan.bindAddress-or$drain.listenerPort-ne443-or$listeners.Count-ne1){throw 'EDGE_DRAIN_LISTENER_IDENTITY_REJECTED'}
  $drainAgeSeconds=($now-$completed).TotalSeconds;if($drainAgeSeconds-gt$MaximumAgeSeconds){throw 'EDGE_DRAIN_STALE'};if($drainAgeSeconds-lt-5){throw 'EDGE_DRAIN_FUTURE_TIMESTAMP'}
  $serviceAgain=Get-CimInstance Win32_Service -Filter "Name='$EdgeServiceName'" -ErrorAction Stop;$processAgain=Get-Process -Id $nodeProcess.Id -ErrorAction Stop;$listenersAgain=@(Get-NetTCPConnection -State Listen -LocalPort 443 -ErrorAction Stop|Where-Object{[int]$_.OwningProcess-eq$nodeProcess.Id-and$_.LocalAddress-ceq[string]$config.lan.bindAddress});if([int]$serviceAgain.ProcessId-ne[int]$service.ProcessId-or$processAgain.StartTime.ToUniversalTime()-ne$nodeProcess.StartTime.ToUniversalTime()-or$listenersAgain.Count-ne1-or(Get-EdgeDrainSha256 $DrainStatePath)-cne$drainBytesHash){throw 'EDGE_DRAIN_ACTION_TIME_IDENTITY_CHANGED'}
  $commandDigest=Get-EdgeDrainTextSha256 ([string]$matches[0].CommandLine);$identity=Get-EdgeDrainTextSha256 (@('edge-drain-runtime-v1',[string]$service.ProcessId,$nodeProcess.StartTime.ToUniversalTime().ToString('o'),[string]$nodeProcess.Id,$ExpectedNodeSha256.ToLowerInvariant(),$commandDigest,[IO.Path]::GetFullPath($ReleaseRoot),$ExpectedReleaseManifestSha256.ToLowerInvariant(),$runtimeFull,$ExpectedRuntimeConfigSha256.ToLowerInvariant(),[string]$config.release.id,[string]$config.lan.bindAddress,'443',$drainBytesHash,$completed.ToString('o'))-join"`n")
  return [pscustomobject]@{IdentityDigest=$identity;ServiceProcessId=[int]$service.ProcessId;EdgeProcessId=$nodeProcess.Id;EdgeProcessStartedAt=$nodeProcess.StartTime.ToUniversalTime().ToString('o');NodeExecutableSha256=$ExpectedNodeSha256.ToLowerInvariant();CommandLineSha256=$commandDigest;ReleaseId=[string]$config.release.id;ReleaseManifestSha256=$ExpectedReleaseManifestSha256.ToLowerInvariant();RuntimeConfigSha256=$ExpectedRuntimeConfigSha256.ToLowerInvariant();ListenerAddress=[string]$config.lan.bindAddress;ListenerPort=443;DrainStateSha256=$drainBytesHash;DrainCompletedAt=$completed.ToString('o');SignedDrainVerified=$true;ActiveRequests=0}
}

function Assert-ExactHttpsReleaseProbe {
  param([string]$NodePath,[string]$ExpectedNodeSha256,[string]$VerifierPath,[string]$ExpectedVerifierSha256,[string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,[string]$ExpectedCaCertificateSha256=$script:ExpectedHttpsCaCertificateSha256,[string]$ExpectedServerCertificateSha256=$script:ExpectedHttpsServerCertificateSha256,[string]$ExpectedReleaseId,[ValidateSet(200,503)][int]$ExpectedStatus=503)
  Assert-EdgeDrainPinned $NodePath $ExpectedNodeSha256 'HTTPS_PROBE_NODE_HASH_MISMATCH';Assert-EdgeDrainPinned $VerifierPath $ExpectedVerifierSha256 'HTTPS_PROBE_VERIFIER_HASH_MISMATCH';Assert-EdgeDrainPinned $RuntimeConfigPath $ExpectedRuntimeConfigSha256 'HTTPS_PROBE_RUNTIME_HASH_MISMATCH'
  $config=Get-Content -Raw -LiteralPath $RuntimeConfigPath|ConvertFrom-Json;if(-not$config.lan.enabled-or$config.lan.bindAddress-notmatch'^(?:10\.|192\.168\.|172\.(?:1[6-9]|2[0-9]|3[01])\.)'-or$config.lan.hostname-notmatch'^[a-z0-9.-]+$'-or$config.release.id-cne$ExpectedReleaseId-or-not$config.tls.caCertificatePath-or-not$config.tls.serverCertificatePath){throw 'HTTPS_PROBE_EXACT_TARGET_REJECTED'};Assert-EdgeDrainPinned ([string]$config.tls.caCertificatePath) $ExpectedCaCertificateSha256 'HTTPS_PROBE_CA_HASH_MISMATCH';Assert-EdgeDrainPinned ([string]$config.tls.serverCertificatePath) $ExpectedServerCertificateSha256 'HTTPS_PROBE_SERVER_CERTIFICATE_HASH_MISMATCH'
  $start=[Diagnostics.ProcessStartInfo]::new();$start.FileName=[IO.Path]::GetFullPath($NodePath);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true
  foreach($argument in @([IO.Path]::GetFullPath($VerifierPath),"--connect-address=$($config.lan.bindAddress)","--hostname=$($config.lan.hostname)","--ca=$([IO.Path]::GetFullPath([string]$config.tls.caCertificatePath))","--certificate=$([IO.Path]::GetFullPath([string]$config.tls.serverCertificatePath))","--release-id=$ExpectedReleaseId","--expected-status=$ExpectedStatus")){[void]$start.ArgumentList.Add($argument)}
  foreach($name in @('HTTP_PROXY','HTTPS_PROXY','ALL_PROXY','NODE_EXTRA_CA_CERTS','NODE_TLS_REJECT_UNAUTHORIZED')){[void]$start.Environment.Remove($name)}
  $process=[Diagnostics.Process]::new();$process.StartInfo=$start
  try{if(-not$process.Start()){throw 'HTTPS_PROBE_START_FAILED'};$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not$process.WaitForExit(15000)){try{$process.Kill($true)}catch{};if(-not$process.WaitForExit(5000)-or-not$process.HasExited){throw 'HTTPS_PROBE_CLEANUP_FAILED'};throw 'HTTPS_PROBE_TIMEOUT'};$out=$stdout.GetAwaiter().GetResult();$err=$stderr.GetAwaiter().GetResult();if($out.Length+$err.Length-gt65536-or$process.ExitCode-ne0){throw 'HTTPS_PROBE_FAILED'}}finally{$process.Dispose()}
  return [pscustomobject]@{Result='PASS';ReleaseId=$ExpectedReleaseId;ConnectAddress=[string]$config.lan.bindAddress;Hostname=[string]$config.lan.hostname;Port=443;ExpectedStatus=$ExpectedStatus;RuntimeConfigSha256=$ExpectedRuntimeConfigSha256.ToLowerInvariant();CaCertificateSha256=$ExpectedCaCertificateSha256.ToLowerInvariant();ServerCertificateSha256=$ExpectedServerCertificateSha256.ToLowerInvariant();VerifierSha256=$ExpectedVerifierSha256.ToLowerInvariant();NodeSha256=$ExpectedNodeSha256.ToLowerInvariant();ProxyEnvironmentRemoved=$true;SniAndHostPinned=$true;CaAndServerCertificatePinned=$true}
}
