#Requires -Version 7.2
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'edge-drain-identity.ps1')
$root=Join-Path ([IO.Path]::GetTempPath()) ('metaads-edge-drain-test-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path (Join-Path $root 'deploy\local') -Force|Out-Null
try{
  $runtime=Join-Path $root 'runtime.json';$manifest=Join-Path $root 'release-manifest.json';$node=Join-Path $root 'node.exe';$drain=Join-Path $root 'drain.json';$verifier=Join-Path $root 'deploy\local\verify-attestation.mjs';$publicKey=Join-Path $root 'edge-public.pem';$launcher=Join-Path $root 'deploy\local\start-edge.mjs'
  foreach($file in @($node,$verifier,$publicKey,$launcher)){[IO.File]::WriteAllText($file,'fixture')};$publicKeyFull=[IO.Path]::GetFullPath($publicKey).Replace('\','\\');[IO.File]::WriteAllText($runtime,"{`"release`":{`"id`":`"release-test`"},`"lan`":{`"bindAddress`":`"192.168.10.20`"},`"hostSecurity`":{`"edgeSigningPublicKeyPath`":`"$publicKeyFull`"}}");[IO.File]::WriteAllText($manifest,(ConvertTo-Json @{releaseId='release-test';files=@{'deploy/local/verify-attestation.mjs'=(Get-EdgeDrainSha256 $verifier)}} -Compress))
  $script:mode='PASS';$script:processRead=0;$started=[datetime]'2026-08-28T00:00:00Z'
  function global:Get-CimInstance{param([string]$ClassName,[string]$Filter);if($ClassName-eq'Win32_Service'){return [pscustomobject]@{State='Running';ProcessId=100}};return @([pscustomobject]@{ProcessId=100;ParentProcessId=0;ExecutablePath='wrapper.exe';CommandLine='wrapper'},[pscustomobject]@{ProcessId=200;ParentProcessId=100;ExecutablePath=$node;CommandLine="`"$node`" `"$launcher`" LOCAL_RUNTIME_CONFIG_PATH=`"$runtime`""})}
  function global:Get-Process{param([int]$Id);$script:processRead++;$at=if($script:mode-eq'RESTARTED'-and$script:processRead-gt1){$started.AddSeconds(1)}else{$started};return [pscustomobject]@{Id=$Id;StartTime=$at}}
  function global:Get-NetTCPConnection{if($script:mode-eq'LISTENER_MISMATCH'){return @([pscustomobject]@{OwningProcess=201;LocalAddress='192.168.10.20'})};return @([pscustomobject]@{OwningProcess=200;LocalAddress='192.168.10.20'})}
  function global:Invoke-EdgeDrainSignatureVerifier{}
  function Write-Drain([int]$ProcessId){[IO.File]::WriteAllText($drain,(@{attestationType='edge-drain';version=2;result='DRAINED';processId=$ProcessId;releaseId='release-test';runtimeConfigSha256=(Get-EdgeDrainSha256 $runtime);nodeExecutableSha256=(Get-EdgeDrainSha256 $node);listenerAddress='192.168.10.20';listenerPort=443;activeRequests=0;completedAt=[DateTimeOffset]::UtcNow.ToString('o');signingKeyId=('a'*64);attestationSignature=('A'*86)}|ConvertTo-Json -Compress))}
  function Invoke-Test{Assert-ExactEdgeDrainIdentity -EdgeServiceName 'MetaAdsPerformanceEdge' -RuntimeConfigPath $runtime -ExpectedRuntimeConfigSha256 (Get-EdgeDrainSha256 $runtime) -ReleaseRoot $root -ExpectedReleaseManifestSha256 (Get-EdgeDrainSha256 $manifest) -NodePath $node -ExpectedNodeSha256 (Get-EdgeDrainSha256 $node) -DrainStatePath $drain -ExpectedDrainStateSha256 (Get-EdgeDrainSha256 $drain) -AttestationVerifierPath $verifier -ExpectedAttestationVerifierSha256 (Get-EdgeDrainSha256 $verifier) -EdgeSigningPublicKeyPath $publicKey -ExpectedEdgeSigningPublicKeySha256 (Get-EdgeDrainSha256 $publicKey) -MaximumAgeSeconds 300}
  Write-Drain 200;$fixtureDrain=Get-Content -Raw -LiteralPath $drain|ConvertFrom-Json;if(([DateTimeOffset]::UtcNow-[DateTimeOffset]::Parse([string]$fixtureDrain.completedAt)).TotalSeconds-gt2){throw 'EDGE_DRAIN_FIXTURE_STALE'};$pass=Invoke-Test;if($pass.EdgeProcessId-ne200-or$pass.ListenerPort-ne443-or-not$pass.SignedDrainVerified){throw 'EDGE_DRAIN_HAPPY_PATH_FAILED'}
  $wrongPidRejected=$false;Write-Drain 201;try{Invoke-Test|Out-Null}catch{$wrongPidRejected=$_.Exception.Message-eq'EDGE_DRAIN_PROCESS_ID_MISMATCH'}
  $script:mode='RESTARTED';$script:processRead=0;Write-Drain 200;$restartedRejected=$false;try{Invoke-Test|Out-Null}catch{$restartedRejected=$_.Exception.Message-eq'EDGE_DRAIN_ACTION_TIME_IDENTITY_CHANGED'}
  $script:mode='LISTENER_MISMATCH';$script:processRead=0;Write-Drain 200;$listenerRejected=$false;try{Invoke-Test|Out-Null}catch{$listenerRejected=$_.Exception.Message-eq'EDGE_DRAIN_LISTENER_IDENTITY_REJECTED'}
  if(-not$wrongPidRejected-or-not$restartedRejected-or-not$listenerRejected){throw 'EDGE_DRAIN_NEGATIVE_TEST_FAILED'}
  [pscustomobject]@{result='PASS';wrongPidRejected=$true;restartedProcessRejected=$true;listenerOwnerMismatchRejected=$true}|ConvertTo-Json -Compress
}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
