#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Apply','Verify')][string]$Action='Plan',[ValidateSet('RETURN_FORWARD','ACCEPT_ROLLBACK_DROP_PRESERVED')][string]$Mode,
  [string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,[string]$RollbackJournalPath,[string]$ExpectedRollbackJournalSha256,
  [string]$RollbackEvidencePath,[string]$ExpectedRollbackEvidenceSha256,[string]$RestoreReceiptPublicKeyPath,[string]$ExpectedRestoreReceiptPublicKeySha256,
  [string]$NodePath,[string]$ExpectedNodeSha256,[string]$AttestationVerifierPath,[string]$ExpectedAttestationVerifierSha256,
  [string]$PsqlPath,[string]$ExpectedPsqlSha256,[string]$PgPassFile,[string]$ExpectedPgPassSha256,[string]$CaCertificatePath,[string]$ExpectedCaCertificateSha256,
  [string]$MaintenanceFlagPath,[string]$ExpectedMaintenanceFlagSha256,[string]$FinalizationJournalPath,[string]$ExpectedFinalizationJournalSha256,[string]$ExpectedApplyPlanSha256,
  [string]$ConfirmProjectRef,[string]$ConfirmDatabaseHost,[string]$ConfirmDatabaseName,[string]$ConfirmDatabaseSchema,[string]$ConfirmDatabaseUser,
  [ValidateSet('Apply','VerifyEvidence')][string]$PlannedAction,[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function NoReparse([string]$Path){$cursor=Get-Item -LiteralPath ([IO.Path]::GetFullPath($Path)) -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'ROLLBACK_FINALIZE_REPARSE_REJECTED'};$cursor=$cursor.Parent}}
function Pinned([string]$Path,[string]$Expected,[string]$Code){if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw $Code};$full=[IO.Path]::GetFullPath($Path);NoReparse $full;if($Expected-notmatch'^[a-fA-F0-9]{64}$'-or(Hash $full)-cne$Expected.ToLowerInvariant()){throw $Code};return $full}
function ReadJson([string]$Path,[string]$Code){$item=Get-Item -LiteralPath $Path -Force;if($item.PSIsContainer-or$item.Length-lt1-or$item.Length-gt16777216-or($item.Attributes-band[IO.FileAttributes]::ReparsePoint)){throw $Code};try{return Get-Content -Raw -LiteralPath $item.FullName|ConvertFrom-Json}catch{throw $Code}}
function Quote([string]$Value){if($Value-notmatch'^[a-z][a-z0-9_]{0,62}$'){throw 'ROLLBACK_FINALIZE_IDENTIFIER_REJECTED'};return '"'+$Value+'"'}
function Stop-Tree($Process){if($Process-and-not$Process.HasExited){$Process.Kill($true);if(-not$Process.WaitForExit(5000)){throw 'ROLLBACK_FINALIZE_PROCESS_TREE_KILL_TIMEOUT'}}}
function Invoke-Bounded([string]$File,[string[]]$Arguments,[hashtable]$Environment,[string]$Code){
  $info=[Diagnostics.ProcessStartInfo]::new();$info.FileName=$File;$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true
  foreach($name in @('DATABASE_URL','PGPASSWORD','PGPASSFILE','PGSSLMODE','PGSSLROOTCERT','PGOPTIONS')){$info.Environment.Remove($name)|Out-Null};foreach($entry in $Environment.GetEnumerator()){$info.Environment[$entry.Key]=$entry.Value};foreach($argument in $Arguments){$info.ArgumentList.Add($argument)}
  $process=[Diagnostics.Process]::new();$process.StartInfo=$info;$watch=[Diagnostics.Stopwatch]::StartNew();try{if(-not$process.Start()){throw "$Code`_START_FAILED"};$outTask=$process.StandardOutput.ReadToEndAsync();$errTask=$process.StandardError.ReadToEndAsync();while(-not$process.WaitForExit(250)){if($watch.Elapsed.TotalMinutes-ge5){Stop-Tree $process;throw "$Code`_TIMEOUT"}};$stdout=$outTask.GetAwaiter().GetResult();$stderr=$errTask.GetAwaiter().GetResult();if(($stdout.Length+$stderr.Length)-gt1048576){throw "$Code`_OUTPUT_LIMIT"};if($process.ExitCode-ne0){throw $Code};return $stdout.Trim()}finally{Stop-Tree $process;$process.Dispose();$watch.Stop()}
}
function New-FinalizePlan([string]$Intended){
  if($Intended-notin@('Apply','VerifyEvidence')){throw 'ROLLBACK_FINALIZE_PLANNED_ACTION_REQUIRED'}
  $p=[ordered]@{mode=$Mode;runtimeConfigPath=Get-ApprovalPath $RuntimeConfigPath 'ROLLBACK_FINALIZE_RUNTIME_REQUIRED';runtimeConfigSha256=Get-ApprovalHash $ExpectedRuntimeConfigSha256 'ROLLBACK_FINALIZE_RUNTIME_HASH_REQUIRED';rollbackJournalPath=Get-ApprovalPath $RollbackJournalPath 'ROLLBACK_FINALIZE_JOURNAL_REQUIRED';rollbackJournalSha256=Get-ApprovalHash $ExpectedRollbackJournalSha256 'ROLLBACK_FINALIZE_JOURNAL_HASH_REQUIRED';rollbackEvidencePath=Get-ApprovalPath $RollbackEvidencePath 'ROLLBACK_FINALIZE_EVIDENCE_REQUIRED';rollbackEvidenceSha256=Get-ApprovalHash $ExpectedRollbackEvidenceSha256 'ROLLBACK_FINALIZE_EVIDENCE_HASH_REQUIRED';maintenanceFlagPath=Get-ApprovalPath $MaintenanceFlagPath 'ROLLBACK_FINALIZE_MAINTENANCE_REQUIRED';maintenanceFlagSha256=Get-ApprovalHash $ExpectedMaintenanceFlagSha256 'ROLLBACK_FINALIZE_MAINTENANCE_HASH_REQUIRED';projectRef=Get-ApprovalText $ConfirmProjectRef '^[a-z]{20}$' 'ROLLBACK_FINALIZE_PROJECT_REQUIRED';databaseHost=Get-ApprovalText $ConfirmDatabaseHost '^(?:db\.[a-z]{20}\.supabase\.co|[a-z0-9-]+\.pooler\.supabase\.com)$' 'ROLLBACK_FINALIZE_HOST_REQUIRED';databaseName=Get-ApprovalText $ConfirmDatabaseName '^[a-z][a-z0-9_]{0,62}$' 'ROLLBACK_FINALIZE_DATABASE_REQUIRED';databaseSchema=Get-ApprovalText $ConfirmDatabaseSchema '^[a-z][a-z0-9_]{0,62}$' 'ROLLBACK_FINALIZE_SCHEMA_REQUIRED';databaseUser=Get-ApprovalText $ConfirmDatabaseUser '^[a-z][a-z0-9_]{0,62}$' 'ROLLBACK_FINALIZE_USER_REQUIRED';finalizationJournalPath=Get-ApprovalPath $FinalizationJournalPath 'ROLLBACK_FINALIZE_OUTPUT_REQUIRED'}
  if($Intended-eq'VerifyEvidence'){$p.expectedApplyPlanSha256=Get-ApprovalHash $ExpectedApplyPlanSha256 'ROLLBACK_FINALIZE_APPLY_PLAN_HASH_REQUIRED';$p.finalizationJournalSha256=Get-ApprovalHash $ExpectedFinalizationJournalSha256 'ROLLBACK_FINALIZE_OUTPUT_HASH_REQUIRED'}
  New-ApprovalPlan $PSCommandPath $Intended $p "Exact Supabase rollback boundary finalization: $Mode" $(if($Mode-eq'RETURN_FORWARD'){'Drops the restored legacy schema and atomically renames the preserved forward schema back to the production name'}else{'Accepts the restored legacy schema and irreversibly drops only the exact preserved forward schema'}) 'Before Apply, take and validate a fresh backup; rollback after the schema drop requires the separately approved restore procedure'
}

$intended=if($Action-eq'Apply'){'Apply'}else{'VerifyEvidence'};$plan=New-FinalizePlan $(if($Action-eq'Plan'){$PlannedAction}else{$intended});if($Action-eq'Plan'){$plan|ConvertTo-Json -Depth 12;exit 0};Assert-ApprovedPlan $plan ([bool]$Approved) $ApprovedPlanSha256
$runtime=Pinned $RuntimeConfigPath $ExpectedRuntimeConfigSha256 'ROLLBACK_FINALIZE_RUNTIME_HASH_MISMATCH';$rollbackJournal=Pinned $RollbackJournalPath $ExpectedRollbackJournalSha256 'ROLLBACK_FINALIZE_JOURNAL_HASH_MISMATCH';$rollbackEvidence=Pinned $RollbackEvidencePath $ExpectedRollbackEvidenceSha256 'ROLLBACK_FINALIZE_EVIDENCE_HASH_MISMATCH';$public=Pinned $RestoreReceiptPublicKeyPath $ExpectedRestoreReceiptPublicKeySha256 'ROLLBACK_FINALIZE_PUBLIC_KEY_HASH_MISMATCH';$node=Pinned $NodePath $ExpectedNodeSha256 'ROLLBACK_FINALIZE_NODE_HASH_MISMATCH';$verifier=Pinned $AttestationVerifierPath $ExpectedAttestationVerifierSha256 'ROLLBACK_FINALIZE_VERIFIER_HASH_MISMATCH';$psql=Pinned $PsqlPath $ExpectedPsqlSha256 'ROLLBACK_FINALIZE_PSQL_HASH_MISMATCH';$pgpass=Pinned $PgPassFile $ExpectedPgPassSha256 'ROLLBACK_FINALIZE_PGPASS_HASH_MISMATCH';$ca=Pinned $CaCertificatePath $ExpectedCaCertificateSha256 'ROLLBACK_FINALIZE_CA_HASH_MISMATCH';[void](Pinned $MaintenanceFlagPath $ExpectedMaintenanceFlagSha256 'ROLLBACK_FINALIZE_MAINTENANCE_HASH_MISMATCH')
$config=ReadJson $runtime 'ROLLBACK_FINALIZE_RUNTIME_INVALID';$journal=ReadJson $rollbackJournal 'ROLLBACK_FINALIZE_JOURNAL_INVALID';$evidence=ReadJson $rollbackEvidence 'ROLLBACK_FINALIZE_EVIDENCE_INVALID'
[void](Invoke-Bounded $node @($verifier,$public,$rollbackEvidence,'legacy-database-rollback') @{} 'ROLLBACK_FINALIZE_SIGNATURE_REJECTED')
$preserved=[string]$journal.preservedSchema;if($journal.version-ne3-or$journal.state-cne'COMPLETE_MAINTENANCE_REQUIRED'-or-not$journal.originalSchemaPreserved-or$journal.partialTargetPossible-or$evidence.attestationType-cne'legacy-database-rollback'-or$evidence.result-cne'PASS'-or$evidence.preservedSchema-cne$preserved-or$evidence.databaseProjectRef-cne$ConfirmProjectRef-or$evidence.databaseHost-cne$ConfirmDatabaseHost-or$evidence.databaseName-cne$ConfirmDatabaseName-or$evidence.databaseSchema-cne$ConfirmDatabaseSchema-or$preserved-notmatch('^'+[regex]::Escape($ConfirmDatabaseSchema)+'_pre_rollback_[0-9a-f]{16}$')){throw 'ROLLBACK_FINALIZE_BOUNDARY_EVIDENCE_REJECTED'}
if($config.database.provider-cne'supabase_postgres'-or$config.database.projectRef-cne$ConfirmProjectRef-or$config.database.host-cne$ConfirmDatabaseHost-or$config.database.name-cne$ConfirmDatabaseName-or$config.database.schema-cne$ConfirmDatabaseSchema-or$config.database.migrationUser-cne$ConfirmDatabaseUser-or$config.database.caCertificateSha256-cne$ExpectedCaCertificateSha256.ToLowerInvariant()){throw 'ROLLBACK_FINALIZE_CONFIG_CONFIRMATION_MISMATCH'}
$environment=@{PGPASSFILE=$pgpass;PGSSLMODE='verify-full';PGSSLROOTCERT=$ca;PGOPTIONS='-c statement_timeout=240000 -c lock_timeout=30000'};$base=@("--host=$ConfirmDatabaseHost",'--port=5432',"--username=$ConfirmDatabaseUser","--dbname=$ConfirmDatabaseName",'--no-password','--tuples-only','--no-align','--set=ON_ERROR_STOP=1');$schema=Quote $ConfirmDatabaseSchema;$saved=Quote $preserved;$stateSql="SELECT (to_regnamespace('$ConfirmDatabaseSchema') IS NOT NULL)::int || '|' || (to_regnamespace('$preserved') IS NOT NULL)::int"
if($Action-eq'Apply'){
  if(Test-Path -LiteralPath $FinalizationJournalPath){throw 'ROLLBACK_FINALIZE_OUTPUT_ALREADY_EXISTS'};$state=Invoke-Bounded $psql ($base+@("--command=$stateSql")) $environment 'ROLLBACK_FINALIZE_STATE_CHECK';if($state-cne'1|1'){throw 'ROLLBACK_FINALIZE_SCHEMA_STATE_REJECTED'}
  $sql=if($Mode-eq'RETURN_FORWARD'){"BEGIN; DROP SCHEMA $schema CASCADE; ALTER SCHEMA $saved RENAME TO $schema; COMMIT;"}else{"BEGIN; DROP SCHEMA $saved CASCADE; COMMIT;"};[void](Invoke-Bounded $psql ($base+@("--command=$sql")) $environment 'ROLLBACK_FINALIZE_MUTATION_FAILED')
  $after=Invoke-Bounded $psql ($base+@("--command=$stateSql")) $environment 'ROLLBACK_FINALIZE_STATE_VERIFY';if($after-cne'1|0'){throw 'ROLLBACK_FINALIZE_POST_STATE_REJECTED'}
  $record=[ordered]@{version=1;state='COMPLETE_MAINTENANCE_REQUIRED';mode=$Mode;approvalPlanSha256=$plan.planSha256;rollbackJournalSha256=$ExpectedRollbackJournalSha256.ToLowerInvariant();rollbackEvidenceSha256=$ExpectedRollbackEvidenceSha256.ToLowerInvariant();databaseProjectRef=$ConfirmProjectRef;databaseHost=$ConfirmDatabaseHost;databaseName=$ConfirmDatabaseName;databaseSchema=$ConfirmDatabaseSchema;preservedSchema=$preserved;currentSchemaPresent=$true;preservedSchemaAbsent=$true;maintenanceMustRemainEnabled=$true;completedAt=[datetimeoffset]::UtcNow.ToString('o')};$bytes=[Text.Encoding]::UTF8.GetBytes(($record|ConvertTo-Json -Compress));try{$stream=[IO.File]::Open([IO.Path]::GetFullPath($FinalizationJournalPath),[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}}finally{[Array]::Clear($bytes,0,$bytes.Length)}
  [pscustomobject]@{Result='COMPLETE_MAINTENANCE_REQUIRED';Mode=$Mode;CurrentSchemaPresent=$true;PreservedSchemaAbsent=$true;DatabaseSecretEmitted=$false}|ConvertTo-Json;exit 0
}
$final=Pinned $FinalizationJournalPath $ExpectedFinalizationJournalSha256 'ROLLBACK_FINALIZE_OUTPUT_HASH_MISMATCH';$record=ReadJson $final 'ROLLBACK_FINALIZE_OUTPUT_INVALID';$state=Invoke-Bounded $psql ($base+@("--command=$stateSql")) $environment 'ROLLBACK_FINALIZE_VERIFY_STATE';if($record.version-ne1-or$record.state-cne'COMPLETE_MAINTENANCE_REQUIRED'-or$record.mode-cne$Mode-or$record.approvalPlanSha256-cne$ExpectedApplyPlanSha256.ToLowerInvariant()-or$record.rollbackJournalSha256-cne$ExpectedRollbackJournalSha256.ToLowerInvariant()-or$record.rollbackEvidenceSha256-cne$ExpectedRollbackEvidenceSha256.ToLowerInvariant()-or$state-cne'1|0'-or-not$record.maintenanceMustRemainEnabled){throw 'ROLLBACK_FINALIZE_VERIFY_REJECTED'}
[pscustomobject]@{Result='PASS';Mode=$Mode;CurrentSchemaPresent=$true;PreservedSchemaAbsent=$true;MaintenanceRetained=$true}|ConvertTo-Json
