#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Install','Start','Stop','Remove','Verify')][string]$Action='Plan',
  [string]$StagedWrapperPath,[string]$ExpectedWrapperSha256,[string]$NodePath,[string]$ExpectedNodeSha256,
  [string]$ReleaseRoot,[string]$ReleaseVerifierPath,[string]$ExpectedReleaseVerifierSha256,[string]$ExpectedReleaseManifestSha256,[string]$ExpectedReleaseId,[string]$ExpectedCoreLauncherSha256,[string]$ExpectedEdgeLauncherSha256,
  [string]$ServiceRoot,[string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,[string]$ApiConfigPath,[string]$ExpectedApiConfigSha256,[string]$CoreLogRoot,[string]$EdgeLogRoot,
  [string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,[string]$PrincipalRightsEvidencePath,[string]$ExpectedPrincipalRightsEvidenceSha256,[string]$PrincipalRightsScriptPath,[string]$ExpectedPrincipalRightsScriptSha256,
  [string]$CoreServiceAccount,[PSCredential]$CoreServiceCredential,
  [string]$EdgeServiceAccount,[PSCredential]$EdgeServiceCredential,[string]$BackupAccount,
  [ValidateSet('Install','Start','Stop','Remove')][string]$PlannedAction,[string]$ApprovedPlanSha256,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
$ids=@('MetaAdsPerformanceCore','MetaAdsPerformanceEdge')
$serviceSddl='D:P(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)'
function NoReparse([string]$Path){$cursor=Get-Item -LiteralPath ([IO.Path]::GetFullPath($Path)) -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw'SERVICE_REPARSE_POINT_REJECTED'};$cursor=$cursor.Parent}}
function File([string]$Path,[string]$Code){if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw $Code};$p=[IO.Path]::GetFullPath($Path);NoReparse $p;return$p}
function Dir([string]$Path,[string]$Code){if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType Container)){throw $Code};$p=[IO.Path]::GetFullPath($Path).TrimEnd('\');NoReparse $p;if($p-eq[IO.Path]::GetPathRoot($p).TrimEnd('\')-or$p-eq[Environment]::GetFolderPath('UserProfile').TrimEnd('\')){throw 'SERVICE_ROOT_FORBIDDEN'};return$p}
function Hash([string]$Path,[string]$Expected,[string]$Code){if($Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash-ine$Expected){throw $Code}}
function Digest([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function Wait-State([string]$Name,[string]$State,[int]$Seconds=30){$deadline=(Get-Date).AddSeconds($Seconds);do{if((Get-Service -Name $Name -ErrorAction Stop).Status-eq$State){return};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw'SERVICE_STATE_TIMEOUT'}
function Sid([string]$Account){if(-not$Account-or$Account-notmatch'^([^\\]+)\\([^\\]+)$'-or$Matches[1]-ine$env:COMPUTERNAME){throw 'LOCAL_SERVICE_ACCOUNT_REQUIRED'};$local=Get-LocalUser -Name $Matches[2] -ErrorAction Stop;if(-not$local.Enabled){throw 'LOCAL_SERVICE_ACCOUNT_DISABLED'};return$local.SID.Value}
function AssertNonAdmin([string]$Account){$sid=Sid $Account;if($sid-in@('S-1-5-18','S-1-5-19','S-1-5-20')){throw 'BUILTIN_SERVICE_ACCOUNT_REJECTED'};foreach($groupSid in @('S-1-5-32-544','S-1-5-32-547','S-1-5-32-548','S-1-5-32-549','S-1-5-32-550','S-1-5-32-551','S-1-5-32-555','S-1-5-32-556','S-1-5-32-562','S-1-5-32-569','S-1-5-32-573','S-1-5-32-580')){$members=@(Get-LocalGroupMember -SID $groupSid -ErrorAction Stop);foreach($member in $members){if($member.SID.Value-eq$sid){throw 'PRIVILEGED_SERVICE_ACCOUNT_REJECTED'};if([string]$member.ObjectClass-eq'Group'){throw 'PRIVILEGED_GROUP_NESTING_UNVERIFIABLE'}}};return$sid}
function UnderAny([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');return@($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function CoreXml($Node,$Launcher,$Release,$Runtime,$Api,$Log){$t=Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'service.xml.template');return$t.Replace('__NODE_PATH__',[Security.SecurityElement]::Escape($Node)).Replace('__LAUNCHER_PATH__',[Security.SecurityElement]::Escape($Launcher)).Replace('__RELEASE_ROOT__',[Security.SecurityElement]::Escape($Release)).Replace('__RUNTIME_CONFIG_PATH__',[Security.SecurityElement]::Escape($Runtime)).Replace('__API_CONFIG_PATH__',[Security.SecurityElement]::Escape($Api)).Replace('__LOG_PATH__',[Security.SecurityElement]::Escape($Log))}
function EdgeXml($Node,$Launcher,$Release,$Runtime,$Log){$t=Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'edge-service.xml.template');return$t.Replace('__NODE_PATH__',[Security.SecurityElement]::Escape($Node)).Replace('__EDGE_LAUNCHER_PATH__',[Security.SecurityElement]::Escape($Launcher)).Replace('__RELEASE_ROOT__',[Security.SecurityElement]::Escape($Release)).Replace('__RUNTIME_CONFIG_PATH__',[Security.SecurityElement]::Escape($Runtime)).Replace('__LOG_PATH__',[Security.SecurityElement]::Escape($Log))}
function ConfigureService($Wrapper,$Id,$Account,$Credential,[string]$StartMode){&$Wrapper install|Out-Null;if($LASTEXITCODE-ne0){throw "SERVICE_INSTALL_FAILED_$Id"};$svc=Get-CimInstance Win32_Service -Filter "Name='$Id'";$password=$Credential.GetNetworkCredential().Password;try{$change=Invoke-CimMethod -InputObject $svc -MethodName Change -Arguments @{StartName=$Account;StartPassword=$password;StartMode=$StartMode}}finally{$password=$null};if($change.ReturnValue-ne0){throw "SERVICE_ACCOUNT_CONFIGURATION_FAILED_$Id"};&sc.exe sidtype $Id unrestricted|Out-Null;if($LASTEXITCODE-ne0){throw "SERVICE_SID_CONFIGURATION_FAILED_$Id"};&sc.exe sdset $Id $serviceSddl|Out-Null;if($LASTEXITCODE-ne0){throw "SERVICE_DACL_CONFIGURATION_FAILED_$Id"}}
function New-ServiceApprovalPlan([string]$IntendedAction){
  if($IntendedAction-notin@('Install','Start','Stop','Remove')){throw'PLANNED_ACTION_REQUIRED'}
  $parameters=[ordered]@{serviceIds=$ids;serviceRoot=(Get-ApprovalPath $ServiceRoot 'SERVICE_PLAN_ROOT_REQUIRED');wrapperSha256=(Get-ApprovalHash $ExpectedWrapperSha256 'SERVICE_PLAN_WRAPPER_HASH_REQUIRED')}
  if($IntendedAction-ne'Remove'){
    foreach($account in @($CoreServiceAccount,$EdgeServiceAccount,$BackupAccount)){if($account-notmatch'^[^\\]+\\[^\\]+$'){throw'SERVICE_PLAN_ACCOUNT_REQUIRED'}}
    if(@(@($CoreServiceAccount,$EdgeServiceAccount,$BackupAccount)|Sort-Object -Unique).Count-ne3){throw'SERVICE_PLAN_ACCOUNTS_MUST_BE_DISTINCT'}
    if($ExpectedReleaseId-notmatch'^[a-z0-9][a-z0-9._-]{0,62}$'){throw'SERVICE_PLAN_RELEASE_ID_REQUIRED'}
    $parameters=[ordered]@{serviceIds=$ids;serviceRoot=(Get-ApprovalPath $ServiceRoot 'SERVICE_PLAN_ROOT_REQUIRED');wrapperSha256=(Get-ApprovalHash $ExpectedWrapperSha256 'SERVICE_PLAN_WRAPPER_HASH_REQUIRED');releaseId=$ExpectedReleaseId;releaseRoot=(Get-ApprovalPath $ReleaseRoot 'SERVICE_PLAN_RELEASE_ROOT_REQUIRED');releaseManifestSha256=(Get-ApprovalHash $ExpectedReleaseManifestSha256 'SERVICE_PLAN_RELEASE_MANIFEST_HASH_REQUIRED');releaseVerifierPath=(Get-ApprovalPath $ReleaseVerifierPath 'SERVICE_PLAN_RELEASE_VERIFIER_PATH_REQUIRED');releaseVerifierSha256=(Get-ApprovalHash $ExpectedReleaseVerifierSha256 'SERVICE_PLAN_RELEASE_VERIFIER_HASH_REQUIRED');nodePath=(Get-ApprovalPath $NodePath 'SERVICE_PLAN_NODE_PATH_REQUIRED');nodeSha256=(Get-ApprovalHash $ExpectedNodeSha256 'SERVICE_PLAN_NODE_HASH_REQUIRED');coreLauncherSha256=(Get-ApprovalHash $ExpectedCoreLauncherSha256 'SERVICE_PLAN_CORE_LAUNCHER_HASH_REQUIRED');edgeLauncherSha256=(Get-ApprovalHash $ExpectedEdgeLauncherSha256 'SERVICE_PLAN_EDGE_LAUNCHER_HASH_REQUIRED');runtimeConfigPath=(Get-ApprovalPath $RuntimeConfigPath 'SERVICE_PLAN_RUNTIME_PATH_REQUIRED');runtimeConfigSha256=(Get-ApprovalHash $ExpectedRuntimeConfigSha256 'SERVICE_PLAN_RUNTIME_HASH_REQUIRED');apiConfigPath=(Get-ApprovalPath $ApiConfigPath 'SERVICE_PLAN_API_PATH_REQUIRED');apiConfigSha256=(Get-ApprovalHash $ExpectedApiConfigSha256 'SERVICE_PLAN_API_HASH_REQUIRED');coreLogRoot=(Get-ApprovalPath $CoreLogRoot 'SERVICE_PLAN_CORE_LOG_ROOT_REQUIRED');edgeLogRoot=(Get-ApprovalPath $EdgeLogRoot 'SERVICE_PLAN_EDGE_LOG_ROOT_REQUIRED');filesystemEvidencePath=(Get-ApprovalPath $FileSystemEvidencePath 'SERVICE_PLAN_FILESYSTEM_EVIDENCE_PATH_REQUIRED');filesystemEvidenceSha256=(Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'SERVICE_PLAN_FILESYSTEM_EVIDENCE_HASH_REQUIRED');principalRightsEvidencePath=(Get-ApprovalPath $PrincipalRightsEvidencePath 'SERVICE_PLAN_RIGHTS_EVIDENCE_PATH_REQUIRED');principalRightsEvidenceSha256=(Get-ApprovalHash $ExpectedPrincipalRightsEvidenceSha256 'SERVICE_PLAN_RIGHTS_EVIDENCE_HASH_REQUIRED');principalRightsScriptPath=(Get-ApprovalPath $PrincipalRightsScriptPath 'SERVICE_PLAN_RIGHTS_SCRIPT_PATH_REQUIRED');principalRightsScriptSha256=(Get-ApprovalHash $ExpectedPrincipalRightsScriptSha256 'SERVICE_PLAN_RIGHTS_SCRIPT_HASH_REQUIRED');coreServiceAccount=$CoreServiceAccount;edgeServiceAccount=$EdgeServiceAccount;backupAccount=$BackupAccount}
    if($IntendedAction-eq'Install'){$parameters.stagedWrapperPath=Get-ApprovalPath $StagedWrapperPath 'SERVICE_PLAN_STAGED_WRAPPER_PATH_REQUIRED'}
  }
  $target="Exact Windows services $($ids-join',') under $($parameters.serviceRoot)"+$(if($IntendedAction-ne'Remove'){" for release $ExpectedReleaseId"}else{''})
  $impact=if($IntendedAction-eq'Install'){'Installs the exact hash-pinned wrappers under distinct non-admin accounts and leaves both services Manual/stopped'}elseif($IntendedAction-eq'Start'){'Starts Core and starts Edge only when the exact runtime is LAN-enabled; it does not target legacy 3100/4100'}elseif($IntendedAction-eq'Stop'){'Stops only the two exact services and sets both to Manual'}else{'Stops/uninstalls only the two exact services and removes their wrapper/XML files; data, DB, firewall, and legacy processes remain unchanged'}
  $rollback=if($IntendedAction-eq'Install'){'Remove only through a separately approved Remove plan'}elseif($IntendedAction-eq'Start'){'Stop only through a separately approved Stop plan'}elseif($IntendedAction-eq'Stop'){'Restart only through a new approved Start plan'}else{'Reinstall only through a new approved Install plan with matching service credentials'}
  return New-ApprovalPlan $PSCommandPath $IntendedAction $parameters $target $impact $rollback
}

if($Action-eq'Plan'){New-ServiceApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0}
$serviceMutation=if($Action-in@('Install','Start','Stop','Remove')){$Action}else{$null};if($serviceMutation){Assert-ApprovedPlan (New-ServiceApprovalPlan $serviceMutation) ([bool]$Approved) $ApprovedPlanSha256}
$root=Dir $ServiceRoot 'SERVICE_ROOT_NOT_FOUND';$coreExe=Join-Path $root 'MetaAdsPerformanceCore.exe';$edgeExe=Join-Path $root 'MetaAdsPerformanceEdge.exe';$coreXmlPath=Join-Path $root 'MetaAdsPerformanceCore.xml';$edgeXmlPath=Join-Path $root 'MetaAdsPerformanceEdge.xml'
if($Action-eq'Remove'){
  foreach($id in $ids){
    $exe=Join-Path $root "$id.exe";$svc=Get-CimInstance Win32_Service -Filter "Name='$id'" -ErrorAction SilentlyContinue
    if($svc){
      $verifiedExe=File $exe "INSTALLED_WRAPPER_NOT_FOUND_$id";Hash $verifiedExe $ExpectedWrapperSha256 'INSTALLED_WRAPPER_HASH_MISMATCH'
      $expectedImage='"'+$verifiedExe+'"';if([string]$svc.PathName-cne$expectedImage){throw "SERVICE_IMAGE_PATH_MISMATCH_$id"}
      $state=Get-Service -Name $id -ErrorAction Stop;if($state.Status-ne'Stopped'){Stop-Service -Name $id -Force;Wait-State $id 'Stopped'}
      Hash $verifiedExe $ExpectedWrapperSha256 'INSTALLED_WRAPPER_HASH_CHANGED_BEFORE_UNINSTALL'
      &$verifiedExe uninstall|Out-Null;if($LASTEXITCODE-ne0){throw "SERVICE_UNINSTALL_FAILED_$id"}
    }elseif(Test-Path -LiteralPath $exe){$verifiedExe=File $exe "INSTALLED_WRAPPER_NOT_FOUND_$id";Hash $verifiedExe $ExpectedWrapperSha256 'INSTALLED_WRAPPER_HASH_MISMATCH'}
    if(Get-Service -Name $id -ErrorAction SilentlyContinue){throw "SERVICE_UNINSTALL_VERIFY_FAILED_$id"}
  }
  foreach($file in @($coreExe,$edgeExe,$coreXmlPath,$edgeXmlPath)){if(Test-Path -LiteralPath $file){Remove-Item -LiteralPath $file -Force}}
  if($ids|Where-Object{Get-CimInstance Win32_Service -Filter "Name='$_'" -ErrorAction SilentlyContinue}){throw'SERVICE_UNINSTALL_VERIFY_FAILED'}
  [pscustomobject]@{Result='REMOVED';ServiceAbsenceVerified=$true;WrapperHashVerified=$true;ServiceImagePathVerified=$true;DataRemoved=$false;LegacyProcessesChanged=$false}|ConvertTo-Json;exit 0
}
$node=File $NodePath 'NODE_BINARY_NOT_FOUND';$runtime=File $RuntimeConfigPath 'RUNTIME_CONFIG_NOT_FOUND';$api=File $ApiConfigPath 'API_CONFIG_NOT_FOUND';$release=Dir $ReleaseRoot 'RELEASE_ROOT_NOT_FOUND';$releaseVerifier=File $ReleaseVerifierPath 'RELEASE_VERIFIER_NOT_FOUND';$coreLauncher=File (Join-Path $release 'deploy\local\launch-local-bundle.mjs') 'CORE_LAUNCHER_NOT_FOUND';$edgeLauncher=File (Join-Path $release 'deploy\local\start-edge.mjs') 'EDGE_LAUNCHER_NOT_FOUND';$coreLog=Dir $CoreLogRoot 'CORE_LOG_ROOT_NOT_FOUND';$edgeLog=Dir $EdgeLogRoot 'EDGE_LOG_ROOT_NOT_FOUND'
Hash $runtime $ExpectedRuntimeConfigSha256 'RUNTIME_CONFIG_HASH_MISMATCH';Hash $api $ExpectedApiConfigSha256 'API_CONFIG_HASH_MISMATCH'
Hash $node $ExpectedNodeSha256 'NODE_HASH_MISMATCH';Hash $coreLauncher $ExpectedCoreLauncherSha256 'CORE_LAUNCHER_HASH_MISMATCH';Hash $edgeLauncher $ExpectedEdgeLauncherSha256 'EDGE_LAUNCHER_HASH_MISMATCH'
$coreSid=AssertNonAdmin $CoreServiceAccount;$edgeSid=AssertNonAdmin $EdgeServiceAccount;$backupSid=Sid $BackupAccount;if(@(@($coreSid,$edgeSid,$backupSid)|Sort-Object -Unique).Count-ne3){throw 'SERVICE_ACCOUNTS_MUST_BE_DISTINCT'}
$filesystemEvidence=File $FileSystemEvidencePath 'FILESYSTEM_EVIDENCE_NOT_FOUND';Hash $filesystemEvidence $ExpectedFileSystemEvidenceSha256 'FILESYSTEM_EVIDENCE_HASH_MISMATCH';$fs=Get-Content -Raw -LiteralPath $filesystemEvidence|ConvertFrom-Json
if($fs.result-ne'PASS'-or-not$fs.leastPrivilege-or$fs.coreServiceSid-ne$coreSid-or$fs.edgeServiceSid-ne$edgeSid-or$fs.backupSid-ne$backupSid){throw 'FILESYSTEM_EVIDENCE_REJECTED'}
$rightsEvidence=File $PrincipalRightsEvidencePath 'PRINCIPAL_RIGHTS_EVIDENCE_NOT_FOUND';Hash $rightsEvidence $ExpectedPrincipalRightsEvidenceSha256 'PRINCIPAL_RIGHTS_EVIDENCE_HASH_MISMATCH';$rights=Get-Content -Raw -LiteralPath $rightsEvidence|ConvertFrom-Json
if($rights.version-ne3-or$rights.result-ne'PASS'-or-not$rights.exactRights-or-not$rights.interactiveLogonDenied-or-not$rights.remoteInteractiveLogonDenied-or-not$rights.networkLogonDenied-or$rights.corePrincipalDigest-cne(Digest $coreSid)-or$rights.edgePrincipalDigest-cne(Digest $edgeSid)-or$rights.backupPrincipalDigest-cne(Digest $backupSid)){throw'PRINCIPAL_RIGHTS_EVIDENCE_REJECTED'}
$rightsScript=File $PrincipalRightsScriptPath 'PRINCIPAL_RIGHTS_SCRIPT_NOT_FOUND';Hash $rightsScript $ExpectedPrincipalRightsScriptSha256 'PRINCIPAL_RIGHTS_SCRIPT_HASH_MISMATCH';&$rightsScript -Action Verify -CoreServiceAccount $CoreServiceAccount -EdgeServiceAccount $EdgeServiceAccount -BackupAccount $BackupAccount 2>$null|Out-Null
$classes=$fs.classRoots;if(-not(UnderAny $root $classes.SHARED_RUNTIME)-or-not(UnderAny $release $classes.SHARED_RUNTIME)-or-not(UnderAny $node $classes.SHARED_RUNTIME)-or-not(UnderAny $releaseVerifier $classes.SHARED_RUNTIME)-or-not(UnderAny $rightsScript $classes.SHARED_RUNTIME)-or-not(UnderAny $runtime $classes.SHARED_RUNTIME)-or-not(UnderAny $api $classes.CORE_READ)-or-not(UnderAny $coreLog $classes.CORE_MODIFY)-or-not(UnderAny $edgeLog $classes.EDGE_MODIFY)-or-not(UnderAny $FileSystemEvidencePath $classes.ADMIN_EVIDENCE)-or-not(UnderAny $PrincipalRightsEvidencePath $classes.ADMIN_EVIDENCE)){throw 'FILESYSTEM_EVIDENCE_PATH_COVERAGE_FAILED'}
$runtimeValue=Get-Content -Raw -LiteralPath $runtime|ConvertFrom-Json
if([string]$runtimeValue.hostSecurity.edgeServiceSid-cne$edgeSid){throw'RUNTIME_EDGE_SERVICE_SID_MISMATCH'}
if($Action-ne'Stop'){
  Hash $releaseVerifier $ExpectedReleaseVerifierSha256 'RELEASE_VERIFIER_HASH_MISMATCH'
  if($ExpectedReleaseManifestSha256-notmatch'^[A-Fa-f0-9]{64}$'){throw'RELEASE_MANIFEST_HASH_INVALID'}
  &$node $releaseVerifier "--root=$release" "--manifest-sha256=$ExpectedReleaseManifestSha256" 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw'COMPLETE_RELEASE_VERIFICATION_FAILED'}
  $releaseManifest=Get-Content -Raw -LiteralPath (File (Join-Path $release 'release-manifest.json') 'RELEASE_MANIFEST_NOT_FOUND')|ConvertFrom-Json
  if($releaseManifest.releaseId-cne$ExpectedReleaseId-or$releaseManifest.releaseId-cne$runtimeValue.release.id-or$releaseManifest.migrationDigest-cne$runtimeValue.release.migrationDigest){throw'RELEASE_RUNTIME_IDENTITY_MISMATCH'}
}
if($runtimeValue.lan.enabled){foreach($secretPath in @($runtimeValue.tls.serverPrivateKeyPath,$runtimeValue.hostSecurity.edgeSigningPrivateKeyPath)){if(-not(UnderAny $secretPath $classes.EDGE_READ)){throw 'EDGE_PRIVATE_KEY_ACL_COVERAGE_FAILED'}}}
$expectedCore=CoreXml $node $coreLauncher $release $runtime $api $coreLog;$expectedEdge=EdgeXml $node $edgeLauncher $release $runtime $edgeLog
if($Action-in@('Start','Stop')){
  foreach($entry in @(@{Id=$ids[0];Exe=$coreExe;Xml=$coreXmlPath;Expected=$expectedCore;Account=$CoreServiceAccount},@{Id=$ids[1];Exe=$edgeExe;Xml=$edgeXmlPath;Expected=$expectedEdge;Account=$EdgeServiceAccount})){
    $svc=Get-CimInstance Win32_Service -Filter "Name='$($entry.Id)'";if(-not$svc-or-not(Test-Path -LiteralPath $entry.Exe)-or-not(Test-Path -LiteralPath $entry.Xml)-or(Get-Content -Raw -LiteralPath $entry.Xml)-cne$entry.Expected-or$svc.StartName-ine$entry.Account){throw 'SERVICE_CONFIGURATION_MISMATCH'};Hash $entry.Exe $ExpectedWrapperSha256 'INSTALLED_WRAPPER_HASH_MISMATCH'
  }
  if($Action-eq'Stop'){
    foreach($id in @($ids[1],$ids[0])){$service=Get-Service -Name $id;if($service.Status-ne'Stopped'){Stop-Service -Name $id -ErrorAction Stop;Wait-State $id 'Stopped'};Set-Service -Name $id -StartupType Manual}
    [pscustomobject]@{Result='STOPPED';CoreStopped=$true;EdgeStopped=$true;StartupType='Manual';LegacyProcessesChanged=$false}|ConvertTo-Json;exit 0
  }
  if((Get-Service -Name $ids[0]).Status-ne'Stopped'-or(Get-Service -Name $ids[1]).Status-ne'Stopped'){throw'SERVICE_START_REQUIRES_BOTH_SERVICES_STOPPED'}
  Set-Service -Name $ids[0] -StartupType Automatic;$core=Get-Service -Name $ids[0];if($core.Status-ne'Running'){Start-Service -Name $ids[0] -ErrorAction Stop;Wait-State $ids[0] 'Running'}
  if($runtimeValue.lan.enabled){Set-Service -Name $ids[1] -StartupType Automatic;$edge=Get-Service -Name $ids[1];if($edge.Status-ne'Running'){Start-Service -Name $ids[1] -ErrorAction Stop;Wait-State $ids[1] 'Running'}}else{Set-Service -Name $ids[1] -StartupType Manual;$edge=Get-Service -Name $ids[1];if($edge.Status-ne'Stopped'){Stop-Service -Name $ids[1] -ErrorAction Stop;Wait-State $ids[1] 'Stopped'}}
  [pscustomobject]@{Result='STARTED_VERIFY_REQUIRED';Mode=if($runtimeValue.lan.enabled){'FULL_LAN'}else{'CORE_ONLY_CLI_BOOTSTRAP'};CoreRunning=$true;EdgeRunning=[bool]$runtimeValue.lan.enabled;LegacyProcessesChanged=$false}|ConvertTo-Json;exit 0
}
if($Action-eq'Verify'){$edgeEnabled=[bool]$runtimeValue.lan.enabled;foreach($entry in @(@{Id=$ids[0];Exe=$coreExe;Xml=$coreXmlPath;Expected=$expectedCore;Account=$CoreServiceAccount;State='Running';Mode='Auto'},@{Id=$ids[1];Exe=$edgeExe;Xml=$edgeXmlPath;Expected=$expectedEdge;Account=$EdgeServiceAccount;State=if($edgeEnabled){'Running'}else{'Stopped'};Mode=if($edgeEnabled){'Auto'}else{'Manual'}})){$svc=Get-CimInstance Win32_Service -Filter "Name='$($entry.Id)'";if(-not$svc-or$svc.State-ne$entry.State-or-not(Test-Path -LiteralPath $entry.Exe)-or-not(Test-Path -LiteralPath $entry.Xml)){throw 'SERVICE_STATE_MISMATCH'};Hash $entry.Exe $ExpectedWrapperSha256 'INSTALLED_WRAPPER_HASH_MISMATCH';$expectedImage='"'+[IO.Path]::GetFullPath($entry.Exe)+'"';$actualSddl=(((&sc.exe sdshow $entry.Id) -join' ') -replace'^.*?(D:)','$1').Trim();$failure=(&sc.exe qfailure $entry.Id)-join' ';$sidType=(&sc.exe qsidtype $entry.Id)-join' ';if((Get-Content -Raw -LiteralPath $entry.Xml)-cne$entry.Expected-or$svc.StartName-ine$entry.Account-or$svc.StartMode-ne$entry.Mode-or[string]$svc.PathName-cne$expectedImage-or$actualSddl-cne$serviceSddl-or$failure-notmatch'10000'-or$failure-notmatch'30000'-or$sidType-notmatch'UNRESTRICTED'){throw 'SERVICE_CONFIGURATION_MISMATCH'}};[pscustomobject]@{Result='PASS';Mode=if($edgeEnabled){'FULL_LAN'}else{'CORE_ONLY_CLI_BOOTSTRAP'};CoreStatus='Running';EdgeStatus=if($edgeEnabled){'Running'}else{'Stopped'};AccountsSeparated=$true;ImagePathsPinned=$true;ServiceSidUnrestricted=$true;ServiceDaclProtected=$true;FailureActionsVerified=$true;LanOpened=$edgeEnabled}|ConvertTo-Json;exit 0}
if($ids|Where-Object{Get-Service -Name $_ -ErrorAction SilentlyContinue}){throw 'SERVICE_ALREADY_EXISTS'}
foreach($path in @($coreExe,$edgeExe,$coreXmlPath,$edgeXmlPath)){if(Test-Path -LiteralPath $path){throw 'SERVICE_FILE_ALREADY_EXISTS'}}
$staged=File $StagedWrapperPath 'STAGED_WRAPPER_NOT_FOUND';Hash $staged $ExpectedWrapperSha256 'WRAPPER_HASH_MISMATCH'
if(-not$CoreServiceCredential-or-not$EdgeServiceCredential-or$CoreServiceCredential.UserName-ine$CoreServiceAccount-or$EdgeServiceCredential.UserName-ine$EdgeServiceAccount){throw 'MATCHING_SERVICE_CREDENTIALS_REQUIRED'}
Copy-Item -LiteralPath $staged -Destination $coreExe;Copy-Item -LiteralPath $staged -Destination $edgeExe;[IO.File]::WriteAllText($coreXmlPath,$expectedCore,(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText($edgeXmlPath,$expectedEdge,(New-Object Text.UTF8Encoding($false)))
try{ConfigureService $coreExe $ids[0] $CoreServiceAccount $CoreServiceCredential 'Manual';ConfigureService $edgeExe $ids[1] $EdgeServiceAccount $EdgeServiceCredential 'Manual'}catch{foreach($exe in @($coreExe,$edgeExe)){if(Test-Path -LiteralPath $exe){&$exe uninstall|Out-Null}};foreach($file in @($coreExe,$edgeExe,$coreXmlPath,$edgeXmlPath)){if(Test-Path -LiteralPath $file){Remove-Item -LiteralPath $file -Force}};throw}
[pscustomobject]@{Result='INSTALLED_STOPPED';Services=$ids;AccountsSeparated=$true;PrincipalRightsVerified=$true;LanOpened=$false;LegacyProcessesChanged=$false}|ConvertTo-Json
