#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Apply','Verify','Rollback')][string]$Action='Plan',
  [string]$LegacyBaselineEvidencePath,[string]$ExpectedLegacyBaselineEvidenceSha256,
  [string]$RestartSpecPath,[string]$ExpectedRestartSpecSha256,
  [string]$NodePath,[string]$ExpectedNodeSha256,
  [string]$AttestationSignerPath,[string]$ExpectedAttestationSignerSha256,[string]$QuiescePrivateKeyPath,[string]$ExpectedQuiescePrivateKeySha256,
  [string]$AttestationVerifierPath,[string]$ExpectedAttestationVerifierSha256,[string]$QuiescePublicKeyPath,[string]$ExpectedQuiescePublicKeySha256,
  [string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,
  [string]$EvidenceOutputPath,[string]$ExpectedEvidenceSha256,
  [string]$MigrationJournalPath,[string]$ExpectedMigrationJournalSha256,[string]$DatabaseRollbackEvidencePath,[string]$ExpectedDatabaseRollbackEvidenceSha256,
  [int]$ExpectedWebProcessId,[int]$ExpectedApiProcessId,[string]$ExpectedWebProcessStartedAt,[string]$ExpectedApiProcessStartedAt,
  [ValidateSet('Apply','Rollback')][string]$PlannedAction,[string]$ApprovedPlanSha256,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
function Existing([string]$Path,[bool]$Directory,[string]$Code){$kind=if($Directory){'Container'}else{'Leaf'};if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType $kind)){throw$Code};$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');$cursor=Get-Item -LiteralPath $full -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw'LEGACY_QUIESCE_REPARSE_REJECTED'};$cursor=$cursor.Parent};return$full}
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function TextHash([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function Under([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');return@($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function ExactKeys($Value,[string[]]$Keys,[string]$Code){$actual=@($Value.PSObject.Properties.Name|Sort-Object);$expected=@($Keys|Sort-Object);if(($actual-join"`n")-cne($expected-join"`n")){throw$Code}}
function InventoryDigest([string]$Root){$rootFull=Existing $Root $true 'LEGACY_STORAGE_ROOT_NOT_FOUND';$prefix=$rootFull+'\';$lines=New-Object 'System.Collections.Generic.List[string]';foreach($file in @(Get-ChildItem -LiteralPath $rootFull -File -Recurse -Force|Sort-Object FullName)){$relative=$file.FullName.Substring($prefix.Length).Replace('\','/');$lines.Add("$relative|$($file.Length)|$(Hash $file.FullName)")};return TextHash ($lines-join"`n")}
function ProcessDigest($Web,$Api){return TextHash (@("3100|$($Web.Id)|$($Web.StartTime.ToUniversalTime().ToString('o'))|$(Hash $Web.Path)","4100|$($Api.Id)|$($Api.StartTime.ToUniversalTime().ToString('o'))|$(Hash $Api.Path)")-join"`n")}
function ExactProcess([int]$Id,[string]$StartedAt){$process=Get-Process -Id $Id -ErrorAction Stop;if((Hash $process.Path)-cne$ExpectedNodeSha256.ToLowerInvariant()-or$process.StartTime.ToUniversalTime()-ne[datetime]::Parse($StartedAt).ToUniversalTime()){throw'LEGACY_PROCESS_IDENTITY_CHANGED'};return$process}
function PortAbsent([int]$Port){return@((Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue)).Count-eq0}
function VerifySigned([string]$Path,[string]$Type,[string]$Code){&$node $verifier $public $Path $Type 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw$Code}}
function WaitListener([int]$Port,[int]$ProcessId){$deadline=(Get-Date).AddSeconds(90);do{$listener=@(Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue);if($listener.Count-eq1-and$listener[0].LocalAddress-in@('127.0.0.1','::1')-and$listener[0].OwningProcess-eq$ProcessId){return};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw'LEGACY_RESTART_LISTENER_FAILED'}
function CommandLineHash([int]$ProcessId){$cim=Get-CimInstance Win32_Process -Filter "ProcessId=$ProcessId" -ErrorAction Stop;if(-not$cim-or-not$cim.CommandLine-or$cim.CommandLine.Length-gt32767-or$cim.CommandLine-match'[\x00\r\n]'){throw'LEGACY_COMMAND_LINE_PROBE_INVALID'};return TextHash ([string]$cim.CommandLine).Trim()}
function HealthDigest([int]$Port,[string]$Path){if($Path-notmatch'^/[A-Za-z0-9/_-]{1,255}$'){throw'LEGACY_HEALTH_PATH_INVALID'};try{$request=[Net.HttpWebRequest]::Create("http://127.0.0.1:$Port$Path");$request.Proxy=$null;$request.Timeout=5000;$response=$request.GetResponse();try{$reader=[IO.StreamReader]::new($response.GetResponseStream());$body=$reader.ReadToEnd();if([int]$response.StatusCode-ne200-or$body.Length-gt4096){throw'LEGACY_HEALTH_SMOKE_FAILED'};$value=$body|ConvertFrom-Json;if($value.status-cne'live'){throw'LEGACY_HEALTH_SMOKE_FAILED'};return TextHash (@('live',[string]$value.releaseId)-join'|')}finally{$response.Dispose()}}catch{throw'LEGACY_HEALTH_SMOKE_FAILED'}}
function New-LegacyQuiesceApprovalPlan([string]$IntendedAction){
  if($IntendedAction-notin@('Apply','Rollback')){throw'PLANNED_ACTION_REQUIRED'}
  if($ExpectedWebProcessId-lt1-or$ExpectedApiProcessId-lt1-or$ExpectedWebProcessId-eq$ExpectedApiProcessId){throw'LEGACY_QUIESCE_PLAN_PID_INVALID'}
  foreach($value in @($ExpectedWebProcessStartedAt,$ExpectedApiProcessStartedAt)){try{[datetime]::Parse($value).ToUniversalTime()|Out-Null}catch{throw'LEGACY_QUIESCE_PLAN_START_TIME_INVALID'}}
  Assert-ApprovalOptionalArtifact $DatabaseRollbackEvidencePath $ExpectedDatabaseRollbackEvidenceSha256 'LEGACY_QUIESCE_PLAN_DATABASE_ROLLBACK_PAIR_REQUIRED'
  $parameters=[ordered]@{legacyBaselineEvidencePath=(Get-ApprovalPath $LegacyBaselineEvidencePath 'LEGACY_QUIESCE_PLAN_BASELINE_PATH_REQUIRED');legacyBaselineEvidenceSha256=(Get-ApprovalHash $ExpectedLegacyBaselineEvidenceSha256 'LEGACY_QUIESCE_PLAN_BASELINE_HASH_REQUIRED');restartSpecPath=(Get-ApprovalPath $RestartSpecPath 'LEGACY_QUIESCE_PLAN_RESTART_SPEC_PATH_REQUIRED');restartSpecSha256=(Get-ApprovalHash $ExpectedRestartSpecSha256 'LEGACY_QUIESCE_PLAN_RESTART_SPEC_HASH_REQUIRED');nodePath=(Get-ApprovalPath $NodePath 'LEGACY_QUIESCE_PLAN_NODE_PATH_REQUIRED');nodeSha256=(Get-ApprovalHash $ExpectedNodeSha256 'LEGACY_QUIESCE_PLAN_NODE_HASH_REQUIRED');attestationSignerPath=(Get-ApprovalPath $AttestationSignerPath 'LEGACY_QUIESCE_PLAN_SIGNER_PATH_REQUIRED');attestationSignerSha256=(Get-ApprovalHash $ExpectedAttestationSignerSha256 'LEGACY_QUIESCE_PLAN_SIGNER_HASH_REQUIRED');quiescePrivateKeyPath=(Get-ApprovalPath $QuiescePrivateKeyPath 'LEGACY_QUIESCE_PLAN_PRIVATE_KEY_PATH_REQUIRED');quiescePrivateKeySha256=(Get-ApprovalHash $ExpectedQuiescePrivateKeySha256 'LEGACY_QUIESCE_PLAN_PRIVATE_KEY_HASH_REQUIRED');attestationVerifierPath=(Get-ApprovalPath $AttestationVerifierPath 'LEGACY_QUIESCE_PLAN_VERIFIER_PATH_REQUIRED');attestationVerifierSha256=(Get-ApprovalHash $ExpectedAttestationVerifierSha256 'LEGACY_QUIESCE_PLAN_VERIFIER_HASH_REQUIRED');quiescePublicKeyPath=(Get-ApprovalPath $QuiescePublicKeyPath 'LEGACY_QUIESCE_PLAN_PUBLIC_KEY_PATH_REQUIRED');quiescePublicKeySha256=(Get-ApprovalHash $ExpectedQuiescePublicKeySha256 'LEGACY_QUIESCE_PLAN_PUBLIC_KEY_HASH_REQUIRED');filesystemEvidencePath=(Get-ApprovalPath $FileSystemEvidencePath 'LEGACY_QUIESCE_PLAN_FILESYSTEM_PATH_REQUIRED');filesystemEvidenceSha256=(Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'LEGACY_QUIESCE_PLAN_FILESYSTEM_HASH_REQUIRED');evidenceOutputPath=(Get-ApprovalPath $EvidenceOutputPath 'LEGACY_QUIESCE_PLAN_EVIDENCE_PATH_REQUIRED');webProcessId=$ExpectedWebProcessId;apiProcessId=$ExpectedApiProcessId;webProcessStartedAt=([datetime]::Parse($ExpectedWebProcessStartedAt).ToUniversalTime().ToString('o'));apiProcessStartedAt=([datetime]::Parse($ExpectedApiProcessStartedAt).ToUniversalTime().ToString('o'));ports=@(3100,4100)}
  if($IntendedAction-eq'Rollback'){$parameters.quiesceEvidenceSha256=Get-ApprovalHash $ExpectedEvidenceSha256 'LEGACY_QUIESCE_PLAN_EVIDENCE_HASH_REQUIRED';$parameters.migrationJournalPath=Get-ApprovalPath $MigrationJournalPath 'LEGACY_QUIESCE_PLAN_MIGRATION_JOURNAL_PATH_REQUIRED';$parameters.migrationJournalSha256=Get-ApprovalOptionalHash $ExpectedMigrationJournalSha256;$parameters.databaseRollbackEvidencePath=Get-ApprovalOptionalPath $DatabaseRollbackEvidencePath;$parameters.databaseRollbackEvidenceSha256=Get-ApprovalOptionalHash $ExpectedDatabaseRollbackEvidenceSha256}
  $target="Exact legacy writer PID $ExpectedWebProcessId/$ExpectedApiProcessId on loopback 3100/4100, baseline $($parameters.legacyBaselineEvidenceSha256)"
  $impact=if($IntendedAction-eq'Apply'){'Stops only the exact baseline-bound writer pair, proves both PIDs/listeners absent, and writes signed quiesce evidence'}else{'After any required signed database rollback, starts only the hash-pinned legacy commands and verifies exact loopback listener ownership'}
  $rollback=if($IntendedAction-eq'Apply'){'Before migration, use a separately approved Rollback plan; after migration, also require signed production DB rollback evidence'}else{'Quiesce again only through a new approved Apply plan'}
  return New-ApprovalPlan $PSCommandPath $IntendedAction $parameters $target $impact $rollback
}

if($Action-eq'Plan'){New-LegacyQuiesceApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0}
$legacyQuiesceMutation=if($Action-in@('Apply','Rollback')){$Action}else{$null};if($legacyQuiesceMutation){Assert-ApprovedPlan (New-LegacyQuiesceApprovalPlan $legacyQuiesceMutation) ([bool]$Approved) $ApprovedPlanSha256}

$baselinePath=Existing $LegacyBaselineEvidencePath $false 'LEGACY_BASELINE_NOT_FOUND';$restartSpec=Existing $RestartSpecPath $false 'RESTART_SPEC_NOT_FOUND';$node=Existing $NodePath $false 'NODE_NOT_FOUND';$signer=Existing $AttestationSignerPath $false 'ATTESTATION_SIGNER_NOT_FOUND';$private=Existing $QuiescePrivateKeyPath $false 'QUIESCE_PRIVATE_KEY_NOT_FOUND';$verifier=Existing $AttestationVerifierPath $false 'ATTESTATION_VERIFIER_NOT_FOUND';$public=Existing $QuiescePublicKeyPath $false 'QUIESCE_PUBLIC_KEY_NOT_FOUND';$fsPath=Existing $FileSystemEvidencePath $false 'FILESYSTEM_EVIDENCE_NOT_FOUND'
foreach($entry in @(@{Path=$baselinePath;Expected=$ExpectedLegacyBaselineEvidenceSha256;Code='LEGACY_BASELINE_HASH_MISMATCH'},@{Path=$restartSpec;Expected=$ExpectedRestartSpecSha256;Code='RESTART_SPEC_HASH_MISMATCH'},@{Path=$node;Expected=$ExpectedNodeSha256;Code='NODE_HASH_MISMATCH'},@{Path=$signer;Expected=$ExpectedAttestationSignerSha256;Code='ATTESTATION_SIGNER_HASH_MISMATCH'},@{Path=$verifier;Expected=$ExpectedAttestationVerifierSha256;Code='ATTESTATION_VERIFIER_HASH_MISMATCH'},@{Path=$fsPath;Expected=$ExpectedFileSystemEvidenceSha256;Code='FILESYSTEM_EVIDENCE_HASH_MISMATCH'})){if($entry.Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $entry.Path)-cne$entry.Expected.ToLowerInvariant()){throw$entry.Code}}
foreach($entry in @(@{Path=$private;Expected=$ExpectedQuiescePrivateKeySha256;Code='QUIESCE_PRIVATE_KEY_HASH_MISMATCH'},@{Path=$public;Expected=$ExpectedQuiescePublicKeySha256;Code='QUIESCE_PUBLIC_KEY_HASH_MISMATCH'})){if($entry.Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $entry.Path)-cne$entry.Expected.ToLowerInvariant()){throw$entry.Code}}
$baseline=Get-Content -Raw -LiteralPath $baselinePath|ConvertFrom-Json;if($baseline.version-ne3-or$baseline.result-cne'PASS'-or$baseline.proofType-cne'legacy-running-baseline'-or$baseline.legacyStorageProvider-cne'repository_local_ntfs'-or$baseline.nodeExecutableSha256-cne$ExpectedNodeSha256.ToLowerInvariant()-or$baseline.restartSpecSha256-cne$ExpectedRestartSpecSha256.ToLowerInvariant()-or-not$baseline.launchIdentityMatchesProtectedRestartSpec-or-not$baseline.legacyIdentityHealthSmokeVerified-or$baseline.restartCanonicalDigest-notmatch'^[0-9a-f]{64}$'-or$baseline.webCommandLineSha256-notmatch'^[0-9a-f]{64}$'-or$baseline.apiCommandLineSha256-notmatch'^[0-9a-f]{64}$'){throw'LEGACY_BASELINE_INVALID'}
if([int]$baseline.webProcessId-ne$ExpectedWebProcessId-or[int]$baseline.apiProcessId-ne$ExpectedApiProcessId-or[datetime]::Parse([string]$baseline.webProcessStartedAt).ToUniversalTime()-ne[datetime]::Parse($ExpectedWebProcessStartedAt).ToUniversalTime()-or[datetime]::Parse([string]$baseline.apiProcessStartedAt).ToUniversalTime()-ne[datetime]::Parse($ExpectedApiProcessStartedAt).ToUniversalTime()){throw'LEGACY_BASELINE_PLAN_IDENTITY_MISMATCH'}
$spec=Get-Content -Raw -LiteralPath $restartSpec|ConvertFrom-Json;ExactKeys $spec @('version','sourceRoot','web','api') 'RESTART_SPEC_KEYS_INVALID';foreach($name in @('web','api')){ExactKeys $spec.$name @('filePath','workingDirectory','arguments') 'RESTART_PROCESS_SPEC_KEYS_INVALID';if([IO.Path]::GetFullPath([string]$spec.$name.filePath)-ine$node-or-not(Under ([string]$spec.$name.workingDirectory) @([string]$baseline.legacySourceRoot))){throw'RESTART_PROCESS_SPEC_INVALID'}}
$fs=Get-Content -Raw -LiteralPath $fsPath|ConvertFrom-Json;if($fs.result-ne'PASS'-or-not$fs.exactAcl-or-not(Under $node $fs.classRoots.SHARED_RUNTIME)-or-not(Under $signer $fs.classRoots.SHARED_RUNTIME)-or-not(Under $verifier $fs.classRoots.SHARED_RUNTIME)-or-not(Under $public $fs.classRoots.SHARED_RUNTIME)-or-not(Under $private $fs.classRoots.ADMIN_ONLY)-or-not(Under $restartSpec $fs.classRoots.ADMIN_ONLY)-or-not(Under $baselinePath $fs.classRoots.ADMIN_EVIDENCE)-or-not(Under $EvidenceOutputPath $fs.classRoots.ADMIN_EVIDENCE)){throw'LEGACY_QUIESCE_FILESYSTEM_BOUNDARY_REJECTED'}
if((InventoryDigest ([string]$baseline.legacyUploadsRoot))-cne$baseline.uploadsInventoryDigest-or(InventoryDigest ([string]$baseline.legacyReportsRoot))-cne$baseline.reportsInventoryDigest){throw'LEGACY_STORAGE_CHANGED_SINCE_BASELINE'}

if($Action-eq'Apply'){
  if(Test-Path -LiteralPath $EvidenceOutputPath){throw'LEGACY_QUIESCE_EVIDENCE_ALREADY_EXISTS'};$web=ExactProcess ([int]$baseline.webProcessId) ([string]$baseline.webProcessStartedAt);$api=ExactProcess ([int]$baseline.apiProcessId) ([string]$baseline.apiProcessStartedAt);if((CommandLineHash $web.Id)-cne$baseline.webObservedCommandLineSha256-or(CommandLineHash $api.Id)-cne$baseline.apiObservedCommandLineSha256-or(HealthDigest 3100 ([string]$baseline.webHealthPath))-cne$baseline.webHealthDigest-or(HealthDigest 4100 ([string]$baseline.apiHealthPath))-cne$baseline.apiHealthDigest){throw'LEGACY_LAUNCH_OR_HEALTH_IDENTITY_CHANGED'}
  Stop-Process -Id $web.Id -Force;Stop-Process -Id $api.Id -Force;Wait-Process -Id $web.Id,$api.Id -Timeout 60 -ErrorAction SilentlyContinue;if((Get-Process -Id $web.Id,$api.Id -ErrorAction SilentlyContinue)-or-not(PortAbsent 3100)-or-not(PortAbsent 4100)){throw'LEGACY_QUIESCE_FAILED'}
  $parent=Split-Path -Parent ([IO.Path]::GetFullPath($EvidenceOutputPath));$unsigned=Join-Path $parent ('.legacy-quiesce-'+[Guid]::NewGuid().ToString('N')+'.unsigned');$pending="$unsigned.signed"
  try{[IO.File]::WriteAllText($unsigned,([ordered]@{attestationType='legacy-quiesce';version=2;result='PASS';baselineSha256=(Hash $baselinePath);releaseId=$baseline.releaseId;migrationDigest=$baseline.migrationDigest;processIdentityDigest=$baseline.processIdentityDigest;restartCanonicalDigest=$baseline.restartCanonicalDigest;webLaunchCanonicalDigest=$baseline.webLaunchCanonicalDigest;apiLaunchCanonicalDigest=$baseline.apiLaunchCanonicalDigest;legacyIdentityHealthSmokeVerifiedBeforeStop=$true;webProcessId=$baseline.webProcessId;apiProcessId=$baseline.apiProcessId;ports=@(3100,4100);processesStopped=$true;listenersAbsent=$true;storageInventoryDigest=$baseline.storageInventoryDigest;databaseMutated=$false;restartSpecSha256=(Hash $restartSpec);completedAt=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json),(New-Object Text.UTF8Encoding($false)));&$node $signer $private $unsigned $pending;if($LASTEXITCODE-ne0-or-not(Test-Path -LiteralPath $pending -PathType Leaf)){throw'LEGACY_QUIESCE_SIGNING_FAILED'};Move-Item -LiteralPath $pending -Destination $EvidenceOutputPath;[pscustomobject]@{Result='QUIESCED';PortsAbsent=$true;LaunchIdentityBound=$true;DatabaseChanged=$false;EvidenceSha256=(Hash $EvidenceOutputPath)}|ConvertTo-Json}finally{Remove-Item -LiteralPath $unsigned,$pending -Force -ErrorAction SilentlyContinue};exit 0
}
$evidence=Existing $EvidenceOutputPath $false 'LEGACY_QUIESCE_EVIDENCE_NOT_FOUND';if($ExpectedEvidenceSha256-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $evidence)-cne$ExpectedEvidenceSha256.ToLowerInvariant()){throw'LEGACY_QUIESCE_EVIDENCE_HASH_MISMATCH'};VerifySigned $evidence 'legacy-quiesce' 'LEGACY_QUIESCE_SIGNATURE_REJECTED';$value=Get-Content -Raw -LiteralPath $evidence|ConvertFrom-Json;if($value.version-ne2-or$value.result-cne'PASS'-or$value.baselineSha256-cne(Hash $baselinePath)-or$value.processIdentityDigest-cne$baseline.processIdentityDigest-or$value.restartCanonicalDigest-cne$baseline.restartCanonicalDigest-or$value.webLaunchCanonicalDigest-cne$baseline.webLaunchCanonicalDigest-or$value.apiLaunchCanonicalDigest-cne$baseline.apiLaunchCanonicalDigest-or-not$value.legacyIdentityHealthSmokeVerifiedBeforeStop-or-not$value.processesStopped-or-not$value.listenersAbsent-or$value.databaseMutated-or$value.restartSpecSha256-cne(Hash $restartSpec)){throw'LEGACY_QUIESCE_EVIDENCE_INVALID'}
if($Action-eq'Verify'){if((Get-Process -Id ([int]$baseline.webProcessId),([int]$baseline.apiProcessId) -ErrorAction SilentlyContinue)-or-not(PortAbsent 3100)-or-not(PortAbsent 4100)){throw'LEGACY_QUIESCE_STATE_CHANGED'};[pscustomobject]@{Result='PASS';SignedEvidence=$true;ProcessesAbsent=$true;ListenersAbsent=$true}|ConvertTo-Json;exit 0}
if(-not(PortAbsent 3100)-or-not(PortAbsent 4100)){throw'LEGACY_RESTART_PORT_IN_USE'}
if(Test-Path -LiteralPath $MigrationJournalPath -PathType Leaf){if($ExpectedMigrationJournalSha256-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $MigrationJournalPath)-cne$ExpectedMigrationJournalSha256.ToLowerInvariant()){throw'MIGRATION_JOURNAL_HASH_MISMATCH'};$rollback=Existing $DatabaseRollbackEvidencePath $false 'DATABASE_ROLLBACK_EVIDENCE_REQUIRED';if($ExpectedDatabaseRollbackEvidenceSha256-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $rollback)-cne$ExpectedDatabaseRollbackEvidenceSha256.ToLowerInvariant()){throw'DATABASE_ROLLBACK_EVIDENCE_HASH_MISMATCH'};VerifySigned $rollback 'legacy-database-rollback' 'DATABASE_ROLLBACK_SIGNATURE_REJECTED';$rollbackValue=Get-Content -Raw -LiteralPath $rollback|ConvertFrom-Json;if($rollbackValue.version-ne1-or$rollbackValue.result-cne'PASS'-or$rollbackValue.baselineSha256-cne(Hash $baselinePath)-or$rollbackValue.migrationDigest-cne$baseline.migrationDigest-or-not$rollbackValue.productionDatabaseRestored){throw'DATABASE_ROLLBACK_EVIDENCE_INVALID'}}
$started=@();try{$api=Start-Process -FilePath $node -WorkingDirectory ([string]$spec.api.workingDirectory) -ArgumentList @($spec.api.arguments) -PassThru;$started+=$api;$web=Start-Process -FilePath $node -WorkingDirectory ([string]$spec.web.workingDirectory) -ArgumentList @($spec.web.arguments) -PassThru;$started+=$web;WaitListener 4100 $api.Id;WaitListener 3100 $web.Id;if((CommandLineHash $web.Id)-cne$baseline.webObservedCommandLineSha256-or(CommandLineHash $api.Id)-cne$baseline.apiObservedCommandLineSha256-or(TextHash ([IO.Path]::GetFullPath([string]$spec.web.workingDirectory).TrimEnd('\').ToLowerInvariant()))-cne$baseline.webWorkingDirectorySha256-or(TextHash ([IO.Path]::GetFullPath([string]$spec.api.workingDirectory).TrimEnd('\').ToLowerInvariant()))-cne$baseline.apiWorkingDirectorySha256){throw'LEGACY_RESTART_LAUNCH_IDENTITY_FAILED'};if((HealthDigest 3100 ([string]$baseline.webHealthPath))-cne$baseline.webHealthDigest-or(HealthDigest 4100 ([string]$baseline.apiHealthPath))-cne$baseline.apiHealthDigest){throw'LEGACY_RESTART_BUSINESS_HEALTH_FAILED'};[pscustomobject]@{Result='ROLLED_BACK';LegacyRestarted=$true;LegacyLaunchIdentityVerified=$true;LegacyBusinessHealthSmokeVerified=$true;DatabaseRollbackRequired=[bool]($MigrationJournalPath-and(Test-Path -LiteralPath $MigrationJournalPath));WebProcessId=$web.Id;ApiProcessId=$api.Id}|ConvertTo-Json}catch{foreach($process in $started){if(-not$process.HasExited){Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue}};throw}
