#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Create','VerifyExtract','Remove')][string]$Action='Plan',
  [string]$NodePath,[string]$ExpectedNodeSha256,[string]$ToolPath,[string]$ExpectedToolSha256,
  [string]$ManifestPath,[string]$ExpectedManifestSha256,[string]$WorksheetPath,[string]$ExpectedWorksheetSha256,
  [string]$KitPath,[string]$ExpectedKitSha256,[string]$AdminOnlyRoot,[string]$EscrowKitPath,[string]$EscrowWorksheetPath,[string]$ExpectedEscrowWorksheetSha256,[string]$EscrowRoot,
  [string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,[string]$ExpectedInstallId,[string]$ExpectedInventoryDigest,
  [string]$CaCertificatePath,[string]$ExpectedCaCertificateSha256,[string]$DisasterScratchPath,[switch]$DisasterRecovery,
  [Security.SecureString]$KitPassphrase,[string]$EvidenceOutputPath,[string]$ExpectedEvidenceSha256,
  [string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,
  [ValidateSet('Create','VerifyExtract','Remove')][string]$PlannedAction,[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
$systemSid='S-1-5-18';$administratorsSid='S-1-5-32-544';$full=[Security.AccessControl.FileSystemRights]::FullControl
function NoReparseAncestors([string]$Path){$cursor=[IO.Path]::GetFullPath($Path);while($cursor){if(Test-Path -LiteralPath $cursor){$item=Get-Item -LiteralPath $cursor -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'RECOVERY_PATH_REPARSE_REJECTED'}};$parent=Split-Path -Parent $cursor;if(-not$parent-or$parent-eq$cursor){break};$cursor=$parent}}
function Under([string]$Path,[string[]]$Roots){$fullPath=[IO.Path]::GetFullPath($Path);return @($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$fullPath-ieq$root-or$fullPath.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function ExactKeys($Value,[string[]]$Keys,[string]$Code){if((@($Value.PSObject.Properties.Name|Sort-Object)-join'|')-cne(@($Keys|Sort-Object)-join'|')){throw $Code}}
function ShaText([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function FileHash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function AssertPinned([string]$Path,[string]$Expected,[string]$Code){NoReparseAncestors $Path;if(-not(Test-Path -LiteralPath $Path -PathType Leaf)-or$Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(FileHash $Path)-cne$Expected.ToLowerInvariant()){throw $Code}}
function AssertAdminOnly([string]$Path,[switch]$Directory){NoReparseAncestors $Path;if(-not(Test-Path -LiteralPath $Path)){throw 'ADMIN_ONLY_PATH_NOT_FOUND'};if($Directory-and-not(Test-Path -LiteralPath $Path -PathType Container)){throw 'ADMIN_ONLY_DIRECTORY_REQUIRED'};$acl=Get-Acl -LiteralPath $Path;if(-not$acl.AreAccessRulesProtected-or$acl.Owner.Translate([Security.Principal.SecurityIdentifier]).Value-notin@($systemSid,$administratorsSid)-or@($acl.Access).Count-ne2){throw 'ADMIN_ONLY_ACL_INVALID'};foreach($rule in $acl.Access){$sid=$rule.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value;if($sid-notin@($systemSid,$administratorsSid)-or$rule.AccessControlType-ne'Allow'-or$rule.FileSystemRights-ne$full-or$rule.IsInherited){throw 'ADMIN_ONLY_ACL_INVALID'}}}
function Protect([string]$Path,[switch]$Directory){$security=if($Directory){New-Object Security.AccessControl.DirectorySecurity}else{New-Object Security.AccessControl.FileSecurity};$security.SetOwner((New-Object Security.Principal.SecurityIdentifier($administratorsSid)));$security.SetAccessRuleProtection($true,$false);$inherit=if($Directory){[Security.AccessControl.InheritanceFlags]'ContainerInherit,ObjectInherit'}else{[Security.AccessControl.InheritanceFlags]::None};foreach($sid in @($systemSid,$administratorsSid)){$rule=New-Object Security.AccessControl.FileSystemAccessRule((New-Object Security.Principal.SecurityIdentifier($sid)),$full,$inherit,[Security.AccessControl.PropagationFlags]::None,[Security.AccessControl.AccessControlType]::Allow);$security.AddAccessRule($rule)|Out-Null};Set-Acl -LiteralPath $Path -AclObject $security;AssertAdminOnly $Path -Directory:$Directory}
function AssertEscrowSeparated([string]$SourceRoot,[string]$TargetRoot){$source=[IO.Path]::GetFullPath($SourceRoot);if($TargetRoot.StartsWith('\\')){return};$target=[IO.Path]::GetFullPath($TargetRoot);$sourceVolume=Get-Volume -FilePath $source;$targetVolume=Get-Volume -FilePath $target;if(-not$sourceVolume.UniqueId-or-not$targetVolume.UniqueId-or$sourceVolume.UniqueId-eq$targetVolume.UniqueId){throw 'RECOVERY_ESCROW_MUST_USE_SEPARATE_VOLUME'}}
function Stop-RecoveryProcessTree([Diagnostics.Process]$Process){if($null-eq$Process){return};try{if(-not$Process.HasExited){$Process.Kill($true)}}catch{try{if(-not$Process.HasExited){$Process.Kill()}}catch{}}}
function InvokeKit([string[]]$Arguments){
  if(-not$KitPassphrase){throw 'RECOVERY_KIT_PASSPHRASE_REQUIRED'};AssertPinned $NodePath $ExpectedNodeSha256 'RECOVERY_NODE_HASH_MISMATCH';AssertPinned $ToolPath $ExpectedToolSha256 'RECOVERY_TOOL_HASH_MISMATCH'
  $pointer=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($KitPassphrase);$plain=$null;$process=$null;$stdout=[IO.MemoryStream]::new();$stderr=[IO.MemoryStream]::new();$stdoutBuffer=New-Object byte[] 4096;$stderrBuffer=New-Object byte[] 4096;$maximumOutputBytes=65536;$watch=[Diagnostics.Stopwatch]::StartNew()
  try{
    $plain=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer);$info=[Diagnostics.ProcessStartInfo]::new();$info.FileName=[IO.Path]::GetFullPath($NodePath);$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardInput=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true
    foreach($argument in @([IO.Path]::GetFullPath($ToolPath))+$Arguments){$info.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::Start($info);if(-not$process){throw 'RECOVERY_KIT_TOOL_START_FAILED'};$process.StandardInput.Write($plain);$process.StandardInput.Close();$plain=$null
    $stdoutTask=$process.StandardOutput.BaseStream.ReadAsync($stdoutBuffer,0,$stdoutBuffer.Length);$stderrTask=$process.StandardError.BaseStream.ReadAsync($stderrBuffer,0,$stderrBuffer.Length);$stdoutDone=$false;$stderrDone=$false
    while(-not($process.HasExited-and$stdoutDone-and$stderrDone)){
      if($watch.ElapsedMilliseconds-ge120000){Stop-RecoveryProcessTree $process;throw 'RECOVERY_KIT_TOOL_TIMEOUT'}
      if(-not$stdoutDone-and$stdoutTask.IsCompleted){$count=$stdoutTask.GetAwaiter().GetResult();if($count-eq0){$stdoutDone=$true}else{if($stdout.Length+$stderr.Length+$count-gt$maximumOutputBytes){Stop-RecoveryProcessTree $process;throw 'RECOVERY_KIT_TOOL_OUTPUT_LIMIT'};$stdout.Write($stdoutBuffer,0,$count);$stdoutTask=$process.StandardOutput.BaseStream.ReadAsync($stdoutBuffer,0,$stdoutBuffer.Length)}}
      if(-not$stderrDone-and$stderrTask.IsCompleted){$count=$stderrTask.GetAwaiter().GetResult();if($count-eq0){$stderrDone=$true}else{if($stdout.Length+$stderr.Length+$count-gt$maximumOutputBytes){Stop-RecoveryProcessTree $process;throw 'RECOVERY_KIT_TOOL_OUTPUT_LIMIT'};$stderr.Write($stderrBuffer,0,$count);$stderrTask=$process.StandardError.BaseStream.ReadAsync($stderrBuffer,0,$stderrBuffer.Length)}}
      if(-not($process.HasExited-and$stdoutDone-and$stderrDone)){[Threading.Thread]::Sleep(10)}
    }
    if($process.ExitCode-ne0){throw 'RECOVERY_KIT_TOOL_FAILED'};return([Text.Encoding]::UTF8.GetString($stdout.ToArray()).Trim()|ConvertFrom-Json)
  }finally{Stop-RecoveryProcessTree $process;if($process){$process.Dispose()};$stdout.Dispose();$stderr.Dispose();$watch.Stop();if($pointer-ne[IntPtr]::Zero){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)};$plain=$null}
}
function Get-InventoryDigest($Files){return ShaText ((@($Files|Sort-Object purpose|ForEach-Object{"$($_.purpose)`0$($_.name)`0$($_.sha256)"}))-join"`n")}
function ValidateCurrentManifest($Manifest,$Fs){
  ExactKeys $Manifest @('version','installId','runtimeConfigSha256','files') 'RECOVERY_MANIFEST_KEYS_INVALID';if($Manifest.version-ne2-or$Manifest.installId-cne$ExpectedInstallId-or$ExpectedInstallId-notmatch'^[a-z0-9][a-z0-9-]{7,63}$'-or$Manifest.runtimeConfigSha256-cne$ExpectedRuntimeConfigSha256.ToLowerInvariant()-or(FileHash $RuntimeConfigPath)-cne$Manifest.runtimeConfigSha256){throw 'RECOVERY_MANIFEST_BINDING_INVALID'}
  $classes=@{'api-config'='CORE_READ';'runtime-config'='SHARED_RUNTIME';'edge-signing-private-key'='EDGE_READ';'backup-receipt-private-key'='SIGNER_ONLY';'restore-receipt-private-key'='ADMIN_ONLY';'backup-integrity-key'='BACKUP_ONLY';'offline-ca-pfx'='ADMIN_ONLY';'offline-ca-pfx-password'='ADMIN_ONLY';'postgres-admin-pgpass'='ADMIN_ONLY';'postgres-migration-pgpass'='ADMIN_ONLY';'postgres-backup-pgpass'='BACKUP_ONLY';'postgres-restore-pgpass'='ADMIN_ONLY';'postgres-runtime-pgpass'='CORE_READ'}
  if(@($Manifest.files).Count-ne$classes.Count){throw 'RECOVERY_MANIFEST_INVENTORY_INVALID'};$purposes=[Collections.Generic.HashSet[string]]::new();$names=[Collections.Generic.HashSet[string]]::new();foreach($entry in $Manifest.files){ExactKeys $entry @('purpose','name','path','sha256') 'RECOVERY_MANIFEST_ENTRY_KEYS_INVALID';if(-not$classes.ContainsKey([string]$entry.purpose)-or-not$purposes.Add([string]$entry.purpose)-or-not$names.Add([string]$entry.name)-or$entry.name-notmatch'^[-a-z0-9_.]{1,80}$'-or$entry.sha256-notmatch'^[a-f0-9]{64}$'-or-not(Test-Path -LiteralPath $entry.path -PathType Leaf)){throw 'RECOVERY_MANIFEST_INVENTORY_INVALID'};NoReparseAncestors $entry.path;$roots=$Fs.classRoots.($classes[[string]$entry.purpose]);if(-not(Under $entry.path $roots)-or(FileHash $entry.path)-cne$entry.sha256){throw 'RECOVERY_MANIFEST_SOURCE_REJECTED'}};return Get-InventoryDigest $Manifest.files
}
function ReadWorksheet([string]$Path,[string]$ExpectedHash){AssertPinned $Path $ExpectedHash 'RECOVERY_WORKSHEET_HASH_MISMATCH';$worksheet=Get-Content -Raw -LiteralPath $Path|ConvertFrom-Json;ExactKeys $worksheet @('version','kitSha256','manifestSha256','runtimeConfigSha256','installId','inventoryDigest') 'RECOVERY_WORKSHEET_KEYS_INVALID';if($worksheet.version-ne1-or$worksheet.kitSha256-notmatch'^[a-f0-9]{64}$'-or$worksheet.manifestSha256-notmatch'^[a-f0-9]{64}$'-or$worksheet.runtimeConfigSha256-notmatch'^[a-f0-9]{64}$'-or$worksheet.inventoryDigest-notmatch'^[a-f0-9]{64}$'-or$worksheet.installId-notmatch'^[a-z0-9][a-z0-9-]{7,63}$'){throw 'RECOVERY_WORKSHEET_INVALID'};if($ExpectedKitSha256-and$worksheet.kitSha256-cne$ExpectedKitSha256.ToLowerInvariant()){throw 'RECOVERY_WORKSHEET_KIT_MISMATCH'};if($ExpectedManifestSha256-and$worksheet.manifestSha256-cne$ExpectedManifestSha256.ToLowerInvariant()){throw 'RECOVERY_WORKSHEET_MANIFEST_MISMATCH'};if($ExpectedRuntimeConfigSha256-and$worksheet.runtimeConfigSha256-cne$ExpectedRuntimeConfigSha256.ToLowerInvariant()){throw 'RECOVERY_WORKSHEET_RUNTIME_MISMATCH'};if($ExpectedInstallId-and$worksheet.installId-cne$ExpectedInstallId){throw 'RECOVERY_WORKSHEET_INSTALL_MISMATCH'};if($ExpectedInventoryDigest-and$worksheet.inventoryDigest-cne$ExpectedInventoryDigest.ToLowerInvariant()){throw 'RECOVERY_WORKSHEET_INVENTORY_MISMATCH'};return $worksheet}
function New-RecoveryApprovalPlan([string]$IntendedAction){
  if($IntendedAction-cnotin@('Create','VerifyExtract','Remove')){throw 'RECOVERY_PLAN_ACTION_REQUIRED'};$p=[ordered]@{nodePath=Get-ApprovalPath $NodePath 'RECOVERY_PLAN_NODE_PATH_REQUIRED';nodeSha256=Get-ApprovalHash $ExpectedNodeSha256 'RECOVERY_PLAN_NODE_HASH_REQUIRED';toolPath=Get-ApprovalPath $ToolPath 'RECOVERY_PLAN_TOOL_PATH_REQUIRED';toolSha256=Get-ApprovalHash $ExpectedToolSha256 'RECOVERY_PLAN_TOOL_HASH_REQUIRED';disasterRecovery=[bool]$DisasterRecovery}
  if($IntendedAction-eq'Create'){$p.manifestPath=Get-ApprovalPath $ManifestPath 'RECOVERY_PLAN_MANIFEST_PATH_REQUIRED';$p.manifestSha256=Get-ApprovalHash $ExpectedManifestSha256 'RECOVERY_PLAN_MANIFEST_HASH_REQUIRED';$p.worksheetPath=Get-ApprovalPath $WorksheetPath 'RECOVERY_PLAN_WORKSHEET_PATH_REQUIRED';$p.kitPath=Get-ApprovalPath $KitPath 'RECOVERY_PLAN_KIT_PATH_REQUIRED';$p.adminOnlyRoot=Get-ApprovalPath $AdminOnlyRoot 'RECOVERY_PLAN_ADMIN_ROOT_REQUIRED';$p.escrowKitPath=Get-ApprovalPath $EscrowKitPath 'RECOVERY_PLAN_ESCROW_KIT_REQUIRED';$p.escrowWorksheetPath=Get-ApprovalPath $EscrowWorksheetPath 'RECOVERY_PLAN_ESCROW_WORKSHEET_REQUIRED';$p.escrowRoot=Get-ApprovalPath $EscrowRoot 'RECOVERY_PLAN_ESCROW_ROOT_REQUIRED';$p.runtimeConfigPath=Get-ApprovalPath $RuntimeConfigPath 'RECOVERY_PLAN_RUNTIME_PATH_REQUIRED';$p.runtimeConfigSha256=Get-ApprovalHash $ExpectedRuntimeConfigSha256 'RECOVERY_PLAN_RUNTIME_HASH_REQUIRED';$p.installId=Get-ApprovalText $ExpectedInstallId '^[a-z0-9][a-z0-9-]{7,63}$' 'RECOVERY_PLAN_INSTALL_ID_REQUIRED';$p.filesystemEvidencePath=Get-ApprovalPath $FileSystemEvidencePath 'RECOVERY_PLAN_FS_PATH_REQUIRED';$p.filesystemEvidenceSha256=Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'RECOVERY_PLAN_FS_HASH_REQUIRED'}
  elseif($IntendedAction-eq'VerifyExtract'){$p.escrowWorksheetPath=Get-ApprovalPath $EscrowWorksheetPath 'RECOVERY_PLAN_ESCROW_WORKSHEET_REQUIRED';$p.escrowWorksheetSha256=Get-ApprovalHash $ExpectedEscrowWorksheetSha256 'RECOVERY_PLAN_ESCROW_WORKSHEET_HASH_REQUIRED';$p.escrowKitPath=Get-ApprovalPath $EscrowKitPath 'RECOVERY_PLAN_ESCROW_KIT_REQUIRED';$p.kitSha256=Get-ApprovalHash $ExpectedKitSha256 'RECOVERY_PLAN_KIT_HASH_REQUIRED';$p.expectedManifestSha256=Get-ApprovalHash $ExpectedManifestSha256 'RECOVERY_PLAN_MANIFEST_HASH_REQUIRED';$p.expectedRuntimeConfigSha256=Get-ApprovalHash $ExpectedRuntimeConfigSha256 'RECOVERY_PLAN_RUNTIME_HASH_REQUIRED';$p.expectedInstallId=Get-ApprovalText $ExpectedInstallId '^[a-z0-9][a-z0-9-]{7,63}$' 'RECOVERY_PLAN_INSTALL_ID_REQUIRED';$p.expectedInventoryDigest=Get-ApprovalHash $ExpectedInventoryDigest 'RECOVERY_PLAN_INVENTORY_REQUIRED';$p.evidenceOutputPath=Get-ApprovalOptionalPath $EvidenceOutputPath;if($DisasterRecovery){$p.disasterScratchPath=Get-ApprovalPath $DisasterScratchPath 'RECOVERY_PLAN_DISASTER_SCRATCH_REQUIRED'}else{$p.worksheetPath=Get-ApprovalPath $WorksheetPath 'RECOVERY_PLAN_WORKSHEET_PATH_REQUIRED';$p.worksheetSha256=Get-ApprovalHash $ExpectedWorksheetSha256 'RECOVERY_PLAN_WORKSHEET_HASH_REQUIRED';$p.kitPath=Get-ApprovalPath $KitPath 'RECOVERY_PLAN_KIT_PATH_REQUIRED';$p.adminOnlyRoot=Get-ApprovalPath $AdminOnlyRoot 'RECOVERY_PLAN_ADMIN_ROOT_REQUIRED';$p.manifestPath=Get-ApprovalPath $ManifestPath 'RECOVERY_PLAN_MANIFEST_PATH_REQUIRED';$p.runtimeConfigPath=Get-ApprovalPath $RuntimeConfigPath 'RECOVERY_PLAN_RUNTIME_PATH_REQUIRED';$p.caCertificatePath=Get-ApprovalPath $CaCertificatePath 'RECOVERY_PLAN_CA_PATH_REQUIRED';$p.caCertificateSha256=Get-ApprovalHash $ExpectedCaCertificateSha256 'RECOVERY_PLAN_CA_HASH_REQUIRED';$p.filesystemEvidencePath=Get-ApprovalPath $FileSystemEvidencePath 'RECOVERY_PLAN_FS_PATH_REQUIRED';$p.filesystemEvidenceSha256=Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'RECOVERY_PLAN_FS_HASH_REQUIRED'}}
  else{$p.kitPath=Get-ApprovalPath $KitPath 'RECOVERY_PLAN_KIT_PATH_REQUIRED';$p.kitSha256=Get-ApprovalHash $ExpectedKitSha256 'RECOVERY_PLAN_KIT_HASH_REQUIRED';$p.worksheetPath=Get-ApprovalPath $WorksheetPath 'RECOVERY_PLAN_WORKSHEET_PATH_REQUIRED';$p.worksheetSha256=Get-ApprovalHash $ExpectedWorksheetSha256 'RECOVERY_PLAN_WORKSHEET_HASH_REQUIRED';$p.evidenceOutputPath=Get-ApprovalOptionalPath $EvidenceOutputPath;$p.evidenceSha256=Get-ApprovalOptionalHash $ExpectedEvidenceSha256;Assert-ApprovalOptionalArtifact $EvidenceOutputPath $ExpectedEvidenceSha256 'RECOVERY_PLAN_EVIDENCE_PAIR_REQUIRED'}
  $target=if($IntendedAction-eq'Create'){'Exact encrypted local and separately located escrow kit plus offline worksheet'}elseif($DisasterRecovery){'Exact escrow kit into an empty ADMIN_ONLY disaster scratch directory'}else{'Exact current-install local and escrow copies in an ephemeral ADMIN_ONLY test directory'};$impact=if($IntendedAction-eq'Remove'){'Removes only the exact local kit, worksheet, and optional readiness evidence; escrow is retained'}elseif($IntendedAction-eq'Create'){'Reads the 13 hash-pinned current-install sources, creates authenticated copies and a source-path-free worksheet'}else{'Authenticates and bounded-extracts the exact encrypted inventory; disaster mode does not require any original source path'};New-ApprovalPlan $PSCommandPath $IntendedAction $p $target $impact 'Remove only the exact newly created outputs; the separately retained escrow copy is never removed by rollback'
}
if($Action-eq'Plan'){New-RecoveryApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0};$plan=New-RecoveryApprovalPlan $Action;Assert-ApprovedPlan $plan ([bool]$Approved) $ApprovedPlanSha256;AssertPinned $NodePath $ExpectedNodeSha256 'RECOVERY_NODE_HASH_MISMATCH';AssertPinned $ToolPath $ExpectedToolSha256 'RECOVERY_TOOL_HASH_MISMATCH'
if($Action-eq'Remove'){AssertPinned $KitPath $ExpectedKitSha256 'RECOVERY_KIT_HASH_MISMATCH';AssertPinned $WorksheetPath $ExpectedWorksheetSha256 'RECOVERY_WORKSHEET_HASH_MISMATCH';AssertAdminOnly $KitPath;AssertAdminOnly $WorksheetPath;if($EvidenceOutputPath){AssertPinned $EvidenceOutputPath $ExpectedEvidenceSha256 'RECOVERY_EVIDENCE_HASH_MISMATCH';AssertAdminOnly $EvidenceOutputPath};Remove-Item -LiteralPath $KitPath,$WorksheetPath -Force;if($EvidenceOutputPath){Remove-Item -LiteralPath $EvidenceOutputPath -Force};[pscustomobject]@{Result='REMOVED_LOCAL_COPY';EscrowCopyRetained=$true;ReadinessEvidenceRevoked=$true}|ConvertTo-Json;exit 0}
if($Action-eq'Create'){
  AssertPinned $ManifestPath $ExpectedManifestSha256 'RECOVERY_MANIFEST_HASH_MISMATCH';AssertPinned $RuntimeConfigPath $ExpectedRuntimeConfigSha256 'RECOVERY_RUNTIME_HASH_MISMATCH';AssertPinned $FileSystemEvidencePath $ExpectedFileSystemEvidenceSha256 'RECOVERY_FILESYSTEM_EVIDENCE_HASH_MISMATCH';$fs=Get-Content -Raw -LiteralPath $FileSystemEvidencePath|ConvertFrom-Json;if($fs.result-ne'PASS'-or-not$fs.exactAcl-or-not(Under $AdminOnlyRoot $fs.classRoots.ADMIN_ONLY)-or-not(Under $KitPath $fs.classRoots.ADMIN_ONLY)-or-not(Under $WorksheetPath $fs.classRoots.ADMIN_ONLY)-or-not(Under $ManifestPath $fs.classRoots.ADMIN_ONLY)-or-not(Under $RuntimeConfigPath $fs.classRoots.SHARED_RUNTIME)-or-not(Under $NodePath $fs.classRoots.SHARED_RUNTIME)-or-not(Under $ToolPath $fs.classRoots.SHARED_RUNTIME)){throw 'RECOVERY_FILESYSTEM_EVIDENCE_REJECTED'};AssertAdminOnly $AdminOnlyRoot -Directory;if(-not(Test-Path -LiteralPath $EscrowRoot -PathType Container)){throw 'RECOVERY_ESCROW_REQUIRED'};AssertAdminOnly $EscrowRoot -Directory;AssertEscrowSeparated $AdminOnlyRoot $EscrowRoot;$escrowBoundary=[IO.Path]::GetFullPath($EscrowRoot).TrimEnd('\')+'\';foreach($escrowOutput in @($EscrowKitPath,$EscrowWorksheetPath)){if(-not[IO.Path]::GetFullPath($escrowOutput).StartsWith($escrowBoundary,[StringComparison]::OrdinalIgnoreCase)){throw 'RECOVERY_ESCROW_PATH_INVALID'}}
  foreach($output in @($KitPath,$EscrowKitPath,$WorksheetPath,$EscrowWorksheetPath)){if(Test-Path -LiteralPath $output){throw 'RECOVERY_OUTPUT_ALREADY_EXISTS'}};$manifest=Get-Content -Raw -LiteralPath $ManifestPath|ConvertFrom-Json;$inventoryDigest=ValidateCurrentManifest $manifest $fs;$result=InvokeKit @('--mode=create',"--manifest=$([IO.Path]::GetFullPath($ManifestPath))","--output=$([IO.Path]::GetFullPath($KitPath))");if($result.fileCount-ne13-or$result.inventoryDigest-cne$inventoryDigest-or$result.manifestSha256-cne$ExpectedManifestSha256.ToLowerInvariant()-or$result.runtimeConfigSha256-cne$ExpectedRuntimeConfigSha256.ToLowerInvariant()-or$result.installId-cne$ExpectedInstallId){throw 'RECOVERY_KIT_CREATE_BINDING_FAILED'};Protect $KitPath;Copy-Item -LiteralPath $KitPath -Destination $EscrowKitPath;Protect $EscrowKitPath;$kitSha=FileHash $KitPath;if((FileHash $EscrowKitPath)-cne$kitSha){Remove-Item -LiteralPath $EscrowKitPath -Force;throw 'RECOVERY_ESCROW_COPY_FAILED'};$worksheet=[ordered]@{version=1;kitSha256=$kitSha;manifestSha256=$ExpectedManifestSha256.ToLowerInvariant();runtimeConfigSha256=$ExpectedRuntimeConfigSha256.ToLowerInvariant();installId=$ExpectedInstallId;inventoryDigest=$inventoryDigest};[IO.File]::WriteAllText([IO.Path]::GetFullPath($WorksheetPath),($worksheet|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));Protect $WorksheetPath;Copy-Item -LiteralPath $WorksheetPath -Destination $EscrowWorksheetPath;Protect $EscrowWorksheetPath;$worksheetSha=FileHash $WorksheetPath;if((FileHash $EscrowWorksheetPath)-cne$worksheetSha){Remove-Item -LiteralPath $EscrowWorksheetPath -Force;throw 'RECOVERY_ESCROW_WORKSHEET_COPY_FAILED'};[pscustomobject]@{Result='CREATED';FileCount=13;KitSha256=$kitSha;WorksheetSha256=$worksheetSha;EscrowWorksheetSha256=$worksheetSha;AdminOnlyAcl=$true;EscrowCopyVerified=$true;EscrowWorksheetCopyVerified=$true;TestExtractRequired=$true}|ConvertTo-Json;exit 0
}
$worksheetSource=if($DisasterRecovery){$EscrowWorksheetPath}else{$WorksheetPath};$worksheetExpected=if($DisasterRecovery){$ExpectedEscrowWorksheetSha256}else{$ExpectedWorksheetSha256};$worksheet=ReadWorksheet $worksheetSource $worksheetExpected;AssertPinned $EscrowKitPath $worksheet.kitSha256 'RECOVERY_ESCROW_KIT_HASH_MISMATCH';AssertAdminOnly $EscrowKitPath;AssertPinned $EscrowWorksheetPath $ExpectedEscrowWorksheetSha256 'RECOVERY_ESCROW_WORKSHEET_HASH_MISMATCH';AssertAdminOnly $EscrowWorksheetPath;if(-not$DisasterRecovery-and(FileHash $WorksheetPath)-cne(FileHash $EscrowWorksheetPath)){throw 'RECOVERY_WORKSHEET_COPIES_DIVERGED'}
if($DisasterRecovery){$testRoot=[IO.Path]::GetFullPath($DisasterScratchPath);AssertAdminOnly $testRoot -Directory;if(@(Get-ChildItem -LiteralPath $testRoot -Force).Count){throw 'RECOVERY_DISASTER_SCRATCH_NOT_EMPTY'};$removeAfter=$false}else{AssertPinned $KitPath $worksheet.kitSha256 'RECOVERY_LOCAL_KIT_HASH_MISMATCH';AssertAdminOnly $KitPath;AssertPinned $ManifestPath $worksheet.manifestSha256 'RECOVERY_MANIFEST_HASH_MISMATCH';AssertPinned $RuntimeConfigPath $worksheet.runtimeConfigSha256 'RECOVERY_RUNTIME_HASH_MISMATCH';AssertPinned $CaCertificatePath $ExpectedCaCertificateSha256 'RECOVERY_CA_HASH_MISMATCH';AssertPinned $FileSystemEvidencePath $ExpectedFileSystemEvidenceSha256 'RECOVERY_FILESYSTEM_EVIDENCE_HASH_MISMATCH';$fs=Get-Content -Raw -LiteralPath $FileSystemEvidencePath|ConvertFrom-Json;$manifest=Get-Content -Raw -LiteralPath $ManifestPath|ConvertFrom-Json;if((ValidateCurrentManifest $manifest $fs)-cne$worksheet.inventoryDigest){throw 'RECOVERY_CURRENT_SOURCE_INVENTORY_CHANGED'};AssertAdminOnly $AdminOnlyRoot -Directory;$testRoot=Join-Path ([IO.Path]::GetFullPath($AdminOnlyRoot)) ('recovery-test-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $testRoot|Out-Null;Protect $testRoot -Directory;$removeAfter=$true}
try{$result=InvokeKit @('--mode=extract',"--kit=$([IO.Path]::GetFullPath($EscrowKitPath))","--output-root=$testRoot");if($result.fileCount-ne13-or$result.kitId-cne$worksheet.kitSha256-or$result.manifestSha256-cne$worksheet.manifestSha256-or$result.runtimeConfigSha256-cne$worksheet.runtimeConfigSha256-or$result.installId-cne$worksheet.installId-or$result.inventoryDigest-cne$worksheet.inventoryDigest-or(Get-InventoryDigest $result.files)-cne$worksheet.inventoryDigest){throw 'RECOVERY_KIT_WORKSHEET_BINDING_FAILED'};$expectedNames=@($result.files|ForEach-Object{$_.name}|Sort-Object);$actual=@(Get-ChildItem -LiteralPath $testRoot -File -Force|Sort-Object Name);if($actual.Count-ne13-or($actual.Name-join"`n")-cne($expectedNames-join"`n")){throw 'RECOVERY_EXTRACT_INVENTORY_INVALID'};foreach($item in $actual){Protect $item.FullName;$entry=@($result.files|Where-Object{$_.name-ceq$item.Name});if($entry.Count-ne1-or(FileHash $item.FullName)-cne$entry[0].sha256){throw 'RECOVERY_EXTRACT_HASH_MISMATCH'}};$pfx=@($result.files|Where-Object{$_.purpose-eq'offline-ca-pfx'});$passwordEntry=@($result.files|Where-Object{$_.purpose-eq'offline-ca-pfx-password'});if($pfx.Count-ne1-or$passwordEntry.Count-ne1){throw 'RECOVERY_CA_INVENTORY_INVALID'};$password=[IO.File]::ReadAllText((Join-Path $testRoot $passwordEntry[0].name),[Text.Encoding]::UTF8);if($password-notmatch'^[A-Za-z0-9_-]{43}$'){throw 'RECOVERY_PFX_PASSWORD_INVALID'};$certificates=[Security.Cryptography.X509Certificates.X509Certificate2Collection]::new();try{$certificates.Import((Join-Path $testRoot $pfx[0].name),$password,[Security.Cryptography.X509Certificates.X509KeyStorageFlags]::EphemeralKeySet);$cas=@($certificates|Where-Object{$_.HasPrivateKey-and@($_.Extensions|Where-Object{$_.Oid.Value-eq'2.5.29.19'-and($_.Format($false)-match'CA')}).Count-eq1});if($cas.Count-ne1){throw 'RECOVERY_PFX_TEST_IMPORT_FAILED'};if(-not$DisasterRecovery){$public=[Security.Cryptography.X509Certificates.X509Certificate2]::new($CaCertificatePath);try{if($cas[0].Thumbprint-ine$public.Thumbprint){throw 'RECOVERY_CA_IDENTITY_MISMATCH'}}finally{$public.Dispose()}}}finally{foreach($certificate in $certificates){$certificate.Dispose()};$password=$null}}finally{if($removeAfter-and(Test-Path -LiteralPath $testRoot)){Remove-Item -LiteralPath $testRoot -Recurse -Force}}
if($removeAfter-and(Test-Path -LiteralPath $testRoot)){throw 'RECOVERY_TEST_EXTRACTION_CLEANUP_FAILED'}
if($EvidenceOutputPath){
  $credentialPurposes=@('postgres-admin-pgpass','postgres-backup-pgpass','postgres-migration-pgpass','postgres-runtime-pgpass');$credentialLines=@();foreach($purpose in $credentialPurposes){$entry=@($result.files|Where-Object{$_.purpose-ceq$purpose});if($entry.Count-ne1){throw 'RECOVERY_DATABASE_CREDENTIAL_INVENTORY_INVALID'};$credentialLines+="$purpose=$($entry[0].sha256)"};$integrityEntry=@($result.files|Where-Object{$_.purpose-ceq'backup-integrity-key'});if($integrityEntry.Count-ne1){throw 'RECOVERY_BACKUP_INTEGRITY_KEY_MISSING'}
  $currentInstall=[bool](-not$DisasterRecovery);$executorSetDigest=ShaText (@($ExpectedNodeSha256.ToLowerInvariant(),$ExpectedToolSha256.ToLowerInvariant())-join"`n")
  $readiness=[ordered]@{version=5;result='PASS';kitId=$worksheet.kitSha256;kitSha256=$worksheet.kitSha256;worksheetSha256=$worksheetExpected.ToLowerInvariant();localWorksheetSha256=if($currentInstall){$ExpectedWorksheetSha256.ToLowerInvariant()}else{$null};escrowWorksheetSha256=$ExpectedEscrowWorksheetSha256.ToLowerInvariant();localKitSha256=if($currentInstall){$worksheet.kitSha256}else{$null};escrowKitSha256=$worksheet.kitSha256;manifestSha256=$worksheet.manifestSha256;installId=$worksheet.installId;runtimeConfigSha256=$worksheet.runtimeConfigSha256;inventoryDigest=$worksheet.inventoryDigest;databaseCredentialInventoryDigest=(ShaText ($credentialLines-join"`n"));backupIntegrityKeySha256=[string]$integrityEntry[0].sha256;nodeSha256=$ExpectedNodeSha256.ToLowerInvariant();toolSha256=$ExpectedToolSha256.ToLowerInvariant();executorSetDigest=$executorSetDigest;fileCount=13;exactInventory=$true;authenticatedExtract=$true;boundedExtract=$true;boundedConcurrentChildOutput=$true;processTreeKillOnDeadline=$true;adminOnlyAcl=$true;disasterRecoveryVerified=[bool]$DisasterRecovery;currentInstallBound=$currentInstall;currentSourceHashesVerified=$currentInstall;sourcePathsDisclosed=$false;extractionRetained=[bool]$DisasterRecovery;localCopyPresent=$currentInstall;escrowCopyPresent=$true;escrowWorksheetPresent=$true;escrowSeparated=$currentInstall;copiesMatch=$currentInstall;testExtractRemoved=$currentInstall;pfxPrivateKeyVerified=$true;caIdentityVerified=$currentInstall;completedAt=(Get-Date).ToUniversalTime().ToString('o')}
  $readinessPending="$EvidenceOutputPath.pending";try{if(Test-Path -LiteralPath $EvidenceOutputPath){throw 'RECOVERY_EVIDENCE_ALREADY_EXISTS'};if(Test-Path -LiteralPath $readinessPending){throw 'RECOVERY_READINESS_PENDING_COLLISION'};[IO.File]::WriteAllText($readinessPending,($readiness|ConvertTo-Json),(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $readinessPending -Destination $EvidenceOutputPath;Protect $EvidenceOutputPath}finally{Remove-Item -LiteralPath $readinessPending -Force -ErrorAction SilentlyContinue}
}
[pscustomobject]@{Result='PASS';ExactInventory=$true;AuthenticatedExtract=$true;DisasterRecovery=[bool]$DisasterRecovery;ExtractionRetained=[bool]$DisasterRecovery;SourcePathsDisclosed=$false;PfxPrivateKeyVerified=$true}|ConvertTo-Json
