#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Measure')][string]$Action='Plan',
  [string]$LegacySourceRoot,[string]$MigrationsRoot,[string]$LegacyUploadsRoot,[string]$LegacyReportsRoot,[string]$ReleaseId,
  [string]$GitPath,[string]$ExpectedGitSha256,[string]$NodePath,[string]$ExpectedNodeSha256,
  [string]$ExpectedGitCommit,[string]$ExpectedGitTree,
  [string]$RestartSpecPath,[string]$ExpectedRestartSpecSha256,
  [string]$LegacyWebHealthPath='/backend-api/health/live',[string]$LegacyApiHealthPath='/api/health/live',
  [string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,
  [string]$EvidenceOutputPath,[ValidateSet('MeasureEvidence')][string]$PlannedAction,[string]$ApprovedPlanSha256,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
function Existing([string]$Path,[bool]$Directory,[string]$Code){$kind=if($Directory){'Container'}else{'Leaf'};if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType $kind)){throw$Code};$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');$cursor=Get-Item -LiteralPath $full -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw'LEGACY_BASELINE_REPARSE_REJECTED'};$cursor=$cursor.Parent};return$full}
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function TextHash([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function Under([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');return@($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function Git([string[]]$Arguments){$out=&$GitPath @Arguments 2>$null;if($LASTEXITCODE-ne0){throw'LEGACY_GIT_COMMAND_FAILED'};return(($out-join"`n").Trim())}
function ExactKeys($Value,[string[]]$Keys,[string]$Code){$actual=@($Value.PSObject.Properties.Name|Sort-Object);$expected=@($Keys|Sort-Object);if(($actual-join"`n")-cne($expected-join"`n")){throw$Code}}
function StorageInventory([string]$Root,[string]$Domain){
  $rootFull=Existing $Root $true "LEGACY_$($Domain.ToUpperInvariant())_ROOT_NOT_FOUND";$prefix=$rootFull.TrimEnd('\')+'\';$lines=New-Object 'System.Collections.Generic.List[string]';[long]$bytes=0
  foreach($file in @(Get-ChildItem -LiteralPath $rootFull -File -Recurse -Force|Sort-Object FullName)){
    if(($file.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0-or-not$file.FullName.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw'LEGACY_STORAGE_INVENTORY_REJECTED'}
    $relative=$file.FullName.Substring($prefix.Length).Replace('\','/');if(-not$relative-or$relative.Length-gt1024-or$relative-match'(^|/)\.\.?(/|$)'-or$relative-match'[\x00-\x1f\x7f]'){throw'LEGACY_STORAGE_KEY_REJECTED'}
    $bytes+=[long]$file.Length;if($lines.Count-ge1000000-or$bytes-gt1099511627776-or$file.Length-gt536870912){throw'LEGACY_STORAGE_INVENTORY_LIMIT_EXCEEDED'}
    $lines.Add("$relative|$($file.Length)|$(Hash $file.FullName)")
  }
  return[pscustomobject]@{Root=$rootFull;Digest=(TextHash ($lines-join"`n"));FileCount=$lines.Count;TotalBytes=$bytes}
}
function ListenerProcess([int]$Port){$listeners=@(Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue);if($listeners.Count-ne1-or$listeners[0].LocalAddress-notin@('127.0.0.1','::1')){throw"LEGACY_${Port}_LOOPBACK_LISTENER_INVALID"};$process=Get-Process -Id $listeners[0].OwningProcess -ErrorAction Stop;if((Hash $process.Path)-cne$ExpectedNodeSha256.ToLowerInvariant()){throw'LEGACY_PROCESS_IDENTITY_INVALID'};return$process}
if(-not('LegacyProcessEnvironment' -as[type])){Add-Type -TypeDefinition @'
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;
public static class LegacyProcessEnvironment {
  [StructLayout(LayoutKind.Sequential)] struct PBI { public IntPtr Reserved1; public IntPtr PebBaseAddress; public IntPtr Reserved2; public IntPtr Reserved3; public IntPtr UniquePid; public IntPtr Reserved4; }
  [DllImport("kernel32.dll", SetLastError=true)] static extern IntPtr OpenProcess(uint access, bool inherit, int pid);
  [DllImport("kernel32.dll")] static extern bool CloseHandle(IntPtr handle);
  [DllImport("kernel32.dll", SetLastError=true)] static extern bool ReadProcessMemory(IntPtr process, IntPtr address, byte[] buffer, int size, out IntPtr read);
  [DllImport("kernel32.dll", SetLastError=true)] static extern bool IsWow64Process(IntPtr process, out bool wow64);
  [DllImport("ntdll.dll")] static extern int NtQueryInformationProcess(IntPtr process, int cls, ref PBI info, int size, out int returned);
  [DllImport("shell32.dll", SetLastError=true)] static extern IntPtr CommandLineToArgvW([MarshalAs(UnmanagedType.LPWStr)] string commandLine, out int argc);
  [DllImport("kernel32.dll")] static extern IntPtr LocalFree(IntPtr value);
  static byte[] Read(IntPtr h, long address, int size) { var b=new byte[size]; IntPtr read; if(!ReadProcessMemory(h,new IntPtr(address),b,size,out read)||read.ToInt64()!=size) throw new Win32Exception(); return b; }
  public static string CurrentDirectory(int pid) {
    if(IntPtr.Size!=8) throw new PlatformNotSupportedException("LEGACY_CWD_PROBE_REQUIRES_X64"); var h=OpenProcess(0x0410,false,pid); if(h==IntPtr.Zero) throw new Win32Exception();
    try { bool wow; if(!IsWow64Process(h,out wow)||wow) throw new PlatformNotSupportedException("LEGACY_CWD_PROBE_TARGET_REQUIRES_X64"); var p=new PBI(); int ret; if(NtQueryInformationProcess(h,0,ref p,Marshal.SizeOf<PBI>(),out ret)!=0) throw new InvalidOperationException("LEGACY_CWD_PROBE_QUERY_FAILED"); long pp=BitConverter.ToInt64(Read(h,p.PebBaseAddress.ToInt64()+0x20,8),0); var us=Read(h,pp+0x38,16); int len=BitConverter.ToUInt16(us,0); long ptr=BitConverter.ToInt64(us,8); if(len<2||len>32766||(len%2)!=0) throw new InvalidOperationException("LEGACY_CWD_PROBE_VALUE_INVALID"); return System.Text.Encoding.Unicode.GetString(Read(h,ptr,len)); }
    finally { CloseHandle(h); }
  }
  public static string[] ParseCommandLine(string commandLine) { int count; var block=CommandLineToArgvW(commandLine,out count); if(block==IntPtr.Zero||count<1||count>65) throw new Win32Exception(); try { var result=new string[count]; for(int i=0;i<count;i++) result[i]=Marshal.PtrToStringUni(Marshal.ReadIntPtr(block,i*IntPtr.Size)); return result; } finally { LocalFree(block); } }
}
'@}
function LaunchIdentity($Process,$Spec,[int]$Port){$cim=Get-CimInstance Win32_Process -Filter "ProcessId=$($Process.Id)" -ErrorAction Stop;if(-not$cim-or-not$cim.CommandLine-or$cim.CommandLine.Length-gt32767-or$cim.CommandLine-match'[\x00\r\n]'){throw'LEGACY_COMMAND_LINE_PROBE_INVALID'};$working=[LegacyProcessEnvironment]::CurrentDirectory([int]$Process.Id);$expectedWorking=[IO.Path]::GetFullPath([string]$Spec.workingDirectory).TrimEnd('\');if([IO.Path]::GetFullPath($working).TrimEnd('\')-ine$expectedWorking){throw'LEGACY_WORKING_DIRECTORY_MISMATCH'};$actual=@([LegacyProcessEnvironment]::ParseCommandLine([string]$cim.CommandLine));$expected=@([IO.Path]::GetFullPath([string]$Spec.filePath))+@($Spec.arguments|ForEach-Object{[string]$_});if($actual.Count-ne$expected.Count-or[IO.Path]::GetFullPath($actual[0])-ine$expected[0]){throw'LEGACY_COMMAND_LINE_RESTART_SPEC_MISMATCH'};for($index=1;$index-lt$actual.Count;$index++){if($actual[$index]-cne$expected[$index]){throw'LEGACY_COMMAND_LINE_RESTART_SPEC_MISMATCH'}};$actualCommandHash=TextHash ((@($actual|ForEach-Object{"$($_.Length):$_"}))-join"`0");$expectedCommandHash=TextHash ((@($expected|ForEach-Object{"$($_.Length):$_"}))-join"`0");if($actualCommandHash-cne$expectedCommandHash){throw'LEGACY_COMMAND_LINE_RESTART_SPEC_MISMATCH'};$workingHash=TextHash $expectedWorking.ToLowerInvariant();$canonical=TextHash (@([string]$Port,$actualCommandHash,$workingHash)-join"`n");return[pscustomobject]@{CommandLineSha256=$actualCommandHash;WorkingDirectorySha256=$workingHash;CanonicalDigest=$canonical}}
function HealthDigest([int]$Port,[string]$Path){if($Path-notmatch'^/[A-Za-z0-9/_-]{1,255}$'){throw'LEGACY_HEALTH_PATH_INVALID'};try{$request=[Net.HttpWebRequest]::Create("http://127.0.0.1:$Port$Path");$request.Proxy=$null;$request.Timeout=5000;$response=$request.GetResponse();try{$reader=[IO.StreamReader]::new($response.GetResponseStream());$body=$reader.ReadToEnd();if([int]$response.StatusCode-ne200-or$body.Length-gt4096){throw'LEGACY_HEALTH_SMOKE_FAILED'};$value=$body|ConvertFrom-Json;if($value.status-cne'live'){throw'LEGACY_HEALTH_SMOKE_FAILED'};return TextHash (@('live',[string]$value.releaseId)-join'|')}finally{$response.Dispose()}}catch{throw'LEGACY_HEALTH_SMOKE_FAILED'}}

$source=Existing $LegacySourceRoot $true 'LEGACY_SOURCE_NOT_FOUND';$migrations=Existing $MigrationsRoot $true 'LEGACY_MIGRATIONS_NOT_FOUND';$uploads=Existing $LegacyUploadsRoot $true 'LEGACY_UPLOADS_ROOT_NOT_FOUND';$reports=Existing $LegacyReportsRoot $true 'LEGACY_REPORTS_ROOT_NOT_FOUND';$git=Existing $GitPath $false 'GIT_NOT_FOUND';$node=Existing $NodePath $false 'NODE_NOT_FOUND';$restartSpec=Existing $RestartSpecPath $false 'LEGACY_RESTART_SPEC_NOT_FOUND';$fsPath=Existing $FileSystemEvidencePath $false 'FILESYSTEM_EVIDENCE_NOT_FOUND'
if(-not(Under $migrations @($source))-or-not(Under $uploads @($source))-or-not(Under $reports @($source))-or(Under $uploads @($reports))-or(Under $reports @($uploads))){throw'LEGACY_SOURCE_ROOT_BOUNDARY_INVALID'}
foreach($entry in @(@{Path=$git;Expected=$ExpectedGitSha256;Code='GIT_HASH_MISMATCH'},@{Path=$node;Expected=$ExpectedNodeSha256;Code='NODE_HASH_MISMATCH'},@{Path=$restartSpec;Expected=$ExpectedRestartSpecSha256;Code='RESTART_SPEC_HASH_MISMATCH'},@{Path=$fsPath;Expected=$ExpectedFileSystemEvidenceSha256;Code='FILESYSTEM_EVIDENCE_HASH_MISMATCH'})){if($entry.Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $entry.Path)-cne$entry.Expected.ToLowerInvariant()){throw$entry.Code}}
$fs=Get-Content -Raw -LiteralPath $fsPath|ConvertFrom-Json;if($fs.result-ne'PASS'-or-not$fs.exactAcl-or-not(Under $git $fs.classRoots.SHARED_RUNTIME)-or-not(Under $node $fs.classRoots.SHARED_RUNTIME)-or-not(Under $restartSpec $fs.classRoots.ADMIN_ONLY)-or($EvidenceOutputPath-and-not(Under $EvidenceOutputPath $fs.classRoots.ADMIN_EVIDENCE))){throw'LEGACY_BASELINE_FILESYSTEM_BOUNDARY_REJECTED'}
$restart=Get-Content -Raw -LiteralPath $restartSpec|ConvertFrom-Json;ExactKeys $restart @('version','sourceRoot','web','api') 'RESTART_SPEC_KEYS_INVALID';foreach($name in @('web','api')){ExactKeys $restart.$name @('filePath','workingDirectory','arguments') 'RESTART_PROCESS_SPEC_KEYS_INVALID';if([IO.Path]::GetFullPath([string]$restart.$name.filePath)-ine$node-or-not(Under ([string]$restart.$name.workingDirectory) @($source))-or-not($restart.$name.arguments-is[Array])-or@($restart.$name.arguments).Count-lt1-or@($restart.$name.arguments).Count-gt64-or@($restart.$name.arguments|Where-Object{$_-isnot[string]-or$_.Length-lt1-or$_.Length-gt2048-or$_-match'[\x00\r\n]'}).Count){throw'RESTART_PROCESS_SPEC_INVALID'}};if($restart.version-ne1-or[IO.Path]::GetFullPath([string]$restart.sourceRoot).TrimEnd('\')-ine$source){throw'RESTART_SPEC_SOURCE_MISMATCH'}
if($ReleaseId-notmatch'^[a-z0-9][a-z0-9._-]{0,62}$'-or$ExpectedGitCommit-notmatch'^[0-9a-f]{40}$'-or$ExpectedGitTree-notmatch'^[0-9a-f]{40}$'){throw'LEGACY_BASELINE_IDENTITY_INVALID'}
if(Git @('-C',$source,'status','--porcelain','--untracked-files=no')){throw'LEGACY_TRACKED_TREE_DIRTY'};$commit=Git @('-C',$source,'rev-parse','HEAD');$tree=Git @('-C',$source,'rev-parse','HEAD^{tree}');if($commit-cne$ExpectedGitCommit-or$tree-cne$ExpectedGitTree){throw'LEGACY_GIT_IDENTITY_MISMATCH'}
$tracked=@(Git @('-C',$source,'-c','core.quotepath=false','ls-files') -split"`n"|Where-Object{$_});if($tracked.Count-lt1-or$tracked.Count-gt100000-or@($tracked|Where-Object{$_.Length-gt1024-or$_.Contains('"')-or$_-match'[\x00-\x1f]'}).Count-gt0){throw'LEGACY_TRACKED_INVENTORY_INVALID'};$sourceLines=@();foreach($relative in $tracked){$file=Existing (Join-Path $source $relative) $false 'LEGACY_TRACKED_FILE_MISSING';if(-not(Under $file @($source))){throw'LEGACY_TRACKED_FILE_ESCAPE'};$sourceLines+="$relative=$(Hash $file)"};$sourceInventoryDigest=TextHash (($sourceLines|Sort-Object)-join"`n")
$migrationLines=@(Get-ChildItem -LiteralPath $migrations -Filter migration.sql -File -Recurse|Sort-Object FullName|ForEach-Object{$relative=$_.FullName.Substring($migrations.TrimEnd('\').Length+1).Replace('\','/');"$relative=$(Hash $_.FullName)"});if($migrationLines.Count-lt1){throw'LEGACY_MIGRATION_INVENTORY_EMPTY'};$migrationDigest=TextHash ($migrationLines-join"`n")
$uploadInventory=StorageInventory $uploads 'uploads';$reportInventory=StorageInventory $reports 'reports';$storageInventoryDigest=TextHash (@("uploads=$($uploadInventory.Digest)","reports=$($reportInventory.Digest)")-join"`n")
$web=ListenerProcess 3100;$api=ListenerProcess 4100;if($web.Id-eq$api.Id){throw'LEGACY_PROCESS_CARDINALITY_INVALID'};$webLaunch=LaunchIdentity $web $restart.web 3100;$apiLaunch=LaunchIdentity $api $restart.api 4100;$webObservedCommandLineSha256=TextHash ([string](Get-CimInstance Win32_Process -Filter "ProcessId=$($web.Id)").CommandLine).Trim();$apiObservedCommandLineSha256=TextHash ([string](Get-CimInstance Win32_Process -Filter "ProcessId=$($api.Id)").CommandLine).Trim();$webHealthDigest=HealthDigest 3100 $LegacyWebHealthPath;$apiHealthDigest=HealthDigest 4100 $LegacyApiHealthPath;$restartCanonicalDigest=TextHash (@($webLaunch.CanonicalDigest,$apiLaunch.CanonicalDigest)-join"`n");$processIdentityDigest=TextHash (@("3100|$($web.Id)|$($web.StartTime.ToUniversalTime().ToString('o'))|$(Hash $web.Path)|$($webLaunch.CanonicalDigest)","4100|$($api.Id)|$($api.StartTime.ToUniversalTime().ToString('o'))|$(Hash $api.Path)|$($apiLaunch.CanonicalDigest)")-join"`n")
function New-BaselineApprovalPlan([string]$IntendedAction){if($IntendedAction-cne'MeasureEvidence'){throw'LEGACY_BASELINE_PLAN_ACTION_REQUIRED'};$p=[ordered]@{legacySourceRoot=$source;migrationsRoot=$migrations;legacyUploadsRoot=$uploads;legacyReportsRoot=$reports;releaseId=$ReleaseId;gitPath=$git;gitSha256=$ExpectedGitSha256.ToLowerInvariant();nodePath=$node;nodeSha256=$ExpectedNodeSha256.ToLowerInvariant();gitCommit=$ExpectedGitCommit;gitTree=$ExpectedGitTree;restartSpecPath=$restartSpec;restartSpecSha256=$ExpectedRestartSpecSha256.ToLowerInvariant();filesystemEvidencePath=$fsPath;filesystemEvidenceSha256=$ExpectedFileSystemEvidenceSha256.ToLowerInvariant();evidenceOutputPath=Get-ApprovalPath $EvidenceOutputPath 'LEGACY_BASELINE_PLAN_OUTPUT_REQUIRED';webProcessId=[int]$web.Id;webProcessStartedAt=$web.StartTime.ToUniversalTime().ToString('o');webObservedCommandLineSha256=$webObservedCommandLineSha256;webLaunchCanonicalDigest=$webLaunch.CanonicalDigest;webHealthPath=$LegacyWebHealthPath;webHealthDigest=$webHealthDigest;apiProcessId=[int]$api.Id;apiProcessStartedAt=$api.StartTime.ToUniversalTime().ToString('o');apiObservedCommandLineSha256=$apiObservedCommandLineSha256;apiLaunchCanonicalDigest=$apiLaunch.CanonicalDigest;apiHealthPath=$LegacyApiHealthPath;apiHealthDigest=$apiHealthDigest;restartCanonicalDigest=$restartCanonicalDigest};New-ApprovalPlan $PSCommandPath 'MeasureEvidence' $p "Exact live legacy PID $($web.Id)/$($api.Id), loopback 3100/4100, and repository-local uploads/reports" 'Reads source/storage/process launch identity and writes one baseline bound to actual command-line, working-directory, and health digests; no process, database, Auth, or Storage mutation' 'Delete only the exact baseline evidence file'}
if($Action-eq'Plan'){New-BaselineApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0};if($EvidenceOutputPath){$approvalPlan=New-BaselineApprovalPlan 'MeasureEvidence';Assert-ApprovedPlan $approvalPlan ([bool]$Approved) $ApprovedPlanSha256}
$result=[ordered]@{version=3;result='PASS';proofType='legacy-running-baseline';releaseId=$ReleaseId;gitCommit=$commit;gitTree=$tree;sourceInventoryDigest=$sourceInventoryDigest;migrationDigest=$migrationDigest;legacySourceRoot=$source;legacyMigrationsRoot=$migrations;legacyUploadsRoot=$uploads;legacyReportsRoot=$reports;uploadsInventoryDigest=$uploadInventory.Digest;uploadsFileCount=$uploadInventory.FileCount;uploadsTotalBytes=$uploadInventory.TotalBytes;reportsInventoryDigest=$reportInventory.Digest;reportsFileCount=$reportInventory.FileCount;reportsTotalBytes=$reportInventory.TotalBytes;storageInventoryDigest=$storageInventoryDigest;originalWebPort=3100;originalApiPort=4100;webProcessId=$web.Id;apiProcessId=$api.Id;webProcessStartedAt=$web.StartTime.ToUniversalTime().ToString('o');apiProcessStartedAt=$api.StartTime.ToUniversalTime().ToString('o');webObservedCommandLineSha256=$webObservedCommandLineSha256;webCommandLineSha256=$webLaunch.CommandLineSha256;webWorkingDirectorySha256=$webLaunch.WorkingDirectorySha256;webLaunchCanonicalDigest=$webLaunch.CanonicalDigest;webHealthPath=$LegacyWebHealthPath;webHealthDigest=$webHealthDigest;apiObservedCommandLineSha256=$apiObservedCommandLineSha256;apiCommandLineSha256=$apiLaunch.CommandLineSha256;apiWorkingDirectorySha256=$apiLaunch.WorkingDirectorySha256;apiLaunchCanonicalDigest=$apiLaunch.CanonicalDigest;apiHealthPath=$LegacyApiHealthPath;apiHealthDigest=$apiHealthDigest;restartCanonicalDigest=$restartCanonicalDigest;launchIdentityMatchesProtectedRestartSpec=$true;legacyIdentityHealthSmokeVerified=$true;nodeExecutableSha256=$ExpectedNodeSha256.ToLowerInvariant();restartSpecSha256=$ExpectedRestartSpecSha256.ToLowerInvariant();legacyAuthProvider='supabase';legacyStorageProvider='repository_local_ntfs';localReleaseManifestApplicable=$false;localRoleMatrixApplicable=$false;referenceConversionRequired=$true;processIdentityDigest=$processIdentityDigest;completedAt=(Get-Date).ToUniversalTime().ToString('o')}
if($EvidenceOutputPath){if(Test-Path -LiteralPath $EvidenceOutputPath){throw'LEGACY_BASELINE_EVIDENCE_ALREADY_EXISTS'};[IO.File]::WriteAllText([IO.Path]::GetFullPath($EvidenceOutputPath),($result|ConvertTo-Json),(New-Object Text.UTF8Encoding($false)))}
$result|ConvertTo-Json
