#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Authorize','Publish')][string]$Action='Plan',[ValidateSet('OneTime','Scheduled')][string]$AuthorizationMode='OneTime',
  [string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,[string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,
  [string]$NodePath,[string]$ExpectedNodeSha256,[string]$SemanticSignerPath,[string]$ExpectedSemanticSignerSha256,
  [string]$BackupIntegrityKeyFile,[string]$ExpectedBackupIntegrityKeySha256,[string]$BackupReceiptPrivateKeyPath,[string]$ExpectedBackupReceiptPrivateKeySha256,
  [string]$BackupId,[string]$ExpectedReceiptRequestSha256,[string]$ExpectedBackupTargetFingerprint,[string]$ExpectedBackupContractSha256,[string]$ExpectedPgPassSha256,[string]$ExpectedNasIdentityHelperSha256,[string]$SignerAccount,
  [string]$SignerAuthorizationPath,[string]$ExpectedSignerAuthorizationSha256,[string]$SignerAuthorizationPrivateKeyPath,[string]$ExpectedSignerAuthorizationPrivateKeySha256,
  [string]$SignerAuthorizationPublicKeyPath,[string]$ExpectedSignerAuthorizationPublicKeySha256,[string]$AttestationSignerPath,[string]$ExpectedAttestationSignerSha256,
  [string]$ScheduledAuthorizationPath,[string]$ExpectedScheduledAuthorizationSha256,[string]$ScheduleAuthorizationPublicKeyPath,[string]$ExpectedScheduleAuthorizationPublicKeySha256,
  [string]$AttestationVerifierPath,[string]$ExpectedAttestationVerifierSha256,[string]$SignerScratchRoot,[string]$SignerReplayLedgerRoot,
  [ValidateSet('Authorize')][string]$PlannedAction='Authorize',[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved,[switch]$ReplayLedgerSelfTest
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')

function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function HashText([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function NoReparse([string]$Path){$cursor=Get-Item -LiteralPath ([IO.Path]::GetFullPath($Path)) -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'BACKUP_RECEIPT_REPARSE_REJECTED'};$cursor=$cursor.Parent}}
function Existing([string]$Path,[bool]$Directory,[string]$Code){if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType $(if($Directory){'Container'}else{'Leaf'}))){throw $Code};$full=[IO.Path]::GetFullPath($Path);NoReparse $full;return $full}
function Under([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path);return @($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function Pinned([string]$Path,[string]$Expected,[string]$Code){$full=Existing $Path $false $Code;if($Expected-notmatch'^[a-fA-F0-9]{64}$'-or(Hash $full)-cne$Expected.ToLowerInvariant()){throw $Code};return $full}
function ExactKeys($Value,[string[]]$Keys,[string]$Code){$actual=@($Value.PSObject.Properties.Name|Sort-Object);$expected=@($Keys|Sort-Object);if(($actual-join"`n")-cne($expected-join"`n")){throw $Code}}
function ReadJson([string]$Path,[string]$Code){$item=Get-Item -LiteralPath $Path -Force;if($item.PSIsContainer-or$item.Length-lt1-or$item.Length-gt1048576-or($item.Attributes-band[IO.FileAttributes]::ReparsePoint)){throw $Code};try{return Get-Content -Raw -LiteralPath $item.FullName|ConvertFrom-Json}catch{throw $Code}}
function Timestamp([object]$Value,[string]$Code){try{if($Value-is[datetime]){if($Value.Kind-eq[DateTimeKind]::Unspecified){throw $Code};return [datetimeoffset]$Value};return [datetimeoffset]::ParseExact([string]$Value,'o',[Globalization.CultureInfo]::InvariantCulture)}catch{throw $Code}}
function Stop-Tree($Process){if($Process-and-not$Process.HasExited){try{$Process.Kill($true)}catch{throw 'BACKUP_RECEIPT_PROCESS_TREE_KILL_FAILED'};if(-not$Process.WaitForExit(5000)){throw 'BACKUP_RECEIPT_PROCESS_TREE_KILL_TIMEOUT'}}}
function Invoke-Bounded([string]$File,[string]$ExpectedHash,[string[]]$Arguments,[string]$Code,[int]$MaximumMilliseconds=300000,[int]$MaximumOutputBytes=1048576){
  $executable=Pinned $File $ExpectedHash "$Code`_EXECUTOR_HASH_MISMATCH";$info=[Diagnostics.ProcessStartInfo]::new();$info.FileName=$executable;$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true
  foreach($name in @('DATABASE_URL','PGPASSWORD','PGPASSFILE','PGSSLMODE','PGSSLROOTCERT','PGOPTIONS')){$info.Environment.Remove($name)|Out-Null};foreach($argument in $Arguments){$info.ArgumentList.Add($argument)}
  $process=[Diagnostics.Process]::new();$process.StartInfo=$info;$stdout=[IO.MemoryStream]::new();$stderr=[IO.MemoryStream]::new();$outBuffer=New-Object byte[] 8192;$errBuffer=New-Object byte[] 8192;$watch=[Diagnostics.Stopwatch]::StartNew()
  try{if(-not$process.Start()){throw "$Code`_START_FAILED"};$outTask=$process.StandardOutput.BaseStream.ReadAsync($outBuffer,0,$outBuffer.Length);$errTask=$process.StandardError.BaseStream.ReadAsync($errBuffer,0,$errBuffer.Length);$outDone=$false;$errDone=$false
    while(-not($process.HasExited-and$outDone-and$errDone)){if($watch.ElapsedMilliseconds-ge$MaximumMilliseconds){Stop-Tree $process;throw "$Code`_TIMEOUT"};if(-not$outDone-and$outTask.IsCompleted){$count=$outTask.GetAwaiter().GetResult();if($count-eq0){$outDone=$true}else{if($stdout.Length+$stderr.Length+$count-gt$MaximumOutputBytes){Stop-Tree $process;throw "$Code`_OUTPUT_LIMIT"};$stdout.Write($outBuffer,0,$count);$outTask=$process.StandardOutput.BaseStream.ReadAsync($outBuffer,0,$outBuffer.Length)}};if(-not$errDone-and$errTask.IsCompleted){$count=$errTask.GetAwaiter().GetResult();if($count-eq0){$errDone=$true}else{if($stdout.Length+$stderr.Length+$count-gt$MaximumOutputBytes){Stop-Tree $process;throw "$Code`_OUTPUT_LIMIT"};$stderr.Write($errBuffer,0,$count);$errTask=$process.StandardError.BaseStream.ReadAsync($errBuffer,0,$errBuffer.Length)}};if(-not($process.HasExited-and$outDone-and$errDone)){[Threading.Thread]::Sleep(10)}}
    if($process.ExitCode-ne0){throw $Code};return [Text.Encoding]::UTF8.GetString($stdout.ToArray()).Trim()
  }finally{Stop-Tree $process;$process.Dispose();$stdout.Dispose();$stderr.Dispose();$watch.Stop()}
}
function Copy-PinnedRequest([string]$Source,[string]$Destination,[string]$Expected){
  $sourcePath=Existing $Source $false 'BACKUP_RECEIPT_REQUEST_NOT_FOUND';$input=[IO.File]::Open($sourcePath,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$output=$null;$sha=[Security.Cryptography.SHA256]::Create()
  try{if($input.Length-lt1-or$input.Length-gt1048576){throw 'BACKUP_RECEIPT_REQUEST_SIZE_INVALID'};$output=[IO.File]::Open($Destination,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$buffer=New-Object byte[] 65536;[long]$total=0;while(($read=$input.Read($buffer,0,$buffer.Length))-gt0){$total+=$read;if($total-gt1048576){throw 'BACKUP_RECEIPT_REQUEST_SIZE_INVALID'};[void]$sha.TransformBlock($buffer,0,$read,$null,0);$output.Write($buffer,0,$read)};[void]$sha.TransformFinalBlock([byte[]]::new(0),0,0);$actual=([BitConverter]::ToString($sha.Hash)).Replace('-','').ToLowerInvariant();if($actual-cne$Expected.ToLowerInvariant()){throw 'BACKUP_RECEIPT_REQUEST_HASH_MISMATCH'};$output.Flush($true);return $actual}finally{if($output){$output.Dispose()};$sha.Dispose();$input.Dispose()}
}
function Open-PinnedGuard([string]$Path,[string]$Expected){
  $stream=[IO.File]::Open((Existing $Path $false 'BACKUP_RECEIPT_REQUEST_NOT_FOUND'),[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$sha=[Security.Cryptography.SHA256]::Create()
  try{if($stream.Length-lt1-or$stream.Length-gt1048576){throw 'BACKUP_RECEIPT_REQUEST_SIZE_INVALID'};$buffer=New-Object byte[] 65536;while(($read=$stream.Read($buffer,0,$buffer.Length))-gt0){[void]$sha.TransformBlock($buffer,0,$read,$null,0)};[void]$sha.TransformFinalBlock([byte[]]::new(0),0,0);$actual=([BitConverter]::ToString($sha.Hash)).Replace('-','').ToLowerInvariant();if($actual-cne$Expected.ToLowerInvariant()){throw 'BACKUP_RECEIPT_REQUEST_CHANGED_BEFORE_PUBLISH'};return [pscustomobject]@{Stream=$stream;Sha256=$actual}}catch{$stream.Dispose();throw}finally{$sha.Dispose()}
}
function Open-ArtifactGuards([string]$Root){
  $rootPath=Existing $Root $true 'BACKUP_ARTIFACT_ROOT_INVALID';$streams=New-Object 'System.Collections.Generic.List[IO.FileStream]';$pending=New-Object 'System.Collections.Generic.Stack[string]';$pending.Push($rootPath);[long]$total=0
  try{while($pending.Count){$directory=$pending.Pop();foreach($entry in [IO.Directory]::EnumerateFileSystemEntries($directory)){$item=Get-Item -LiteralPath $entry -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'BACKUP_ARTIFACT_REPARSE_REJECTED'};if($item.PSIsContainer){$pending.Push($item.FullName);continue};if($streams.Count-ge1000010-or$item.Length-lt0){throw 'BACKUP_ARTIFACT_GUARD_LIMIT'};$total+=$item.Length;if($total-gt1099511627776){throw 'BACKUP_ARTIFACT_GUARD_LIMIT'};$streams.Add([IO.FileStream]::new($item.FullName,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read,4096,[IO.FileOptions]::SequentialScan))}};return $streams}catch{foreach($stream in $streams){$stream.Dispose()};throw}
}
function Assert-Request($Request,[string]$ExpectedPublisherHash){
  ExactKeys $Request @('attestationType','backupContractSha256','backupId','backupIntegrityKeySha256','backupReceiptPrivateKeySha256','backupRoot','completedAt','manifestSha256','nasIdentityHelperSha256','pgPassSha256','receiptPublisherSha256','result','semanticSignerSha256','targetEvidenceFingerprint','version') 'BACKUP_RECEIPT_REQUEST_KEYS_INVALID'
  if($Request.attestationType-cne'backup-latest'-or$Request.version-ne6-or$Request.result-cne'COMPLETE'-or$Request.backupId-cne$BackupId-or$Request.manifestSha256-notmatch'^[0-9a-f]{64}$'-or$Request.targetEvidenceFingerprint-cne$ExpectedBackupTargetFingerprint.ToLowerInvariant()-or$Request.backupContractSha256-cne$ExpectedBackupContractSha256.ToLowerInvariant()-or$Request.pgPassSha256-cne$ExpectedPgPassSha256.ToLowerInvariant()-or$Request.nasIdentityHelperSha256-cne$ExpectedNasIdentityHelperSha256.ToLowerInvariant()-or$Request.backupIntegrityKeySha256-cne$ExpectedBackupIntegrityKeySha256.ToLowerInvariant()-or$Request.backupReceiptPrivateKeySha256-cne$ExpectedBackupReceiptPrivateKeySha256.ToLowerInvariant()-or$Request.receiptPublisherSha256-cne$ExpectedPublisherHash-or$Request.semanticSignerSha256-cne$ExpectedSemanticSignerSha256.ToLowerInvariant()){throw 'BACKUP_RECEIPT_REQUEST_BINDING_REJECTED'}
}
function Assert-TimeWindow($Authorization,[double]$MaximumMinutes){try{$issued=[datetimeoffset]::ParseExact([string]$Authorization.authorizationIssuedAt,'o',[Globalization.CultureInfo]::InvariantCulture);$expires=[datetimeoffset]::ParseExact([string]$Authorization.authorizationExpiresAt,'o',[Globalization.CultureInfo]::InvariantCulture)}catch{throw 'BACKUP_SIGNER_AUTHORIZATION_TIME_INVALID'};$now=[datetimeoffset]::UtcNow;if($expires-le$issued-or($expires-$issued).TotalMinutes-gt$MaximumMinutes-or$now-lt$issued.AddMinutes(-1)-or$now-gt$expires){throw 'BACKUP_SIGNER_AUTHORIZATION_EXPIRED'}}
function Get-Authorization($Request,$Fs,[string]$ExpectedSignerSid){
  $verifier=Pinned $AttestationVerifierPath $ExpectedAttestationVerifierSha256 'ATTESTATION_VERIFIER_HASH_MISMATCH'
  if($AuthorizationMode-eq'OneTime'){$path=Pinned $SignerAuthorizationPath $ExpectedSignerAuthorizationSha256 'BACKUP_SIGNER_AUTHORIZATION_HASH_MISMATCH';$public=Pinned $SignerAuthorizationPublicKeyPath $ExpectedSignerAuthorizationPublicKeySha256 'BACKUP_SIGNER_AUTHORIZATION_PUBLIC_KEY_HASH_MISMATCH';if(-not(Under $path $Fs.classRoots.ADMIN_EVIDENCE)-or-not(Under $public $Fs.classRoots.SHARED_RUNTIME)){throw 'BACKUP_SIGNER_AUTHORIZATION_CLASS_REJECTED'};Invoke-Bounded $NodePath $ExpectedNodeSha256 @($verifier,$public,$path,'backup-signer-authorization') 'BACKUP_SIGNER_AUTHORIZATION_SIGNATURE_REJECTED'|Out-Null;$authorization=ReadJson $path 'BACKUP_SIGNER_AUTHORIZATION_INVALID';ExactKeys $authorization @('attestationSignature','attestationType','authorizationExpiresAt','authorizationInstanceId','authorizationIssuedAt','authorizationNonce','backupContractSha256','backupId','backupIntegrityKeySha256','backupReceiptPrivateKeySha256','nasIdentityHelperSha256','pgPassSha256','receiptPublisherSha256','requestSha256','result','semanticSignerSha256','signerSid','signingKeyId','targetEvidenceFingerprint','version') 'BACKUP_SIGNER_AUTHORIZATION_KEYS_INVALID';if($authorization.version-ne2-or$authorization.attestationType-cne'backup-signer-authorization'-or$authorization.result-cne'APPROVED'-or$authorization.backupId-cne$BackupId-or$authorization.requestSha256-cne$ExpectedReceiptRequestSha256.ToLowerInvariant()-or$authorization.signerSid-cne$ExpectedSignerSid){throw 'BACKUP_SIGNER_AUTHORIZATION_BINDING_REJECTED'};Assert-TimeWindow $authorization 15}
  else{$path=Pinned $ScheduledAuthorizationPath $ExpectedScheduledAuthorizationSha256 'SCHEDULE_AUTHORIZATION_HASH_MISMATCH';$public=Pinned $ScheduleAuthorizationPublicKeyPath $ExpectedScheduleAuthorizationPublicKeySha256 'SCHEDULE_AUTHORIZATION_PUBLIC_KEY_HASH_MISMATCH';if(-not(Under $path $Fs.classRoots.ADMIN_EVIDENCE)-or-not(Under $public $Fs.classRoots.SHARED_RUNTIME)){throw 'SCHEDULE_AUTHORIZATION_CLASS_REJECTED'};Invoke-Bounded $NodePath $ExpectedNodeSha256 @($verifier,$public,$path,'backup-schedule-authorization') 'SCHEDULE_AUTHORIZATION_SIGNATURE_REJECTED'|Out-Null;$authorization=ReadJson $path 'SCHEDULE_AUTHORIZATION_INVALID';ExactKeys $authorization @('attestationSignature','attestationType','authorizationExpiresAt','authorizationInstanceId','authorizationIssuedAt','authorizationNonce','backupIntegrityKeySha256','backupReceiptPrivateKeySha256','contractSha256','nasIdentityHelperSha256','pgPassSha256','receiptPublisherSha256','result','semanticSignerSha256','signingKeyId','taskName','version') 'SCHEDULE_AUTHORIZATION_KEYS_INVALID';if($authorization.version-ne3-or$authorization.attestationType-cne'backup-schedule-authorization'-or$authorization.result-cne'APPROVED'-or$authorization.taskName-cne'Meta Ads Performance Daily Backup'-or$authorization.contractSha256-cne$ExpectedBackupContractSha256.ToLowerInvariant()){throw 'SCHEDULE_AUTHORIZATION_BINDING_REJECTED'};Assert-TimeWindow $authorization 44640}
  $authorizationContract=if($AuthorizationMode-eq'OneTime'){$authorization.backupContractSha256}else{$authorization.contractSha256}
  if($authorization.authorizationNonce-notmatch'^[0-9a-f]{64}$'-or$authorization.authorizationInstanceId-notmatch'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'-or$authorization.signingKeyId-notmatch'^[0-9a-f]{64}$'-or$authorization.pgPassSha256-cne$Request.pgPassSha256-or$authorization.nasIdentityHelperSha256-cne$Request.nasIdentityHelperSha256-or$authorization.backupIntegrityKeySha256-cne$Request.backupIntegrityKeySha256-or$authorization.backupReceiptPrivateKeySha256-cne$Request.backupReceiptPrivateKeySha256-or$authorization.receiptPublisherSha256-cne$Request.receiptPublisherSha256-or$authorization.semanticSignerSha256-cne$Request.semanticSignerSha256-or$authorizationContract-cne$Request.backupContractSha256-or($AuthorizationMode-eq'OneTime'-and$authorization.targetEvidenceFingerprint-cne$Request.targetEvidenceFingerprint)){throw 'BACKUP_SIGNER_AUTHORIZATION_BINDING_REJECTED'}
  return $authorization
}
function Write-AtomicReplayRecord([string]$Path,$Value,[bool]$CreateOnly){
  $parent=Split-Path -Parent $Path;$temporary=Join-Path $parent ('.replay-'+[guid]::NewGuid().ToString('N')+'.tmp');$stream=$null
  try{$stream=[IO.File]::Open($temporary,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$bytes=[Text.Encoding]::UTF8.GetBytes(($Value|ConvertTo-Json -Compress));$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true);$stream.Dispose();$stream=$null;if($CreateOnly){[IO.File]::Move($temporary,$Path,$false)}else{[IO.File]::Move($temporary,$Path,$true)}}catch [IO.IOException]{throw 'BACKUP_SIGNER_AUTHORIZATION_REPLAY_REJECTED'}finally{if($stream){$stream.Dispose()};if(Test-Path -LiteralPath $temporary){Remove-Item -LiteralPath $temporary -Force}}
}
function Open-SignerReplay($Authorization,[string]$RequestSha256,[string]$ReceiptSha256){
  $root=Existing $SignerReplayLedgerRoot $true 'SIGNER_REPLAY_LEDGER_ROOT_REQUIRED';$recordId=HashText "$($Authorization.authorizationInstanceId)`n$RequestSha256";$record=Join-Path $root ($recordId+'.consumed');$active=Join-Path $root ($recordId+'.active')
  try{$stream=[IO.FileStream]::new($active,[IO.FileMode]::CreateNew,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None,4096,[IO.FileOptions]::DeleteOnClose)}catch [IO.IOException]{throw 'BACKUP_SIGNER_AUTHORIZATION_REPLAY_REJECTED'}
  $nonceHash=HashText ([string]$Authorization.authorizationNonce)
  try{
    if(Test-Path -LiteralPath $record){
      $value=ReadJson $record 'BACKUP_SIGNER_REPLAY_RECORD_INVALID';ExactKeys $value @('authorizationInstanceId','authorizationNonceSha256','authorizationType','committedAt','outcome','receiptSha256','requestSha256','reservedAt','state','version') 'BACKUP_SIGNER_REPLAY_RECORD_INVALID'
      if($value.version-ne2-or$value.authorizationType-cne$Authorization.attestationType-or$value.authorizationInstanceId-cne$Authorization.authorizationInstanceId-or$value.authorizationNonceSha256-cne$nonceHash-or$value.requestSha256-cne$RequestSha256-or$value.receiptSha256-cne$ReceiptSha256){throw 'BACKUP_SIGNER_REPLAY_BINDING_INVALID'}
      [void](Timestamp $value.reservedAt 'BACKUP_SIGNER_REPLAY_STATE_INVALID');if($value.state-notin@('RESERVED','COMMITTED')){throw 'BACKUP_SIGNER_REPLAY_STATE_INVALID'}
      if($value.state-eq'RESERVED'-and($null-ne$value.committedAt-or$null-ne$value.outcome)){throw 'BACKUP_SIGNER_REPLAY_RESERVATION_INVALID'}
      if($value.state-eq'COMMITTED'){[void](Timestamp $value.committedAt 'BACKUP_SIGNER_REPLAY_COMMIT_INVALID');if($value.outcome-notin@('PUBLISHED','IDEMPOTENT','SUPERSEDED')){throw 'BACKUP_SIGNER_REPLAY_COMMIT_INVALID'}}
    }
    else{$value=[ordered]@{version=2;state='RESERVED';authorizationType=[string]$Authorization.attestationType;authorizationInstanceId=[string]$Authorization.authorizationInstanceId;authorizationNonceSha256=$nonceHash;requestSha256=$RequestSha256;receiptSha256=$ReceiptSha256;reservedAt=(Get-Date).ToUniversalTime().ToString('o');committedAt=$null;outcome=$null};Write-AtomicReplayRecord $record $value $true}
    return [pscustomobject]@{Stream=$stream;Record=$record;Value=$value;Authorization=$Authorization;RequestSha256=$RequestSha256;ReceiptSha256=$ReceiptSha256}
  }catch{$stream.Dispose();throw}
}
function Complete-SignerReplay($Replay,[string]$Outcome){
  if($Outcome-notin@('PUBLISHED','IDEMPOTENT','SUPERSEDED')){throw 'BACKUP_SIGNER_REPLAY_OUTCOME_INVALID'};$reserved=Timestamp $Replay.Value.reservedAt 'BACKUP_SIGNER_REPLAY_STATE_INVALID';$reservedAt=$reserved.ToUniversalTime().ToString('o');$value=[ordered]@{version=2;state='COMMITTED';authorizationType=[string]$Replay.Authorization.attestationType;authorizationInstanceId=[string]$Replay.Authorization.authorizationInstanceId;authorizationNonceSha256=(HashText ([string]$Replay.Authorization.authorizationNonce));requestSha256=[string]$Replay.RequestSha256;receiptSha256=[string]$Replay.ReceiptSha256;reservedAt=$reservedAt;committedAt=(Get-Date).ToUniversalTime().ToString('o');outcome=$Outcome};Write-AtomicReplayRecord $Replay.Record $value $false
}
function Flush-PendingReceipt([string]$Path){$stream=[IO.File]::Open($Path,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::Read);try{$stream.Flush($true)}finally{$stream.Dispose()}}
function Publish-LatestReceipt([string]$Pending,[string]$Latest,[string]$CandidateSha256,$Candidate){
  if(Test-Path -LiteralPath $Latest){NoReparse $Latest;$currentSha=Hash $Latest;if($currentSha-ceq$CandidateSha256){return 'IDEMPOTENT'};$current=ReadJson $Latest 'BACKUP_RECEIPT_CURRENT_INVALID';$currentAt=Timestamp $current.completedAt 'BACKUP_RECEIPT_CURRENT_INVALID';$candidateAt=Timestamp $Candidate.completedAt 'BACKUP_RECEIPT_CURRENT_INVALID';if($current.result-ne'COMPLETE'-or$current.backupId-notmatch'^[0-9A-Za-z-]{20,80}$'){throw 'BACKUP_RECEIPT_CURRENT_INVALID'};if($currentAt-ge$candidateAt){return 'SUPERSEDED'}}
  [IO.File]::Move($Pending,$Latest,$true);return 'PUBLISHED'
}
function New-SignerAuthorizationPlan{
  if($AuthorizationMode-ne'OneTime'){throw 'ONE_TIME_SIGNER_AUTHORIZATION_PLAN_REQUIRED'}
  $p=[ordered]@{runtimeConfigPath=Get-ApprovalPath $RuntimeConfigPath 'BACKUP_AUTH_PLAN_RUNTIME_REQUIRED';runtimeConfigSha256=Get-ApprovalHash $ExpectedRuntimeConfigSha256 'BACKUP_AUTH_PLAN_RUNTIME_HASH_REQUIRED';filesystemEvidencePath=Get-ApprovalPath $FileSystemEvidencePath 'BACKUP_AUTH_PLAN_FILESYSTEM_REQUIRED';filesystemEvidenceSha256=Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'BACKUP_AUTH_PLAN_FILESYSTEM_HASH_REQUIRED';nodePath=Get-ApprovalPath $NodePath 'BACKUP_AUTH_PLAN_NODE_REQUIRED';nodeSha256=Get-ApprovalHash $ExpectedNodeSha256 'BACKUP_AUTH_PLAN_NODE_HASH_REQUIRED';semanticSignerPath=Get-ApprovalPath $SemanticSignerPath 'BACKUP_AUTH_PLAN_SEMANTIC_SIGNER_REQUIRED';semanticSignerSha256=Get-ApprovalHash $ExpectedSemanticSignerSha256 'BACKUP_AUTH_PLAN_SEMANTIC_SIGNER_HASH_REQUIRED';integrityKeyPath=Get-ApprovalPath $BackupIntegrityKeyFile 'BACKUP_AUTH_PLAN_INTEGRITY_KEY_REQUIRED';integrityKeySha256=Get-ApprovalHash $ExpectedBackupIntegrityKeySha256 'BACKUP_AUTH_PLAN_INTEGRITY_KEY_HASH_REQUIRED';receiptPrivateKeyPath=Get-ApprovalPath $BackupReceiptPrivateKeyPath 'BACKUP_AUTH_PLAN_RECEIPT_KEY_REQUIRED';receiptPrivateKeySha256=Get-ApprovalHash $ExpectedBackupReceiptPrivateKeySha256 'BACKUP_AUTH_PLAN_RECEIPT_KEY_HASH_REQUIRED';backupId=Get-ApprovalText $BackupId '^[0-9A-Za-z-]{20,80}$' 'BACKUP_AUTH_PLAN_BACKUP_ID_INVALID';requestSha256=Get-ApprovalHash $ExpectedReceiptRequestSha256 'BACKUP_AUTH_PLAN_REQUEST_HASH_REQUIRED';targetFingerprint=Get-ApprovalHash $ExpectedBackupTargetFingerprint 'BACKUP_AUTH_PLAN_TARGET_FINGERPRINT_REQUIRED';contractSha256=Get-ApprovalHash $ExpectedBackupContractSha256 'BACKUP_AUTH_PLAN_CONTRACT_HASH_REQUIRED';pgPassSha256=Get-ApprovalHash $ExpectedPgPassSha256 'BACKUP_AUTH_PLAN_PGPASS_HASH_REQUIRED';nasIdentityHelperSha256=Get-ApprovalHash $ExpectedNasIdentityHelperSha256 'BACKUP_AUTH_PLAN_NAS_HELPER_HASH_REQUIRED';signerAccount=$SignerAccount;authorizationPath=Get-ApprovalPath $SignerAuthorizationPath 'BACKUP_AUTH_PLAN_OUTPUT_REQUIRED';authorizationPrivateKeyPath=Get-ApprovalPath $SignerAuthorizationPrivateKeyPath 'BACKUP_AUTH_PLAN_PRIVATE_KEY_REQUIRED';authorizationPrivateKeySha256=Get-ApprovalHash $ExpectedSignerAuthorizationPrivateKeySha256 'BACKUP_AUTH_PLAN_PRIVATE_KEY_HASH_REQUIRED';authorizationPublicKeyPath=Get-ApprovalPath $SignerAuthorizationPublicKeyPath 'BACKUP_AUTH_PLAN_PUBLIC_KEY_REQUIRED';authorizationPublicKeySha256=Get-ApprovalHash $ExpectedSignerAuthorizationPublicKeySha256 'BACKUP_AUTH_PLAN_PUBLIC_KEY_HASH_REQUIRED';attestationSignerPath=Get-ApprovalPath $AttestationSignerPath 'BACKUP_AUTH_PLAN_SIGNER_REQUIRED';attestationSignerSha256=Get-ApprovalHash $ExpectedAttestationSignerSha256 'BACKUP_AUTH_PLAN_SIGNER_HASH_REQUIRED';attestationVerifierPath=Get-ApprovalPath $AttestationVerifierPath 'BACKUP_AUTH_PLAN_VERIFIER_REQUIRED';attestationVerifierSha256=Get-ApprovalHash $ExpectedAttestationVerifierSha256 'BACKUP_AUTH_PLAN_VERIFIER_HASH_REQUIRED'}
  return New-ApprovalPlan $PSCommandPath 'Authorize' $p 'Exact one-time semantic backup receipt authorization' 'Consumes one ADMIN_ONLY exact plan and issues one short-lived signed authorization for the non-admin receipt signer' 'Delete only the unused authorization; a consumed authorization remains replay-blocked and needs a new plan'
}

if($ReplayLedgerSelfTest){
  $testRoot=Join-Path ([IO.Path]::GetTempPath()) ('metaads-replay-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($testRoot)|Out-Null;$SignerReplayLedgerRoot=$testRoot
  try{
    $authorization=[pscustomobject]@{attestationType='backup-schedule-authorization';authorizationInstanceId=[guid]::NewGuid().ToString('D').ToLowerInvariant();authorizationNonce='a'*64};$requestSha='b'*64;$latest=Join-Path $testRoot 'latest.json';$candidate=[ordered]@{result='COMPLETE';backupId='20260831T010000Z-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';completedAt='2026-08-31T01:00:00.0000000Z'};$pending=Join-Path $testRoot 'candidate.json';[IO.File]::WriteAllText($pending,($candidate|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));$receiptSha=Hash $pending
    $reservation=Open-SignerReplay $authorization $requestSha $receiptSha;$reservation.Stream.Dispose();$reserved=ReadJson $reservation.Record 'SELF_TEST_RESERVED_MISSING';if($reserved.state-cne'RESERVED'){throw 'SELF_TEST_RESERVATION_NOT_DURABLE'}
    $recovered=Open-SignerReplay $authorization $requestSha $receiptSha;$outcome=Publish-LatestReceipt $pending $latest $receiptSha $candidate;if($outcome-cne'PUBLISHED'){throw 'SELF_TEST_PUBLISH_FAILED'};Complete-SignerReplay $recovered $outcome;$recovered.Stream.Dispose();$committed=ReadJson $recovered.Record 'SELF_TEST_COMMIT_MISSING';if($committed.state-cne'COMMITTED'-or$committed.outcome-cne'PUBLISHED'){throw 'SELF_TEST_COMMIT_FAILED'}
    $same=Join-Path $testRoot 'same.json';[IO.File]::WriteAllText($same,($candidate|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));$idempotent=Open-SignerReplay $authorization $requestSha (Hash $same);$sameOutcome=Publish-LatestReceipt $same $latest (Hash $same) $candidate;Complete-SignerReplay $idempotent $sameOutcome;$idempotent.Stream.Dispose();if($sameOutcome-cne'IDEMPOTENT'){throw 'SELF_TEST_IDEMPOTENT_RECOVERY_FAILED'}
    $olderAuthorization=[pscustomobject]@{attestationType='backup-schedule-authorization';authorizationInstanceId=[guid]::NewGuid().ToString('D').ToLowerInvariant();authorizationNonce='c'*64};$older=[ordered]@{result='COMPLETE';backupId='20260830T010000Z-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';completedAt='2026-08-30T01:00:00.0000000Z'};$olderPath=Join-Path $testRoot 'older.json';[IO.File]::WriteAllText($olderPath,($older|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));$olderSha=Hash $olderPath;$olderReplay=Open-SignerReplay $olderAuthorization ('d'*64) $olderSha;$olderOutcome=Publish-LatestReceipt $olderPath $latest $olderSha $older;Complete-SignerReplay $olderReplay $olderOutcome;$olderReplay.Stream.Dispose();if($olderOutcome-cne'SUPERSEDED'-or(Hash $latest)-cne$receiptSha){throw 'SELF_TEST_ROLLBACK_PREVENTION_FAILED'}
    [pscustomobject]@{result='PASS';durableReservation=$true;crashRecovery=$true;idempotentReplay=$true;rollbackPrevented=$true}|ConvertTo-Json -Compress;exit 0
  }finally{if(Test-Path -LiteralPath $testRoot){[IO.Directory]::Delete($testRoot,$true)}}
}

if($Action-eq'Plan'){New-SignerAuthorizationPlan|ConvertTo-Json -Depth 12;exit 0}
if($Action-eq'Authorize'){
  Assert-ApprovedPlan (New-SignerAuthorizationPlan) ([bool]$Approved) $ApprovedPlanSha256;$principal=[Security.Principal.WindowsPrincipal]::new([Security.Principal.WindowsIdentity]::GetCurrent());if(-not$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'BACKUP_AUTHORIZATION_ADMIN_REQUIRED'}
  $runtime=Pinned $RuntimeConfigPath $ExpectedRuntimeConfigSha256 'RUNTIME_CONFIG_HASH_MISMATCH';$fsPath=Pinned $FileSystemEvidencePath $ExpectedFileSystemEvidenceSha256 'FILESYSTEM_EVIDENCE_HASH_MISMATCH';$node=Pinned $NodePath $ExpectedNodeSha256 'NODE_HASH_MISMATCH';$semantic=Pinned $SemanticSignerPath $ExpectedSemanticSignerSha256 'SEMANTIC_SIGNER_HASH_MISMATCH';$integrity=Pinned $BackupIntegrityKeyFile $ExpectedBackupIntegrityKeySha256 'BACKUP_INTEGRITY_KEY_HASH_MISMATCH';$receiptPrivate=Pinned $BackupReceiptPrivateKeyPath $ExpectedBackupReceiptPrivateKeySha256 'BACKUP_RECEIPT_PRIVATE_KEY_HASH_MISMATCH';$authPrivate=Pinned $SignerAuthorizationPrivateKeyPath $ExpectedSignerAuthorizationPrivateKeySha256 'BACKUP_AUTHORIZATION_PRIVATE_KEY_HASH_MISMATCH';$authPublic=Pinned $SignerAuthorizationPublicKeyPath $ExpectedSignerAuthorizationPublicKeySha256 'BACKUP_AUTHORIZATION_PUBLIC_KEY_HASH_MISMATCH';$genericSigner=Pinned $AttestationSignerPath $ExpectedAttestationSignerSha256 'ATTESTATION_SIGNER_HASH_MISMATCH';$verifier=Pinned $AttestationVerifierPath $ExpectedAttestationVerifierSha256 'ATTESTATION_VERIFIER_HASH_MISMATCH'
  $config=ReadJson $runtime 'RUNTIME_CONFIG_INVALID';$fs=ReadJson $fsPath 'FILESYSTEM_EVIDENCE_INVALID';$expectedSignerSid=([Security.Principal.NTAccount]$SignerAccount).Translate([Security.Principal.SecurityIdentifier]).Value;if($fs.result-ne'PASS'-or-not$fs.exactAcl-or$fs.signerSid-cne$expectedSignerSid-or@(@($node,$semantic,$genericSigner,$verifier,$authPublic)|Where-Object{-not(Under $_ $fs.classRoots.SHARED_RUNTIME)}).Count-or-not(Under $integrity $fs.classRoots.BACKUP_ONLY)-or-not(Under $receiptPrivate $fs.classRoots.SIGNER_ONLY)-or-not(Under $authPrivate $fs.classRoots.ADMIN_ONLY)-or-not(Under $SignerAuthorizationPath $fs.classRoots.ADMIN_EVIDENCE)){throw 'BACKUP_AUTHORIZATION_FILESYSTEM_BOUNDARY_REJECTED'}
  $backupRoot=if($config.backup.root.StartsWith('\\')){$config.backup.root.TrimEnd('\')}else{[IO.Path]::GetFullPath([string]$config.backup.root)};$requestPath=Join-Path (Join-Path $backupRoot $BackupId) 'receipt-request.json';$request=Pinned $requestPath $ExpectedReceiptRequestSha256 'BACKUP_RECEIPT_REQUEST_HASH_MISMATCH';$requestValue=ReadJson $request 'BACKUP_RECEIPT_REQUEST_INVALID';Assert-Request $requestValue (Hash $PSCommandPath)
  if(Test-Path -LiteralPath $SignerAuthorizationPath){throw 'BACKUP_SIGNER_AUTHORIZATION_ALREADY_EXISTS'};$unsigned="$SignerAuthorizationPath.unsigned-$([guid]::NewGuid().ToString('N'))";try{$value=[ordered]@{attestationType='backup-signer-authorization';version=2;result='APPROVED';backupId=$BackupId;requestSha256=$ExpectedReceiptRequestSha256.ToLowerInvariant();backupContractSha256=$ExpectedBackupContractSha256.ToLowerInvariant();targetEvidenceFingerprint=$ExpectedBackupTargetFingerprint.ToLowerInvariant();pgPassSha256=$ExpectedPgPassSha256.ToLowerInvariant();nasIdentityHelperSha256=$ExpectedNasIdentityHelperSha256.ToLowerInvariant();backupIntegrityKeySha256=$ExpectedBackupIntegrityKeySha256.ToLowerInvariant();backupReceiptPrivateKeySha256=$ExpectedBackupReceiptPrivateKeySha256.ToLowerInvariant();receiptPublisherSha256=(Hash $PSCommandPath);semanticSignerSha256=$ExpectedSemanticSignerSha256.ToLowerInvariant();signerSid=$expectedSignerSid;authorizationNonce=$ApprovalNonce;authorizationInstanceId=$ApprovalInstanceId;authorizationIssuedAt=([datetimeoffset]::ParseExact($ApprovalIssuedAt,'o',[Globalization.CultureInfo]::InvariantCulture)).ToUniversalTime().ToString('o');authorizationExpiresAt=([datetimeoffset]::ParseExact($ApprovalExpiresAt,'o',[Globalization.CultureInfo]::InvariantCulture)).ToUniversalTime().ToString('o')};[IO.File]::WriteAllText($unsigned,($value|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));Pinned $genericSigner $ExpectedAttestationSignerSha256 'ATTESTATION_SIGNER_HASH_MISMATCH'|Out-Null;Pinned $authPrivate $ExpectedSignerAuthorizationPrivateKeySha256 'BACKUP_AUTHORIZATION_PRIVATE_KEY_HASH_MISMATCH'|Out-Null;Invoke-Bounded $node $ExpectedNodeSha256 @($genericSigner,$authPrivate,$unsigned,$SignerAuthorizationPath) 'BACKUP_SIGNER_AUTHORIZATION_SIGN_FAILED'|Out-Null;Pinned $verifier $ExpectedAttestationVerifierSha256 'ATTESTATION_VERIFIER_HASH_MISMATCH'|Out-Null;Invoke-Bounded $node $ExpectedNodeSha256 @($verifier,$authPublic,$SignerAuthorizationPath,'backup-signer-authorization') 'BACKUP_SIGNER_AUTHORIZATION_VERIFY_FAILED'|Out-Null}finally{Remove-Item -LiteralPath $unsigned -Force -ErrorAction SilentlyContinue}
  [pscustomobject]@{Result='AUTHORIZED';AuthorizationSha256=(Hash $SignerAuthorizationPath);ExpiresAt=$ApprovalExpiresAt;SignerSidDigest=(HashText $expectedSignerSid)}|ConvertTo-Json;exit 0
}

if($Approved-or$ApprovedPlanSha256-or$ApprovalLedgerPath){throw 'SIGNER_PUBLISH_MUST_NOT_USE_ADMIN_LEDGER'}
$runtime=Pinned $RuntimeConfigPath $ExpectedRuntimeConfigSha256 'RUNTIME_CONFIG_HASH_MISMATCH';$fsPath=Pinned $FileSystemEvidencePath $ExpectedFileSystemEvidenceSha256 'FILESYSTEM_EVIDENCE_HASH_MISMATCH';$node=Pinned $NodePath $ExpectedNodeSha256 'NODE_HASH_MISMATCH';$semantic=Pinned $SemanticSignerPath $ExpectedSemanticSignerSha256 'SEMANTIC_SIGNER_HASH_MISMATCH';$integrity=Pinned $BackupIntegrityKeyFile $ExpectedBackupIntegrityKeySha256 'BACKUP_INTEGRITY_KEY_HASH_MISMATCH';$private=Pinned $BackupReceiptPrivateKeyPath $ExpectedBackupReceiptPrivateKeySha256 'BACKUP_RECEIPT_PRIVATE_KEY_HASH_MISMATCH';$verifier=Pinned $AttestationVerifierPath $ExpectedAttestationVerifierSha256 'ATTESTATION_VERIFIER_HASH_MISMATCH';$scratchRoot=Existing $SignerScratchRoot $true 'SIGNER_SCRATCH_ROOT_REQUIRED';$replayRoot=Existing $SignerReplayLedgerRoot $true 'SIGNER_REPLAY_LEDGER_ROOT_REQUIRED'
$config=ReadJson $runtime 'RUNTIME_CONFIG_INVALID';$fs=ReadJson $fsPath 'FILESYSTEM_EVIDENCE_INVALID';$expectedSignerSid=([Security.Principal.NTAccount]$SignerAccount).Translate([Security.Principal.SecurityIdentifier]).Value;$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=[Security.Principal.WindowsPrincipal]::new($identity);if($identity.User.Value-cne$expectedSignerSid-or$fs.signerSid-cne$expectedSignerSid-or$fs.backupSid-ceq$expectedSignerSid-or$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'BACKUP_RECEIPT_SIGNER_IDENTITY_REJECTED'}
if($fs.result-ne'PASS'-or-not$fs.exactAcl-or@(@($node,$semantic,$verifier)|Where-Object{-not(Under $_ $fs.classRoots.SHARED_RUNTIME)}).Count-or-not(Under $integrity $fs.classRoots.BACKUP_ONLY)-or-not(Under $private $fs.classRoots.SIGNER_ONLY)-or-not(Under $scratchRoot $fs.classRoots.SIGNER_STATE)-or-not(Under $replayRoot $fs.classRoots.SIGNER_STATE)){throw 'BACKUP_RECEIPT_FILESYSTEM_BOUNDARY_REJECTED'}
$backupRoot=if($config.backup.root.StartsWith('\\')){$config.backup.root.TrimEnd('\')}else{[IO.Path]::GetFullPath([string]$config.backup.root)};$artifactRoot=Existing (Join-Path $backupRoot $BackupId) $true 'BACKUP_ARTIFACT_ROOT_INVALID';$requestPath=Join-Path $artifactRoot 'receipt-request.json';$immutable=Join-Path $scratchRoot ("$([guid]::NewGuid().ToString('N'))-$($ExpectedReceiptRequestSha256.ToLowerInvariant()).json");$pending=$null;$artifactGuards=Open-ArtifactGuards $artifactRoot;$replay=$null
try{
  Copy-PinnedRequest $requestPath $immutable $ExpectedReceiptRequestSha256|Out-Null;$requestValue=ReadJson $immutable 'BACKUP_RECEIPT_REQUEST_INVALID';Assert-Request $requestValue (Hash $PSCommandPath);$authorization=Get-Authorization $requestValue $fs $expectedSignerSid
  Pinned $semantic $ExpectedSemanticSignerSha256 'SEMANTIC_SIGNER_HASH_MISMATCH'|Out-Null;Pinned $private $ExpectedBackupReceiptPrivateKeySha256 'BACKUP_RECEIPT_PRIVATE_KEY_HASH_MISMATCH'|Out-Null;Pinned $integrity $ExpectedBackupIntegrityKeySha256 'BACKUP_INTEGRITY_KEY_HASH_MISMATCH'|Out-Null;$latest=[IO.Path]::GetFullPath([string]$config.backup.latestBackupEvidencePath);if(-not(Under $latest $fs.classRoots.BACKUP_RECEIPT)){throw 'BACKUP_RECEIPT_OUTPUT_CLASS_REJECTED'};$pending=Join-Path (Split-Path -Parent $latest) ('.receipt-'+[guid]::NewGuid().ToString('N')+'.pending');Invoke-Bounded $node $ExpectedNodeSha256 @($semantic,$private,$ExpectedBackupReceiptPrivateKeySha256.ToLowerInvariant(),$integrity,$ExpectedBackupIntegrityKeySha256.ToLowerInvariant(),$immutable,$ExpectedReceiptRequestSha256.ToLowerInvariant(),[string]$authorization.signingKeyId,$pending) 'BACKUP_RECEIPT_SIGNER_FAILED'|Out-Null
  $receipt=ReadJson $pending 'BACKUP_RECEIPT_OUTPUT_INVALID';if($receipt.attestationType-cne'backup-latest'-or$receipt.version-ne6-or$receipt.result-cne'COMPLETE'-or$receipt.backupId-cne$BackupId-or$receipt.manifestSha256-cne$requestValue.manifestSha256-or$receipt.backupContractSha256-cne$requestValue.backupContractSha256-or$receipt.backupIntegrityKeySha256-cne$requestValue.backupIntegrityKeySha256-or$receipt.backupReceiptPrivateKeySha256-cne$requestValue.backupReceiptPrivateKeySha256-or$receipt.authorizationSigningKeyId-cne$authorization.signingKeyId-or$receipt.signingKeyId-ceq$authorization.signingKeyId-or$receipt.attestationSignature-notmatch'^[A-Za-z0-9_-]{80,128}$'){throw 'BACKUP_RECEIPT_OUTPUT_BINDING_REJECTED'}
  Flush-PendingReceipt $pending;$receiptSha=Hash $pending;$replay=Open-SignerReplay $authorization $ExpectedReceiptRequestSha256.ToLowerInvariant() $receiptSha
  $guard=Open-PinnedGuard $requestPath $ExpectedReceiptRequestSha256;try{$publishOutcome=Publish-LatestReceipt $pending $latest $receiptSha $receipt;if($publishOutcome-eq'PUBLISHED'){$pending=$null};Complete-SignerReplay $replay $publishOutcome}finally{$guard.Stream.Dispose()}
  [pscustomobject]@{Result='PUBLISHED';BackupId=$BackupId;IndependentSigner=$true;AuthorizationMode=$AuthorizationMode;ReplayProtected=$true;ReplayState='COMMITTED';PublishOutcome=$publishOutcome;CrashRecoveryIdempotent=$true;RollbackPrevented=$true;ImmutableRequestVerified=$true;ArtifactReadLocksHeld=$true;HardlinksRejectedBySemanticSigner=$true}|ConvertTo-Json
}finally{if($replay){$replay.Stream.Dispose()};foreach($stream in $artifactGuards){$stream.Dispose()};if($pending-and(Test-Path -LiteralPath $pending)){Remove-Item -LiteralPath $pending -Force};if(Test-Path -LiteralPath $immutable){Remove-Item -LiteralPath $immutable -Force}}
