#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Publish','Verify','Rollback')][string]$Action='Plan',
  [string]$ScratchEvidencePath,[string]$ExpectedScratchEvidenceSha256,
  [string]$PublishedEvidencePath,[string]$ExpectedPublishedEvidenceSha256,[string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,
  [string]$NodePath,[string]$ExpectedNodeSha256,[string]$AttestationVerifierPath,[string]$ExpectedAttestationVerifierSha256,
  [string]$RestoreReceiptPublicKeyPath,[string]$ExpectedRestoreReceiptPublicKeySha256,
  [ValidateSet('Publish','Rollback')][string]$PlannedAction,[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
function Existing([string]$Path,[string]$Code){if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw $Code};$full=[IO.Path]::GetFullPath($Path);$cursor=Get-Item -LiteralPath $full -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'RESTORE_PUBLICATION_REPARSE_REJECTED'};$cursor=$cursor.Parent};return $full}
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Under([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path);return @($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function Assert-Pinned([string]$Path,[string]$Expected,[string]$Code){$null=Existing $Path $Code;if($Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $Path)-cne$Expected.ToLowerInvariant()){throw $Code}}
function Verify-Signed([string]$Path){Assert-Pinned $node $ExpectedNodeSha256 'NODE_HASH_MISMATCH';Assert-Pinned $verifier $ExpectedAttestationVerifierSha256 'ATTESTATION_VERIFIER_HASH_MISMATCH';&$node $verifier $publicKey $Path 'restore-verification' 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw 'RESTORE_EVIDENCE_SIGNATURE_REJECTED'};$value=Get-Content -Raw -LiteralPath $Path|ConvertFrom-Json;if($value.version-ne6-or$value.result-ne'PASS'-or$value.nodeSha256-notmatch'^[a-f0-9]{64}$'-or$value.psqlSha256-notmatch'^[a-f0-9]{64}$'-or$value.pgRestoreSha256-notmatch'^[a-f0-9]{64}$'-or$value.restoreExecutorSetDigest-notmatch'^[a-f0-9]{64}$'-or-not$value.isolatedDatabasePristineBeforeRestore-or-not$value.eventTriggersAbsentBeforeRestore-or-not$value.isolatedDatabaseSchemaCleaned-or-not$value.isolatedStorageRootCleaned-or-not$value.fullCatalogCleanupVerified-or-not$value.verifiedInputSnapshot-or-not$value.boundedManifestCopy-or-not$value.isolatedApiConfigsBound-or$value.productionDatabaseMutated){throw 'RESTORE_EVIDENCE_CONTENT_REJECTED'};return $value}
function New-PublishRestoreApprovalPlan([string]$IntendedAction){if($IntendedAction-notin@('Publish','Rollback')){throw 'RESTORE_PUBLICATION_PLAN_ACTION_REQUIRED'};$p=[ordered]@{publishedEvidencePath=Get-ApprovalPath $PublishedEvidencePath 'RESTORE_PUBLICATION_PLAN_PUBLISHED_PATH_REQUIRED';filesystemEvidencePath=Get-ApprovalPath $FileSystemEvidencePath 'RESTORE_PUBLICATION_PLAN_FS_PATH_REQUIRED';filesystemEvidenceSha256=Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'RESTORE_PUBLICATION_PLAN_FS_HASH_REQUIRED';nodePath=Get-ApprovalPath $NodePath 'RESTORE_PUBLICATION_PLAN_NODE_PATH_REQUIRED';nodeSha256=Get-ApprovalHash $ExpectedNodeSha256 'RESTORE_PUBLICATION_PLAN_NODE_HASH_REQUIRED';attestationVerifierPath=Get-ApprovalPath $AttestationVerifierPath 'RESTORE_PUBLICATION_PLAN_VERIFIER_PATH_REQUIRED';attestationVerifierSha256=Get-ApprovalHash $ExpectedAttestationVerifierSha256 'RESTORE_PUBLICATION_PLAN_VERIFIER_HASH_REQUIRED';receiptPublicKeyPath=Get-ApprovalPath $RestoreReceiptPublicKeyPath 'RESTORE_PUBLICATION_PLAN_PUBLIC_KEY_REQUIRED';receiptPublicKeySha256=Get-ApprovalHash $ExpectedRestoreReceiptPublicKeySha256 'RESTORE_PUBLICATION_PLAN_PUBLIC_KEY_HASH_REQUIRED'};if($IntendedAction-eq'Publish'){$p.scratchEvidencePath=Get-ApprovalPath $ScratchEvidencePath 'RESTORE_PUBLICATION_PLAN_SCRATCH_PATH_REQUIRED';$p.scratchEvidenceSha256=Get-ApprovalHash $ExpectedScratchEvidenceSha256 'RESTORE_PUBLICATION_PLAN_SCRATCH_HASH_REQUIRED'}else{$p.publishedEvidenceSha256=Get-ApprovalHash $ExpectedPublishedEvidenceSha256 'RESTORE_PUBLICATION_PLAN_PUBLISHED_HASH_REQUIRED'};$impact=if($IntendedAction-eq'Publish'){'Verifies the exact signed scratch receipt, publishes it to ADMIN_EVIDENCE, and removes only the exact scratch receipt'}else{'Removes only the exact hash-pinned published receipt'};New-ApprovalPlan $PSCommandPath $IntendedAction $p 'Exact signed restore receipt and ADMIN_EVIDENCE publication path' $impact 'Publish rollback removes only the exact receipt; rollback recovery requires a new approved Publish plan'}
if($Action-eq'Plan'){New-PublishRestoreApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0};if($Action-in@('Publish','Rollback')){$approvalPlan=New-PublishRestoreApprovalPlan $Action;Assert-ApprovedPlan $approvalPlan ([bool]$Approved) $ApprovedPlanSha256}
$node=Existing $NodePath 'NODE_NOT_FOUND';$verifier=Existing $AttestationVerifierPath 'ATTESTATION_VERIFIER_NOT_FOUND';$publicKey=Existing $RestoreReceiptPublicKeyPath 'RESTORE_PUBLIC_KEY_NOT_FOUND';$filesystemPath=Existing $FileSystemEvidencePath 'FILESYSTEM_EVIDENCE_NOT_FOUND'
Assert-Pinned $node $ExpectedNodeSha256 'NODE_HASH_MISMATCH';Assert-Pinned $verifier $ExpectedAttestationVerifierSha256 'ATTESTATION_VERIFIER_HASH_MISMATCH';Assert-Pinned $publicKey $ExpectedRestoreReceiptPublicKeySha256 'RESTORE_PUBLIC_KEY_HASH_MISMATCH';Assert-Pinned $filesystemPath $ExpectedFileSystemEvidenceSha256 'FILESYSTEM_EVIDENCE_HASH_MISMATCH'
$filesystem=Get-Content -Raw -LiteralPath $filesystemPath|ConvertFrom-Json;if($filesystem.result-ne'PASS'-or-not$filesystem.exactAcl-or-not(Under $node $filesystem.classRoots.SHARED_RUNTIME)-or-not(Under $verifier $filesystem.classRoots.SHARED_RUNTIME)-or-not(Under $publicKey $filesystem.classRoots.SHARED_RUNTIME)-or-not(Under $PublishedEvidencePath $filesystem.classRoots.ADMIN_EVIDENCE)){throw 'RESTORE_PUBLICATION_FILESYSTEM_REJECTED'}
$published=[IO.Path]::GetFullPath($PublishedEvidencePath)
if($Action-eq'Rollback'){Assert-Pinned $published $ExpectedPublishedEvidenceSha256 'PUBLISHED_RESTORE_EVIDENCE_HASH_MISMATCH';Remove-Item -LiteralPath $published -Force;if(Test-Path -LiteralPath $published){throw 'RESTORE_PUBLICATION_ROLLBACK_FAILED'};[pscustomobject]@{Result='ROLLED_BACK';DatabaseChanged=$false;PayloadChanged=$false}|ConvertTo-Json;exit 0}
if($Action-eq'Verify'){$file=Existing $published 'PUBLISHED_RESTORE_EVIDENCE_NOT_FOUND';$value=Verify-Signed $file;[pscustomobject]@{Result='PASS';BackupId=$value.backupId;PublishedEvidenceSha256=Hash $file}|ConvertTo-Json;exit 0}
$source=Existing $ScratchEvidencePath 'SCRATCH_RESTORE_EVIDENCE_NOT_FOUND'
if($ExpectedScratchEvidenceSha256-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $source)-cne$ExpectedScratchEvidenceSha256.ToLowerInvariant()){throw 'SCRATCH_RESTORE_EVIDENCE_HASH_MISMATCH'}
$evidence=Verify-Signed $source;$scratchRoot=[IO.Path]::GetFullPath((Join-Path ([string]$evidence.verifiedTargetDataRoot) 'restore-verification')).TrimEnd('\')
if(-not(Under $source @($scratchRoot))){throw 'RESTORE_EVIDENCE_NOT_FROM_VERIFIER_SCRATCH'}
if(Test-Path -LiteralPath $published){throw 'PUBLISHED_RESTORE_EVIDENCE_ALREADY_EXISTS'}
$pending="$published.pending";if(Test-Path -LiteralPath $pending){throw 'RESTORE_PUBLICATION_PENDING_EXISTS'};Copy-Item -LiteralPath $source -Destination $pending
if((Hash $pending)-cne$ExpectedScratchEvidenceSha256.ToLowerInvariant()){Remove-Item -LiteralPath $pending -Force;throw 'RESTORE_PUBLICATION_COPY_HASH_MISMATCH'}
Move-Item -LiteralPath $pending -Destination $published
Remove-Item -LiteralPath $source -Force
if(Test-Path -LiteralPath $source){throw 'RESTORE_SCRATCH_RECEIPT_CLEANUP_FAILED'}
[pscustomobject]@{Result='PUBLISHED';BackupId=$evidence.backupId;PublishedEvidenceSha256=Hash $published;ScratchReceiptRemoved=$true;DatabaseChanged=$false;PayloadChanged=$false}|ConvertTo-Json
