#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Publish')][string]$Action='Plan',[string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,
  [string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,[string]$NodePath,[string]$ExpectedNodeSha256,
  [string]$SemanticSignerPath,[string]$ExpectedSemanticSignerSha256,[string]$BackupIntegrityKeyFile,[string]$BackupReceiptPrivateKeyPath,
  [string]$BackupId,[string]$ExpectedReceiptRequestSha256,[string]$ExpectedBackupTargetFingerprint,[string]$SignerAccount,
  [ValidateSet('Publish')][string]$PlannedAction,[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved
)
$ErrorActionPreference='Stop';. (Join-Path $PSScriptRoot 'approval-plan.ps1')
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Existing([string]$Path,[string]$Code){if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw $Code};$full=[IO.Path]::GetFullPath($Path);$cursor=Get-Item -LiteralPath $full -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'BACKUP_RECEIPT_REPARSE_REJECTED'};$cursor=$cursor.Parent};return $full}
function Under([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path);return @($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function Pinned([string]$Path,[string]$Expected,[string]$Code){$full=Existing $Path $Code;if($Expected-notmatch'^[a-fA-F0-9]{64}$'-or(Hash $full)-cne$Expected.ToLowerInvariant()){throw $Code};return $full}
function New-PublishBackupReceiptPlan {
  $parameters=[ordered]@{runtimeConfigPath=(Get-ApprovalPath $RuntimeConfigPath 'BACKUP_RECEIPT_PLAN_RUNTIME_REQUIRED');runtimeConfigSha256=(Get-ApprovalHash $ExpectedRuntimeConfigSha256 'BACKUP_RECEIPT_PLAN_RUNTIME_HASH_REQUIRED');filesystemEvidencePath=(Get-ApprovalPath $FileSystemEvidencePath 'BACKUP_RECEIPT_PLAN_FILESYSTEM_REQUIRED');filesystemEvidenceSha256=(Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'BACKUP_RECEIPT_PLAN_FILESYSTEM_HASH_REQUIRED');nodePath=(Get-ApprovalPath $NodePath 'BACKUP_RECEIPT_PLAN_NODE_REQUIRED');nodeSha256=(Get-ApprovalHash $ExpectedNodeSha256 'BACKUP_RECEIPT_PLAN_NODE_HASH_REQUIRED');semanticSignerPath=(Get-ApprovalPath $SemanticSignerPath 'BACKUP_RECEIPT_PLAN_SIGNER_REQUIRED');semanticSignerSha256=(Get-ApprovalHash $ExpectedSemanticSignerSha256 'BACKUP_RECEIPT_PLAN_SIGNER_HASH_REQUIRED');backupIntegrityKeyPath=(Get-ApprovalPath $BackupIntegrityKeyFile 'BACKUP_RECEIPT_PLAN_INTEGRITY_KEY_REQUIRED');receiptPrivateKeyPath=(Get-ApprovalPath $BackupReceiptPrivateKeyPath 'BACKUP_RECEIPT_PLAN_PRIVATE_KEY_REQUIRED');backupId=(Get-ApprovalText $BackupId '^[0-9A-Za-z-]{20,80}$' 'BACKUP_RECEIPT_PLAN_BACKUP_ID_INVALID');receiptRequestSha256=(Get-ApprovalHash $ExpectedReceiptRequestSha256 'BACKUP_RECEIPT_PLAN_REQUEST_HASH_REQUIRED');targetFingerprint=(Get-ApprovalHash $ExpectedBackupTargetFingerprint 'BACKUP_RECEIPT_PLAN_TARGET_FINGERPRINT_REQUIRED');signerAccount=$SignerAccount}
  return New-ApprovalPlan $PSCommandPath 'Publish' $parameters 'Exact latest-backup receipt for one immutable backup artifact set' 'A distinct signer identity independently verifies manifest, HMAC, database dump, and every storage object before publishing one receipt' 'Delete only the newly published receipt; backup payload remains immutable'
}
if($Action-eq'Plan'){New-PublishBackupReceiptPlan|ConvertTo-Json -Depth 12;exit 0}
Assert-ApprovedPlan (New-PublishBackupReceiptPlan) ([bool]$Approved) $ApprovedPlanSha256
$runtime=Pinned $RuntimeConfigPath $ExpectedRuntimeConfigSha256 'RUNTIME_CONFIG_HASH_MISMATCH';$fsPath=Pinned $FileSystemEvidencePath $ExpectedFileSystemEvidenceSha256 'FILESYSTEM_EVIDENCE_HASH_MISMATCH';$node=Pinned $NodePath $ExpectedNodeSha256 'NODE_HASH_MISMATCH';$signer=Pinned $SemanticSignerPath $ExpectedSemanticSignerSha256 'SEMANTIC_SIGNER_HASH_MISMATCH';$integrity=Existing $BackupIntegrityKeyFile 'BACKUP_INTEGRITY_KEY_REQUIRED';$private=Existing $BackupReceiptPrivateKeyPath 'BACKUP_RECEIPT_PRIVATE_KEY_REQUIRED'
$config=Get-Content -Raw -LiteralPath $runtime|ConvertFrom-Json;$fs=Get-Content -Raw -LiteralPath $fsPath|ConvertFrom-Json
if($fs.result-ne'PASS'-or-not$fs.exactAcl-or-not$fs.signerSid-or-not(Under $node $fs.classRoots.SHARED_RUNTIME)-or-not(Under $signer $fs.classRoots.SHARED_RUNTIME)-or-not(Under $integrity $fs.classRoots.BACKUP_ONLY)-or-not(Under $private $fs.classRoots.SIGNER_ONLY)){throw 'BACKUP_RECEIPT_FILESYSTEM_BOUNDARY_REJECTED'}
$expectedSignerSid=([Security.Principal.NTAccount]$SignerAccount).Translate([Security.Principal.SecurityIdentifier]).Value;$currentSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;if($expectedSignerSid-cne$fs.signerSid-or$currentSid-cne$expectedSignerSid-or$fs.backupSid-ceq$expectedSignerSid){throw 'BACKUP_RECEIPT_SIGNER_IDENTITY_REJECTED'}
$backupRoot=if($config.backup.root.StartsWith('\\')){$config.backup.root.TrimEnd('\')}else{[IO.Path]::GetFullPath([string]$config.backup.root)};$artifactRoot=Join-Path $backupRoot $BackupId;$request=Pinned (Join-Path $artifactRoot 'receipt-request.json') $ExpectedReceiptRequestSha256 'BACKUP_RECEIPT_REQUEST_HASH_MISMATCH';$requestValue=Get-Content -Raw -LiteralPath $request|ConvertFrom-Json
if($requestValue.backupId-cne$BackupId-or$requestValue.backupRoot-cne$backupRoot-or$requestValue.targetEvidenceFingerprint-cne$ExpectedBackupTargetFingerprint.ToLowerInvariant()){throw 'BACKUP_RECEIPT_REQUEST_BINDING_REJECTED'}
$latest=[IO.Path]::GetFullPath([string]$config.backup.latestBackupEvidencePath);if(-not(Under $latest $fs.classRoots.BACKUP_RECEIPT)){throw 'BACKUP_RECEIPT_OUTPUT_CLASS_REJECTED'};$pending=Join-Path (Split-Path -Parent $latest) ('.receipt-'+[guid]::NewGuid().ToString('N')+'.pending')
$info=[Diagnostics.ProcessStartInfo]::new();$info.FileName=$node;$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true;foreach($argument in @($signer,$private,$integrity,$request,$pending)){$info.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::new();$process.StartInfo=$info
try{if(-not$process.Start()){throw 'BACKUP_RECEIPT_SIGNER_START_FAILED'};if(-not$process.WaitForExit(300000)){$process.Kill($true);throw 'BACKUP_RECEIPT_SIGNER_TIMEOUT'};$stdout=$process.StandardOutput.ReadToEnd();$stderr=$process.StandardError.ReadToEnd();if($stdout.Length+$stderr.Length-gt1048576-or$process.ExitCode-ne0){throw 'BACKUP_RECEIPT_SIGNER_FAILED'};if(-not(Test-Path -LiteralPath $pending -PathType Leaf)){throw 'BACKUP_RECEIPT_SIGNER_FAILED'};[IO.File]::Move($pending,$latest,$true)}finally{if(-not$process.HasExited){$process.Kill($true)};$process.Dispose();if(Test-Path -LiteralPath $pending){Remove-Item -LiteralPath $pending -Force}}
[pscustomobject]@{Result='PUBLISHED';BackupId=$BackupId;IndependentSigner=$true}|ConvertTo-Json
