#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Stage','Verify','Rollback')][string]$Action='Plan',
  [string]$LegacyBaselineEvidencePath,[string]$ExpectedLegacyBaselineEvidenceSha256,
  [string]$TargetDataRoot,[string]$FileSystemEvidencePath,[string]$ExpectedFileSystemEvidenceSha256,
  [string]$EvidenceOutputPath,[string]$ExpectedEvidenceSha256,
  [ValidateSet('Stage','Rollback')][string]$PlannedAction,[string]$ApprovedPlanSha256,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
function Existing([string]$Path,[bool]$Directory,[string]$Code){$kind=if($Directory){'Container'}else{'Leaf'};if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType $kind)){throw$Code};$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');$cursor=Get-Item -LiteralPath $full -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw'LEGACY_STAGE_REPARSE_REJECTED'};$cursor=$cursor.Parent};return$full}
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function TextHash([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function Under([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');return@($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function Inventory([string]$Root){$rootFull=Existing $Root $true 'LEGACY_STAGE_STORAGE_ROOT_NOT_FOUND';$prefix=$rootFull+'\';$lines=New-Object 'System.Collections.Generic.List[string]';[long]$bytes=0;foreach($file in @(Get-ChildItem -LiteralPath $rootFull -File -Recurse -Force|Sort-Object FullName)){if(($file.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0-or-not$file.FullName.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw'LEGACY_STAGE_STORAGE_INVENTORY_REJECTED'};$key=$file.FullName.Substring($prefix.Length).Replace('\','/');if(-not$key-or$key.Length-gt1024-or$key-match'(^|/)\.\.?(/|$)'-or$key-match'[\x00-\x1f\x7f]'){throw'LEGACY_STAGE_STORAGE_KEY_REJECTED'};$bytes+=[long]$file.Length;if($lines.Count-ge1000000-or$bytes-gt1099511627776-or$file.Length-gt536870912){throw'LEGACY_STAGE_STORAGE_LIMIT_EXCEEDED'};$lines.Add("$key|$($file.Length)|$(Hash $file.FullName)")};return[pscustomobject]@{Digest=(TextHash ($lines-join"`n"));FileCount=$lines.Count;TotalBytes=$bytes}}
function CopyDomain([string]$Source,[string]$Destination){New-Item -ItemType Directory -Path $Destination -Force|Out-Null;$prefix=$Source.TrimEnd('\')+'\';foreach($file in @(Get-ChildItem -LiteralPath $Source -File -Recurse -Force|Sort-Object FullName)){$relative=$file.FullName.Substring($prefix.Length);$target=[IO.Path]::GetFullPath((Join-Path $Destination $relative));if(-not$target.StartsWith($Destination.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)){throw'LEGACY_STAGE_TARGET_ESCAPE'};$parent=Split-Path -Parent $target;New-Item -ItemType Directory -Path $parent -Force|Out-Null;$before=Hash $file.FullName;$length=$file.Length;Copy-Item -LiteralPath $file.FullName -Destination $target;if((Hash $target)-cne$before-or(Hash $file.FullName)-cne$before-or(Get-Item -LiteralPath $target).Length-ne$length-or(Get-Item -LiteralPath $file.FullName).Length-ne$length){throw'LEGACY_STAGE_COPY_HASH_MISMATCH'}}}
function ValidateBaseline($Value){if($Value.version-ne3-or-not$Value.launchIdentityMatchesProtectedRestartSpec-or-not$Value.legacyIdentityHealthSmokeVerified-or$Value.result-cne'PASS'-or$Value.proofType-cne'legacy-running-baseline'-or$Value.legacyStorageProvider-cne'repository_local_ntfs'-or$Value.localReleaseManifestApplicable-or-not$Value.referenceConversionRequired-or$Value.storageInventoryDigest-notmatch'^[0-9a-f]{64}$'){throw'LEGACY_STAGE_BASELINE_INVALID'}}
function New-LegacyStorageStageApprovalPlan([string]$IntendedAction){
  if($IntendedAction-notin@('Stage','Rollback')){throw'PLANNED_ACTION_REQUIRED'}
  $parameters=[ordered]@{legacyBaselineEvidencePath=(Get-ApprovalPath $LegacyBaselineEvidencePath 'LEGACY_STAGE_PLAN_BASELINE_PATH_REQUIRED');legacyBaselineEvidenceSha256=(Get-ApprovalHash $ExpectedLegacyBaselineEvidenceSha256 'LEGACY_STAGE_PLAN_BASELINE_HASH_REQUIRED');targetDataRoot=(Get-ApprovalPath $TargetDataRoot 'LEGACY_STAGE_PLAN_DATA_ROOT_REQUIRED');filesystemEvidencePath=(Get-ApprovalPath $FileSystemEvidencePath 'LEGACY_STAGE_PLAN_FILESYSTEM_PATH_REQUIRED');filesystemEvidenceSha256=(Get-ApprovalHash $ExpectedFileSystemEvidenceSha256 'LEGACY_STAGE_PLAN_FILESYSTEM_HASH_REQUIRED');evidenceOutputPath=(Get-ApprovalPath $EvidenceOutputPath 'LEGACY_STAGE_PLAN_EVIDENCE_PATH_REQUIRED')}
  if($IntendedAction-eq'Rollback'){$parameters.stageEvidenceSha256=Get-ApprovalHash $ExpectedEvidenceSha256 'LEGACY_STAGE_PLAN_EVIDENCE_HASH_REQUIRED'}
  $target="Exact target storage roots under $($parameters.targetDataRoot) bound to baseline $($parameters.legacyBaselineEvidenceSha256)"
  $impact=if($IntendedAction-eq'Stage'){'After legacy quiesce, copies only repository-local uploads/reports to the configured target and verifies every source/destination byte hash; no cloud Storage call'}else{'After exact evidence/inventory verification, removes only the two staged target roots; source and DB remain unchanged'}
  $rollback=if($IntendedAction-eq'Stage'){'Use a separately approved Rollback plan bound to the exact stage evidence hash'}else{'Re-stage only through a new approved Stage plan'}
  return New-ApprovalPlan $PSCommandPath $IntendedAction $parameters $target $impact $rollback
}

if($Action-eq'Plan'){New-LegacyStorageStageApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0}
$legacyStageMutation=if($Action-in@('Stage','Rollback')){$Action}else{$null};if($legacyStageMutation){Assert-ApprovedPlan (New-LegacyStorageStageApprovalPlan $legacyStageMutation) ([bool]$Approved) $ApprovedPlanSha256}

$baselinePath=Existing $LegacyBaselineEvidencePath $false 'LEGACY_BASELINE_NOT_FOUND';$fsPath=Existing $FileSystemEvidencePath $false 'FILESYSTEM_EVIDENCE_NOT_FOUND';foreach($entry in @(@{Path=$baselinePath;Expected=$ExpectedLegacyBaselineEvidenceSha256;Code='LEGACY_BASELINE_HASH_MISMATCH'},@{Path=$fsPath;Expected=$ExpectedFileSystemEvidenceSha256;Code='FILESYSTEM_EVIDENCE_HASH_MISMATCH'})){if($entry.Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $entry.Path)-cne$entry.Expected.ToLowerInvariant()){throw$entry.Code}}
$baseline=Get-Content -Raw -LiteralPath $baselinePath|ConvertFrom-Json;ValidateBaseline $baseline;$sourceUploads=Existing ([string]$baseline.legacyUploadsRoot) $true 'LEGACY_UPLOADS_ROOT_NOT_FOUND';$sourceReports=Existing ([string]$baseline.legacyReportsRoot) $true 'LEGACY_REPORTS_ROOT_NOT_FOUND'
if($Action-in@('Stage','Verify')-and((Get-Process -Id ([int]$baseline.webProcessId),([int]$baseline.apiProcessId) -ErrorAction SilentlyContinue)-or@(Get-NetTCPConnection -State Listen -LocalPort 3100,4100 -ErrorAction SilentlyContinue).Count)){throw'LEGACY_STAGE_REQUIRES_QUIESCED_PROCESSES'}
$dataRoot=Existing $TargetDataRoot $true 'TARGET_DATA_ROOT_NOT_FOUND';$fs=Get-Content -Raw -LiteralPath $fsPath|ConvertFrom-Json;if($fs.result-ne'PASS'-or-not$fs.exactAcl-or[IO.Path]::GetFullPath([string]$fs.dataRoot).TrimEnd('\')-ine$dataRoot-or-not(Under $baselinePath $fs.classRoots.ADMIN_EVIDENCE)-or-not(Under $EvidenceOutputPath $fs.classRoots.ADMIN_EVIDENCE)){throw'LEGACY_STAGE_FILESYSTEM_BOUNDARY_REJECTED'}
$targetStorage=Join-Path $dataRoot 'storage';$targetUploads=Join-Path $targetStorage 'uploads';$targetReports=Join-Path $targetStorage 'reports'
$sourceUploadInventory=Inventory $sourceUploads;$sourceReportInventory=Inventory $sourceReports;$combined=TextHash (@("uploads=$($sourceUploadInventory.Digest)","reports=$($sourceReportInventory.Digest)")-join"`n");if($combined-cne$baseline.storageInventoryDigest-or$sourceUploadInventory.Digest-cne$baseline.uploadsInventoryDigest-or$sourceReportInventory.Digest-cne$baseline.reportsInventoryDigest){throw'LEGACY_STORAGE_CHANGED_SINCE_BASELINE'}
if($Action-eq'Rollback'){
  $evidence=Existing $EvidenceOutputPath $false 'LEGACY_STAGE_EVIDENCE_NOT_FOUND';if($ExpectedEvidenceSha256-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $evidence)-cne$ExpectedEvidenceSha256.ToLowerInvariant()){throw'LEGACY_STAGE_EVIDENCE_HASH_MISMATCH'};$value=Get-Content -Raw -LiteralPath $evidence|ConvertFrom-Json
  if($value.version-ne1-or$value.result-cne'PASS'-or$value.baselineSha256-cne(Hash $baselinePath)-or[IO.Path]::GetFullPath([string]$value.targetDataRoot).TrimEnd('\')-ine$dataRoot){throw'LEGACY_STAGE_EVIDENCE_INVALID'}
  if((Inventory $targetUploads).Digest-cne$value.uploadsInventoryDigest-or(Inventory $targetReports).Digest-cne$value.reportsInventoryDigest){throw'LEGACY_STAGE_TARGET_CHANGED'}
  foreach($root in @($targetUploads,$targetReports)){Remove-Item -LiteralPath $root -Recurse -Force};[pscustomobject]@{Result='ROLLED_BACK';DatabaseChanged=$false;SourceChanged=$false}|ConvertTo-Json;exit 0
}
if($Action-eq'Verify'){$expected=Existing $EvidenceOutputPath $false 'LEGACY_STAGE_EVIDENCE_NOT_FOUND';if($ExpectedEvidenceSha256-notmatch'^[A-Fa-f0-9]{64}$'-or(Hash $expected)-cne$ExpectedEvidenceSha256.ToLowerInvariant()){throw'LEGACY_STAGE_EVIDENCE_HASH_MISMATCH'};$value=Get-Content -Raw -LiteralPath $expected|ConvertFrom-Json;$targetUploadInventory=Inventory $targetUploads;$targetReportInventory=Inventory $targetReports;if($value.version-ne1-or$value.result-cne'PASS'-or$value.baselineSha256-cne(Hash $baselinePath)-or$value.sourceDestinationHashesVerified-ne$true-or$value.cloudStorageCalled-ne$false-or$targetUploadInventory.Digest-cne$value.uploadsInventoryDigest-or$targetReportInventory.Digest-cne$value.reportsInventoryDigest){throw'LEGACY_STAGE_VERIFY_FAILED'};[pscustomobject]@{Result='PASS';SourceDestinationHashesVerified=$true;CloudStorageCalled=$false}|ConvertTo-Json;exit 0}
if(Test-Path -LiteralPath $EvidenceOutputPath){throw'LEGACY_STAGE_EVIDENCE_ALREADY_EXISTS'};foreach($root in @($targetUploads,$targetReports)){if(Test-Path -LiteralPath $root){if(Get-ChildItem -LiteralPath $root -Force|Select-Object -First 1){throw'LEGACY_STAGE_TARGET_NOT_EMPTY'}}}
try{CopyDomain $sourceUploads $targetUploads;CopyDomain $sourceReports $targetReports;$targetUploadInventory=Inventory $targetUploads;$targetReportInventory=Inventory $targetReports;if($targetUploadInventory.Digest-cne$baseline.uploadsInventoryDigest-or$targetReportInventory.Digest-cne$baseline.reportsInventoryDigest){throw'LEGACY_STAGE_TARGET_INVENTORY_MISMATCH'};$record=[ordered]@{version=1;result='PASS';proofType='legacy-local-storage-stage';baselineSha256=(Hash $baselinePath);targetDataRoot=$dataRoot;uploadsInventoryDigest=$targetUploadInventory.Digest;uploadsFileCount=$targetUploadInventory.FileCount;uploadsTotalBytes=$targetUploadInventory.TotalBytes;reportsInventoryDigest=$targetReportInventory.Digest;reportsFileCount=$targetReportInventory.FileCount;reportsTotalBytes=$targetReportInventory.TotalBytes;storageInventoryDigest=$baseline.storageInventoryDigest;sourceDestinationHashesVerified=$true;cloudStorageCalled=$false;completedAt=(Get-Date).ToUniversalTime().ToString('o')};[IO.File]::WriteAllText([IO.Path]::GetFullPath($EvidenceOutputPath),($record|ConvertTo-Json),(New-Object Text.UTF8Encoding($false)));$record|ConvertTo-Json}catch{foreach($root in @($targetUploads,$targetReports)){if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}};throw}
