#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Apply','Rollback','Verify','Finalize')][string]$Action='Plan',
  [string]$ServiceRoot,[string]$NodePath,[string]$ExpectedNodeSha256,[string]$ReleaseVerifierPath,[string]$ExpectedReleaseVerifierSha256,
  [string]$RuntimeReadinessVerifierPath,[string]$ExpectedRuntimeReadinessVerifierSha256,
  [string]$TargetReleaseRoot,[string]$TargetRuntimeConfigPath,[string]$ExpectedTargetRuntimeConfigSha256,[string]$TargetApiConfigPath,[string]$ExpectedTargetApiConfigSha256,
  [string]$TargetFileSystemEvidencePath,[string]$ExpectedTargetFileSystemEvidenceSha256,[string]$CoreLogRoot,
  [string]$ExpectedReleaseManifestSha256,[string]$ExpectedReleaseId,[string]$ConfirmProjectRef,[string]$ConfirmDatabaseHost,[string]$ConfirmDatabaseName,[string]$ConfirmDatabaseSchema,[string]$CompatibilityEvidencePath,[string]$ExpectedCompatibilityEvidenceSha256,
  [string]$CompatibilityGeneratorPath,[string]$ExpectedCompatibilityGeneratorSha256,
  [string]$MigrationEvidencePath,[string]$ExpectedMigrationEvidenceSha256,
  [string]$InternalProbeTokenFile,[string]$ExpectedInternalProbeTokenFileSha256,
  [string]$ReleaseSwitchJournalPath,[string]$ExpectedReleaseSwitchJournalSha256,
  [ValidateSet('Apply','Rollback','Finalize')][string]$PlannedAction,[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
$coreServiceId='MetaAdsPerformanceCore';$edgeServiceId='MetaAdsPerformanceEdge'

function Existing([string]$Path,[bool]$Directory,[string]$Code){$kind=if($Directory){'Container'}else{'Leaf'};if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType $kind)){throw $Code};$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');$cursor=Get-Item -LiteralPath $full -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'RELEASE_REPARSE_REJECTED'};$cursor=$cursor.Parent};return $full}
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Sha256Text([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function UnderAny([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');return @($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function EdgeImmutable($Config){return([ordered]@{version=$Config.version;deploymentMode=$Config.deploymentMode;internalPorts=$Config.internalPorts;data=$Config.data;lan=$Config.lan;tls=$Config.tls;hostSecurity=$Config.hostSecurity;database=$Config.database;backup=$Config.backup}|ConvertTo-Json -Compress -Depth 12)}
function Assert-FilesystemCoverage($Config,[string]$Runtime,[string]$Api,[string]$Release,[string]$Node,[string]$Verifier,[string]$Log){
  $evidencePath=Existing ([string]$Config.hostSecurity.filesystemEvidencePath) $false 'FILESYSTEM_EVIDENCE_REQUIRED';$e=Get-Content -Raw -LiteralPath $evidencePath|ConvertFrom-Json
  $age=(Get-Date).ToUniversalTime()-[datetime]$e.completedAt;if($e.result-ne'PASS'-or-not$e.leastPrivilege-or$age.TotalDays-gt7-or$age.TotalMinutes-lt-5-or[IO.Path]::GetFullPath([string]$e.dataRoot)-ine(Resolve-DataRoot $Config.data.root)){throw 'FILESYSTEM_EVIDENCE_REJECTED'}
  $classes=$e.classRoots;if(-not(UnderAny $Release $classes.SHARED_RUNTIME)-or-not(UnderAny $Runtime $classes.SHARED_RUNTIME)-or-not(UnderAny $Node $classes.SHARED_RUNTIME)-or-not(UnderAny $Verifier $classes.SHARED_RUNTIME)-or-not(UnderAny $Api $classes.CORE_READ)-or-not(UnderAny $Log $classes.CORE_MODIFY)-or-not(UnderAny $evidencePath $classes.ADMIN_EVIDENCE)){throw 'FILESYSTEM_EVIDENCE_PATH_COVERAGE_FAILED'}
  $latestReleaseWrite=(Get-ChildItem -LiteralPath $Release -File -Recurse -Force|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1).LastWriteTimeUtc
  if($latestReleaseWrite-and$latestReleaseWrite-gt[datetime]::Parse([string]$e.completedAt).ToUniversalTime()){throw 'FILESYSTEM_EVIDENCE_PREDATES_RELEASE'}
}
function Resolve-DataRoot($Value){if($Value){return [IO.Path]::GetFullPath([string]$Value)};$base=if($env:ProgramData){$env:ProgramData}else{$env:LOCALAPPDATA};if(-not$base){throw 'OS_APPLICATION_DATA_ROOT_UNAVAILABLE'};return [IO.Path]::GetFullPath((Join-Path $base 'MetaAdsPerformance'))}
function CoreXml($Node,$Launcher,$Release,$Runtime,$Api,$Log){$t=Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'service.xml.template');return $t.Replace('__NODE_PATH__',[Security.SecurityElement]::Escape($Node)).Replace('__LAUNCHER_PATH__',[Security.SecurityElement]::Escape($Launcher)).Replace('__RELEASE_ROOT__',[Security.SecurityElement]::Escape($Release)).Replace('__RUNTIME_CONFIG_PATH__',[Security.SecurityElement]::Escape($Runtime)).Replace('__API_CONFIG_PATH__',[Security.SecurityElement]::Escape($Api)).Replace('__LOG_PATH__',[Security.SecurityElement]::Escape($Log))}
function EnvironmentValue([string]$XmlPath,[string]$Name){[xml]$xml=Get-Content -Raw -LiteralPath $XmlPath;$node=@($xml.service.env|Where-Object{$_.name-eq$Name});if($node.Count-ne1-or-not$node[0].value){throw 'SERVICE_XML_ENVIRONMENT_INVALID'};return [IO.Path]::GetFullPath([string]$node[0].value)}
function ReleaseRootValue([string]$XmlPath){return EnvironmentValue $XmlPath 'LOCAL_RELEASE_ROOT'}
function Atomic-ReplaceText([string]$Path,[string]$Text){$pending="$Path.pending";[IO.File]::WriteAllText($pending,$Text,(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $pending -Destination $Path -Force}
function Read-ProbeToken([string]$Path){$file=Existing $Path $false 'INTERNAL_PROBE_TOKEN_FILE_REQUIRED';$item=Get-Item -LiteralPath $file -Force;if($item.Length-lt32-or$item.Length-gt4096){throw 'INTERNAL_PROBE_TOKEN_FILE_INVALID'};$value=[IO.File]::ReadAllText($file).Trim();if($value.Length-lt32){throw 'INTERNAL_PROBE_TOKEN_INVALID'};return $value}
function Probe([int]$Port,[string]$Target,[string]$Status,[string]$ReleaseId,[string]$Token){try{$request=[Net.HttpWebRequest]::Create("http://127.0.0.1:$Port$Target");$request.Proxy=$null;$request.Timeout=1500;$request.Method='GET';if($Token){$request.Headers.Add('x-internal-probe-token',$Token)};$response=$request.GetResponse();try{$reader=New-Object IO.StreamReader($response.GetResponseStream());$body=$reader.ReadToEnd();if($body.Length-gt4096){return $false};$value=$body|ConvertFrom-Json;return [int]$response.StatusCode-eq200-and$value.status-eq$Status-and(-not$ReleaseId-or$value.releaseId-eq$ReleaseId)}finally{$response.Dispose()}}catch{return $false}}
function Wait-CoreHealth($Config,[string]$ReleaseId,[string]$Token,[int]$Seconds=60){$deadline=(Get-Date).AddSeconds($Seconds);do{if((Probe ([int]$Config.internalPorts.api) '/api/health/ready' 'ready' $null $Token)-and(Probe ([int]$Config.internalPorts.web) '/backend-api/health/live' 'live' $ReleaseId $null)){return};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw 'CORE_RELEASE_READY_FAILED'}
function Wait-State([string]$Name,[string]$State,[int]$Seconds=30){$deadline=(Get-Date).AddSeconds($Seconds);do{if((Get-Service -Name $Name -ErrorAction Stop).Status-eq$State){return};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw 'SERVICE_STATE_TIMEOUT'}
function Stop-Core{Stop-Service -Name $coreServiceId -ErrorAction Stop;Wait-State $coreServiceId 'Stopped'}
function Start-Core{Start-Service -Name $coreServiceId -ErrorAction Stop;Wait-State $coreServiceId 'Running'}
function Assert-Drain([string]$DataRoot){$statePath=Join-Path $DataRoot 'logs\edge\drain-state.json';$deadline=(Get-Date).AddMinutes(5);do{if(Test-Path -LiteralPath $statePath -PathType Leaf){$state=Get-Content -Raw -LiteralPath $statePath|ConvertFrom-Json;$completed=[datetime]::Parse([string]$state.completedAt).ToUniversalTime();if($state.version-eq1-and$state.result-eq'DRAINED'-and$state.activeRequests-eq0-and(Get-Process -Id ([int]$state.processId) -ErrorAction SilentlyContinue)-and$completed-gt(Get-Date).ToUniversalTime().AddSeconds(-30)){return}};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw 'EDGE_DRAIN_TIMEOUT'}
function Validate-Compatibility([string]$Previous,[string]$Target,[string]$PreviousManifestHash,[string]$TargetManifestHash){if($Previous-eq$Target){return};$path=Existing $CompatibilityEvidencePath $false 'COMPATIBILITY_EVIDENCE_REQUIRED';$generator=Existing $CompatibilityGeneratorPath $false 'COMPATIBILITY_GENERATOR_REQUIRED';if($ExpectedCompatibilityEvidenceSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $path)-cne$ExpectedCompatibilityEvidenceSha256.ToLowerInvariant()){throw 'COMPATIBILITY_EVIDENCE_HASH_MISMATCH'};if($ExpectedCompatibilityGeneratorSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $generator)-cne$ExpectedCompatibilityGeneratorSha256.ToLowerInvariant()){throw 'COMPATIBILITY_GENERATOR_HASH_MISMATCH'};$filesystem=Get-Content -Raw -LiteralPath (Existing ([string]$targetRuntime.hostSecurity.filesystemEvidencePath) $false 'FILESYSTEM_EVIDENCE_REQUIRED')|ConvertFrom-Json;$latestPath=Existing ([string]$targetRuntime.backup.latestBackupEvidencePath) $false 'LATEST_BACKUP_EVIDENCE_REQUIRED';if(-not(UnderAny $path $filesystem.classRoots.ADMIN_EVIDENCE)-or-not(UnderAny $generator $filesystem.classRoots.SHARED_RUNTIME)-or-not(UnderAny $latestPath $filesystem.classRoots.BACKUP_RECEIPT)){throw 'COMPATIBILITY_FILESYSTEM_BOUNDARY_REJECTED'};$latest=Get-Content -Raw -LiteralPath $latestPath|ConvertFrom-Json;$e=Get-Content -Raw -LiteralPath $path|ConvertFrom-Json;$age=(Get-Date).ToUniversalTime()-[datetime]::Parse([string]$e.completedAt).ToUniversalTime();if($e.version-ne5-or$e.result-ne'PASS'-or$e.proofType-ne'release-compatibility'-or$e.generatorScriptSha256-cne(Hash $generator)-or$e.nodeSha256-cne$ExpectedNodeSha256.ToLowerInvariant()-or$e.attestationVerifierSha256-notmatch'^[0-9a-f]{64}$'-or$e.executorSetDigest-cne(Sha256Text (@($e.nodeSha256,$e.attestationVerifierSha256)-join"`n"))-or-not$e.backwardCompatible-or-not$e.rollbackCodeCompatible-or-not$e.previousMigrationChainUnchanged-or-not$e.additiveDeltaVerified-or-not$e.previousReleaseSmokeBeforeMigration-or-not$e.targetMigrationsAppliedToIsolatedRestore-or-not$e.previousReleaseSmokeAfterMigration-or-not$e.targetReleaseSmokeAfterMigration-or-not$e.isolatedRestoreVerified-or-not$e.authRoleMatrixVerified-or-not$e.businessKpiVerified-or-not$e.storageHashVerified-or-not$e.storageReferenceVerified-or-not$e.restoreTargetCleaned-or-not$e.freshBackupBound-or$e.latestBackupEvidenceSha256-cne(Hash $latestPath)-or$e.backupId-cne$latest.backupId-or$e.backupManifestSha256-cne$latest.manifestSha256-or$e.productionDatabaseMutated-or$e.previousMigrationDigest-ne$Previous-or$e.targetMigrationDigest-ne$Target-or$e.previousManifestSha256-ne$PreviousManifestHash-or$e.targetManifestSha256-ne$TargetManifestHash-or$e.restoreEvidenceSha256-notmatch'^[0-9a-f]{64}$'-or$e.restoreSigningKeyId-notmatch'^[0-9a-f]{64}$'-or$e.rehearsalEvidenceSha256-notmatch'^[0-9a-f]{64}$'-or$e.rehearsalSigningKeyId-notmatch'^[0-9a-f]{64}$'-or$age.TotalDays-gt30-or$age.TotalMinutes-lt-5){throw 'DATABASE_COMPATIBILITY_EVIDENCE_REJECTED'}}
function Validate-MigrationFinalized([string]$Previous,[string]$Target,[string]$TargetManifestHash){if($Previous-ceq$Target){return};$path=Existing $MigrationEvidencePath $false 'FINALIZED_MIGRATION_EVIDENCE_REQUIRED';if($ExpectedMigrationEvidenceSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $path)-cne$ExpectedMigrationEvidenceSha256.ToLowerInvariant()){throw 'FINALIZED_MIGRATION_EVIDENCE_HASH_MISMATCH'};$filesystem=Get-Content -Raw -LiteralPath (Existing ([string]$targetRuntime.hostSecurity.filesystemEvidencePath) $false 'FILESYSTEM_EVIDENCE_REQUIRED')|ConvertFrom-Json;if(-not(UnderAny $path $filesystem.classRoots.ADMIN_EVIDENCE)){throw 'FINALIZED_MIGRATION_EVIDENCE_BOUNDARY_REJECTED'};$e=Get-Content -Raw -LiteralPath $path|ConvertFrom-Json;if($e.version-ne4-or$e.result-cne'APPLIED'-or$e.provider-cne'supabase_postgres'-or$e.projectRef-cne$targetRuntime.database.projectRef-or$e.host-cne$targetRuntime.database.host-or$e.databaseName-cne$targetRuntime.database.name-or$e.databaseSchema-cne$targetRuntime.database.schema-or$e.previousMigrationDigest-cne$Previous-or$e.targetMigrationDigest-cne$Target-or$e.targetManifestSha256-cne$TargetManifestHash-or-not$e.maintenanceVerified-or-not$e.drainVerified-or$e.postBoundaryEvidenceSha256-notmatch'^[0-9a-f]{64}$'){throw 'FINALIZED_MIGRATION_EVIDENCE_REJECTED'}}

function New-ReleaseSwitchApprovalPlan([string]$IntendedAction){
  if($IntendedAction-notin@('Apply','Rollback','Finalize')){throw 'PLANNED_ACTION_REQUIRED'}
  if($ExpectedReleaseId-notmatch'^[a-z0-9][a-z0-9._-]{0,62}$'-or$ConfirmProjectRef-notmatch'^[a-z]{20}$'-or$ConfirmDatabaseHost-notmatch'^(?:db\.[a-z]{20}\.supabase\.co|[a-z0-9-]+\.pooler\.supabase\.com)$'-or$ConfirmDatabaseName-notmatch'^[a-z][a-z0-9_]{0,62}$'-or$ConfirmDatabaseSchema-notmatch'^[a-z][a-z0-9_]{0,62}$'){throw 'RELEASE_SWITCH_PLAN_IDENTITY_INVALID'}
  Assert-ApprovalOptionalArtifact $CompatibilityEvidencePath $ExpectedCompatibilityEvidenceSha256 'RELEASE_SWITCH_PLAN_COMPATIBILITY_PAIR_REQUIRED';Assert-ApprovalOptionalArtifact $CompatibilityGeneratorPath $ExpectedCompatibilityGeneratorSha256 'RELEASE_SWITCH_PLAN_COMPATIBILITY_GENERATOR_PAIR_REQUIRED';Assert-ApprovalOptionalArtifact $MigrationEvidencePath $ExpectedMigrationEvidenceSha256 'RELEASE_SWITCH_PLAN_MIGRATION_PAIR_REQUIRED'
  $parameters=[ordered]@{serviceRoot=(Get-ApprovalPath $ServiceRoot 'RELEASE_SWITCH_PLAN_SERVICE_ROOT_REQUIRED');coreServiceId=$coreServiceId;edgeServiceId=$edgeServiceId;targetReleaseId=$ExpectedReleaseId;targetReleaseRoot=(Get-ApprovalPath $TargetReleaseRoot 'RELEASE_SWITCH_PLAN_TARGET_ROOT_REQUIRED');targetManifestSha256=(Get-ApprovalHash $ExpectedReleaseManifestSha256 'RELEASE_SWITCH_PLAN_MANIFEST_HASH_REQUIRED');targetRuntimeConfigPath=(Get-ApprovalPath $TargetRuntimeConfigPath 'RELEASE_SWITCH_PLAN_RUNTIME_PATH_REQUIRED');targetRuntimeConfigSha256=(Get-ApprovalHash $ExpectedTargetRuntimeConfigSha256 'RELEASE_SWITCH_PLAN_RUNTIME_HASH_REQUIRED');targetApiConfigPath=(Get-ApprovalPath $TargetApiConfigPath 'RELEASE_SWITCH_PLAN_API_PATH_REQUIRED');targetApiConfigSha256=(Get-ApprovalHash $ExpectedTargetApiConfigSha256 'RELEASE_SWITCH_PLAN_API_HASH_REQUIRED');targetFileSystemEvidencePath=(Get-ApprovalPath $TargetFileSystemEvidencePath 'RELEASE_SWITCH_PLAN_FILESYSTEM_EVIDENCE_PATH_REQUIRED');targetFileSystemEvidenceSha256=(Get-ApprovalHash $ExpectedTargetFileSystemEvidenceSha256 'RELEASE_SWITCH_PLAN_FILESYSTEM_EVIDENCE_HASH_REQUIRED');coreLogRoot=(Get-ApprovalPath $CoreLogRoot 'RELEASE_SWITCH_PLAN_LOG_ROOT_REQUIRED');nodePath=(Get-ApprovalPath $NodePath 'RELEASE_SWITCH_PLAN_NODE_PATH_REQUIRED');nodeSha256=(Get-ApprovalHash $ExpectedNodeSha256 'RELEASE_SWITCH_PLAN_NODE_HASH_REQUIRED');releaseVerifierPath=(Get-ApprovalPath $ReleaseVerifierPath 'RELEASE_SWITCH_PLAN_RELEASE_VERIFIER_PATH_REQUIRED');releaseVerifierSha256=(Get-ApprovalHash $ExpectedReleaseVerifierSha256 'RELEASE_SWITCH_PLAN_RELEASE_VERIFIER_HASH_REQUIRED');runtimeReadinessVerifierPath=(Get-ApprovalPath $RuntimeReadinessVerifierPath 'RELEASE_SWITCH_PLAN_READINESS_VERIFIER_PATH_REQUIRED');runtimeReadinessVerifierSha256=(Get-ApprovalHash $ExpectedRuntimeReadinessVerifierSha256 'RELEASE_SWITCH_PLAN_READINESS_VERIFIER_HASH_REQUIRED');compatibilityEvidencePath=(Get-ApprovalOptionalPath $CompatibilityEvidencePath);compatibilityEvidenceSha256=(Get-ApprovalOptionalHash $ExpectedCompatibilityEvidenceSha256);compatibilityGeneratorPath=(Get-ApprovalOptionalPath $CompatibilityGeneratorPath);compatibilityGeneratorSha256=(Get-ApprovalOptionalHash $ExpectedCompatibilityGeneratorSha256);migrationEvidencePath=(Get-ApprovalOptionalPath $MigrationEvidencePath);migrationEvidenceSha256=(Get-ApprovalOptionalHash $ExpectedMigrationEvidenceSha256);internalProbeTokenFile=(Get-ApprovalPath $InternalProbeTokenFile 'RELEASE_SWITCH_PLAN_PROBE_PATH_REQUIRED');internalProbeTokenFileSha256=(Get-ApprovalHash $ExpectedInternalProbeTokenFileSha256 'RELEASE_SWITCH_PLAN_PROBE_HASH_REQUIRED');databaseProjectRef=$ConfirmProjectRef;databaseHost=$ConfirmDatabaseHost;databasePort=5432;databaseName=$ConfirmDatabaseName;databaseSchema=$ConfirmDatabaseSchema}
  if($IntendedAction-in@('Rollback','Finalize')){$parameters.releaseSwitchJournalPath=Get-ApprovalPath $ReleaseSwitchJournalPath 'RELEASE_SWITCH_PLAN_JOURNAL_PATH_REQUIRED';$parameters.releaseSwitchJournalSha256=Get-ApprovalHash $ExpectedReleaseSwitchJournalSha256 'RELEASE_SWITCH_PLAN_JOURNAL_HASH_REQUIRED'}
  $target="Exact Core release $ExpectedReleaseId against Supabase $ConfirmProjectRef/$ConfirmDatabaseHost`:5432/$ConfirmDatabaseName schema $ConfirmDatabaseSchema"
  $impact=if($IntendedAction-eq'Apply'){'Under maintenance and a fresh drain, stops only Core, atomically switches exact runtime/API/XML generation, restarts Core, and verifies readiness while Edge remains running'}elseif($IntendedAction-eq'Rollback'){'Stops only Core, restores the journal-bound prior XML/runtime/API generation, restarts Core, and verifies the previous release'}else{'Deletes only the verified release-switch journal and rollback artifacts after successful target verification'}
  $rollback=if($IntendedAction-eq'Apply'){'Use a separately approved Rollback plan bound to the exact prior artifacts; legacy 3100/4100 are never targeted'}elseif($IntendedAction-eq'Rollback'){'Re-apply only through a new approved Apply plan'}else{'Finalize removes local rollback artifacts; recover from the separately verified release/recovery kit and database backup'}
  return New-ApprovalPlan $PSCommandPath $IntendedAction $parameters $target $impact $rollback
}

if($Action-eq'Plan'){New-ReleaseSwitchApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0}
$releaseMutation=if($Action-in@('Apply','Rollback','Finalize')){$Action}else{$null};if($releaseMutation){Assert-ApprovedPlan (New-ReleaseSwitchApprovalPlan $releaseMutation) ([bool]$Approved) $ApprovedPlanSha256}

$serviceRoot=Existing $ServiceRoot $true 'SERVICE_ROOT_NOT_FOUND';$activeXml=Join-Path $serviceRoot 'MetaAdsPerformanceCore.xml';$edgeXml=Join-Path $serviceRoot 'MetaAdsPerformanceEdge.xml';$previousXml="$activeXml.previous";$journalPath=Join-Path $serviceRoot 'release-switch.json'
if($Action-in@('Rollback','Finalize')){if([IO.Path]::GetFullPath($ReleaseSwitchJournalPath)-ine[IO.Path]::GetFullPath($journalPath)){throw 'RELEASE_SWITCH_JOURNAL_PATH_MISMATCH'};if((Hash (Existing $journalPath $false 'RELEASE_SWITCH_JOURNAL_NOT_FOUND'))-cne$ExpectedReleaseSwitchJournalSha256.ToLowerInvariant()){throw 'RELEASE_SWITCH_JOURNAL_HASH_MISMATCH'}}
$activeRuntime=if(Test-Path -LiteralPath $edgeXml){EnvironmentValue $edgeXml 'LOCAL_RUNTIME_CONFIG_PATH'}else{$null};$activeApi=if(Test-Path -LiteralPath $activeXml){EnvironmentValue $activeXml 'CONFIG_PATH'}else{$null}
$probeTokenPath=Existing $InternalProbeTokenFile $false 'INTERNAL_PROBE_TOKEN_FILE_REQUIRED';if((Hash $probeTokenPath)-cne$ExpectedInternalProbeTokenFileSha256.ToLowerInvariant()){throw 'INTERNAL_PROBE_TOKEN_FILE_HASH_MISMATCH'};$probeToken=Read-ProbeToken $probeTokenPath

if($Action-eq'Rollback'){
  foreach($file in @($previousXml,$journalPath,"$activeRuntime.previous","$activeApi.previous")){Existing $file $false 'RELEASE_ROLLBACK_NOT_AVAILABLE'|Out-Null}
  $journal=Get-Content -Raw -LiteralPath $journalPath|ConvertFrom-Json
  if((Hash $previousXml)-cne$journal.previousXmlSha256-or(Hash "$activeRuntime.previous")-cne$journal.previousRuntimeSha256-or(Hash "$activeApi.previous")-cne$journal.previousApiSha256){throw 'ROLLBACK_ARTIFACT_HASH_MISMATCH'}
  $node=Existing $NodePath $false 'NODE_BINARY_NOT_FOUND';$verifier=Existing $ReleaseVerifierPath $false 'RELEASE_VERIFIER_NOT_FOUND';if($ExpectedNodeSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $node)-cne$ExpectedNodeSha256.ToLowerInvariant()){throw 'NODE_HASH_MISMATCH'};if($ExpectedReleaseVerifierSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $verifier)-cne$ExpectedReleaseVerifierSha256.ToLowerInvariant()){throw 'RELEASE_VERIFIER_HASH_MISMATCH'}
  $previousConfig=Get-Content -Raw -LiteralPath "$activeRuntime.previous"|ConvertFrom-Json;$previousFs=Get-Content -Raw -LiteralPath (Existing ([string]$previousConfig.hostSecurity.filesystemEvidencePath) $false 'FILESYSTEM_EVIDENCE_REQUIRED')|ConvertFrom-Json;if(-not(UnderAny $node $previousFs.classRoots.SHARED_RUNTIME)-or-not(UnderAny $verifier $previousFs.classRoots.SHARED_RUNTIME)){throw 'ROLLBACK_EXECUTOR_OUTSIDE_SHARED_RUNTIME'}
  $previousReleaseRoot=Existing ([string]$journal.previousReleaseRoot) $true 'PREVIOUS_RELEASE_NOT_FOUND';&$node $verifier "--root=$previousReleaseRoot" "--manifest-sha256=$($journal.previousManifestSha256)"|Out-Null;if($LASTEXITCODE-ne0){throw 'PREVIOUS_RELEASE_VERIFICATION_FAILED'}
  $dataRoot=Resolve-DataRoot ((Get-Content -Raw -LiteralPath "$activeRuntime.previous"|ConvertFrom-Json).data.root);if(-not(Test-Path -LiteralPath (Join-Path $dataRoot 'runtime-control\maintenance.enabled') -PathType Leaf)){throw 'MAINTENANCE_REQUIRED'};Assert-Drain $dataRoot
  Stop-Core;try{Atomic-ReplaceText $activeRuntime (Get-Content -Raw -LiteralPath "$activeRuntime.previous");Atomic-ReplaceText $activeApi (Get-Content -Raw -LiteralPath "$activeApi.previous");Atomic-ReplaceText $activeXml (Get-Content -Raw -LiteralPath $previousXml);Start-Core;$previousConfig=Get-Content -Raw -LiteralPath $activeRuntime|ConvertFrom-Json;Wait-CoreHealth $previousConfig $journal.previousReleaseId $probeToken}catch{throw 'RELEASE_ROLLBACK_FAILED'}
  [pscustomobject]@{Result='ROLLED_BACK';ReleaseId=$journal.previousReleaseId;MaintenanceStillEnabled=$true;EdgeRestarted=$false;LegacyProcessesChanged=$false}|ConvertTo-Json;exit 0
}

$node=Existing $NodePath $false 'NODE_BINARY_NOT_FOUND';$verifier=Existing $ReleaseVerifierPath $false 'RELEASE_VERIFIER_NOT_FOUND';$readinessVerifier=Existing $RuntimeReadinessVerifierPath $false 'RUNTIME_READINESS_VERIFIER_NOT_FOUND';if($ExpectedNodeSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $node)-cne$ExpectedNodeSha256.ToLowerInvariant()){throw 'NODE_HASH_MISMATCH'};if($ExpectedReleaseVerifierSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $verifier)-cne$ExpectedReleaseVerifierSha256.ToLowerInvariant()){throw 'RELEASE_VERIFIER_HASH_MISMATCH'};if($ExpectedRuntimeReadinessVerifierSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $readinessVerifier)-cne$ExpectedRuntimeReadinessVerifierSha256.ToLowerInvariant()){throw 'RUNTIME_READINESS_VERIFIER_HASH_MISMATCH'}
$targetRoot=Existing $TargetReleaseRoot $true 'TARGET_RELEASE_NOT_FOUND';$targetRuntimePath=Existing $TargetRuntimeConfigPath $false 'TARGET_RUNTIME_CONFIG_NOT_FOUND';$targetApiPath=Existing $TargetApiConfigPath $false 'TARGET_API_CONFIG_NOT_FOUND';$logRoot=Existing $CoreLogRoot $true 'CORE_LOG_ROOT_NOT_FOUND'
if((Hash $targetRuntimePath)-cne$ExpectedTargetRuntimeConfigSha256.ToLowerInvariant()-or(Hash $targetApiPath)-cne$ExpectedTargetApiConfigSha256.ToLowerInvariant()){throw 'TARGET_CONFIG_HASH_MISMATCH'}
if($ExpectedReleaseManifestSha256-notmatch'^[0-9a-f]{64}$'){throw 'RELEASE_MANIFEST_HASH_INVALID'}
&$node $verifier "--root=$targetRoot" "--manifest-sha256=$ExpectedReleaseManifestSha256"|Out-Null;if($LASTEXITCODE-ne0){throw 'RELEASE_VERIFICATION_FAILED'}
$manifest=Get-Content -Raw -LiteralPath (Join-Path $targetRoot 'release-manifest.json')|ConvertFrom-Json;$targetRuntime=Get-Content -Raw -LiteralPath $targetRuntimePath|ConvertFrom-Json
$targetFsPath=Existing $TargetFileSystemEvidencePath $false 'TARGET_FILESYSTEM_EVIDENCE_REQUIRED';if((Hash $targetFsPath)-cne$ExpectedTargetFileSystemEvidenceSha256.ToLowerInvariant()-or[IO.Path]::GetFullPath([string]$targetRuntime.hostSecurity.filesystemEvidencePath)-ine$targetFsPath){throw 'TARGET_FILESYSTEM_EVIDENCE_MISMATCH'}
if($targetRuntime.release.id-cne$ExpectedReleaseId-or$targetRuntime.release.id-ne$manifest.releaseId-or$targetRuntime.release.migrationDigest-ne$manifest.migrationDigest-or$targetRuntime.database.projectRef-cne$ConfirmProjectRef-or$targetRuntime.database.host-cne$ConfirmDatabaseHost-or$targetRuntime.database.name-cne$ConfirmDatabaseName-or$targetRuntime.database.schema-cne$ConfirmDatabaseSchema){throw 'RELEASE_RUNTIME_IDENTITY_MISMATCH'}
$currentRuntimeForBoundary=if($activeRuntime-and(Test-Path -LiteralPath $activeRuntime -PathType Leaf)){Get-Content -Raw -LiteralPath $activeRuntime|ConvertFrom-Json}else{$null}
if($currentRuntimeForBoundary-and(EdgeImmutable $currentRuntimeForBoundary)-cne(EdgeImmutable $targetRuntime)){throw 'EDGE_IMMUTABLE_CONFIG_CHANGE_REQUIRES_SEPARATE_WORKFLOW'}
Assert-FilesystemCoverage $targetRuntime $targetRuntimePath $targetApiPath $targetRoot $node $verifier $logRoot
$targetFilesystem=Get-Content -Raw -LiteralPath $targetFsPath|ConvertFrom-Json;if(-not(UnderAny $readinessVerifier $targetFilesystem.classRoots.SHARED_RUNTIME)){throw 'RUNTIME_READINESS_VERIFIER_OUTSIDE_SHARED_RUNTIME'}
&$node $readinessVerifier "--runtime-config=$targetRuntimePath" "--release-root=$targetRoot" '--mode=operational' 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw 'TARGET_OPERATIONAL_READINESS_FAILED'}
$targetXml=CoreXml $node (Join-Path $targetRoot 'deploy\local\launch-local-bundle.mjs') $targetRoot $activeRuntime $activeApi $logRoot
$core=Get-Service -Name $coreServiceId -ErrorAction SilentlyContinue;$edge=Get-Service -Name $edgeServiceId -ErrorAction SilentlyContinue

if($Action-eq'Verify'-or$Action-eq'Finalize'){
  if(-not$core-or$core.Status-ne'Running'-or-not$edge-or$edge.Status-ne'Running'-or(Get-Content -Raw -LiteralPath $activeXml)-cne$targetXml){throw 'ACTIVE_RELEASE_VERIFY_FAILED'}
  Wait-CoreHealth (Get-Content -Raw -LiteralPath $activeRuntime|ConvertFrom-Json) $manifest.releaseId $probeToken
  if($Action-eq'Finalize'){foreach($file in @($previousXml,"$activeRuntime.previous","$activeApi.previous",$journalPath)){if(Test-Path -LiteralPath $file){Remove-Item -LiteralPath $file -Force}}}
  [pscustomobject]@{Result=if($Action-eq'Finalize'){'FINALIZED'}else{'PASS'};ReleaseId=$manifest.releaseId;CoreRunning=$true;EdgeRunning=$true;RollbackAvailable=(Test-Path -LiteralPath $journalPath)}|ConvertTo-Json;exit 0
}

if(-not$core-or-not$edge-or$core.Status-ne'Running'-or$edge.Status-ne'Running'-or-not(Test-Path -LiteralPath $activeXml -PathType Leaf)){throw 'CORE_EDGE_SERVICES_NOT_READY'}
foreach($file in @($previousXml,"$activeRuntime.previous","$activeApi.previous",$journalPath)){if(Test-Path -LiteralPath $file){throw 'UNFINISHED_RELEASE_SWITCH_PRESENT'}}
$currentRuntime=Get-Content -Raw -LiteralPath $activeRuntime|ConvertFrom-Json;$dataRoot=Resolve-DataRoot $currentRuntime.data.root
if(-not(Test-Path -LiteralPath (Join-Path $dataRoot 'runtime-control\maintenance.enabled') -PathType Leaf)){throw 'MAINTENANCE_REQUIRED'};Assert-Drain $dataRoot
  $previousReleaseRoot=Existing (ReleaseRootValue $activeXml) $true 'PREVIOUS_RELEASE_NOT_FOUND';$previousManifestPath=Existing (Join-Path $previousReleaseRoot 'release-manifest.json') $false 'PREVIOUS_RELEASE_MANIFEST_NOT_FOUND';$previousManifestSha256=Hash $previousManifestPath
  &$node $verifier "--root=$previousReleaseRoot" "--manifest-sha256=$previousManifestSha256"|Out-Null;if($LASTEXITCODE-ne0){throw 'PREVIOUS_RELEASE_VERIFICATION_FAILED'}
  Assert-FilesystemCoverage $currentRuntime $activeRuntime $activeApi $previousReleaseRoot $node $verifier $logRoot
  Validate-Compatibility $currentRuntime.release.migrationDigest $manifest.migrationDigest $previousManifestSha256 $ExpectedReleaseManifestSha256.ToLowerInvariant()
  Validate-MigrationFinalized $currentRuntime.release.migrationDigest $manifest.migrationDigest $ExpectedReleaseManifestSha256.ToLowerInvariant()
Copy-Item -LiteralPath $activeXml -Destination $previousXml;Copy-Item -LiteralPath $activeRuntime -Destination "$activeRuntime.previous";Copy-Item -LiteralPath $activeApi -Destination "$activeApi.previous"
$journal=[ordered]@{version=3;previousReleaseId=$currentRuntime.release.id;previousMigrationDigest=$currentRuntime.release.migrationDigest;previousReleaseRoot=$previousReleaseRoot;previousManifestSha256=$previousManifestSha256;previousXmlSha256=Hash $previousXml;previousRuntimeSha256=Hash "$activeRuntime.previous";previousApiSha256=Hash "$activeApi.previous";targetReleaseId=$manifest.releaseId;targetManifestSha256=$ExpectedReleaseManifestSha256.ToLowerInvariant();switchedAt=(Get-Date).ToUniversalTime().ToString('o')}
Atomic-ReplaceText $journalPath ($journal|ConvertTo-Json -Depth 4)
Stop-Core
try{Atomic-ReplaceText $activeRuntime (Get-Content -Raw -LiteralPath $targetRuntimePath);Atomic-ReplaceText $activeApi (Get-Content -Raw -LiteralPath $targetApiPath);Atomic-ReplaceText $activeXml $targetXml;Start-Core;Wait-CoreHealth $targetRuntime $manifest.releaseId $probeToken}catch{try{if((Get-Service -Name $coreServiceId).Status-ne'Stopped'){Stop-Core};Atomic-ReplaceText $activeRuntime (Get-Content -Raw -LiteralPath "$activeRuntime.previous");Atomic-ReplaceText $activeApi (Get-Content -Raw -LiteralPath "$activeApi.previous");Atomic-ReplaceText $activeXml (Get-Content -Raw -LiteralPath $previousXml);Start-Core;Wait-CoreHealth $currentRuntime $currentRuntime.release.id $probeToken}catch{throw 'RELEASE_SWITCH_AND_AUTOMATIC_ROLLBACK_FAILED'};throw 'RELEASE_SWITCH_ROLLED_BACK'}
[pscustomobject]@{Result='APPLIED';ReleaseId=$manifest.releaseId;RollbackAvailable=$true;MaintenanceStillEnabled=$true;CoreRestarted=$true;EdgeRestarted=$false;LegacyProcessesChanged=$false}|ConvertTo-Json
