#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Apply','Rollback','Verify','Finalize')][string]$Action='Plan',
  [string]$ServiceRoot,[string]$NodePath,[string]$ExpectedNodeSha256,[string]$ReleaseVerifierPath,[string]$ExpectedReleaseVerifierSha256,
  [string]$RuntimeReadinessVerifierPath,[string]$ExpectedRuntimeReadinessVerifierSha256,
  [string]$EdgeDrainHelperPath,[string]$ExpectedEdgeDrainHelperSha256,[string]$DrainStatePath,[string]$ExpectedDrainStateSha256,
  [string]$AttestationVerifierPath,[string]$ExpectedAttestationVerifierSha256,[string]$EdgeSigningPublicKeyPath,[string]$ExpectedEdgeSigningPublicKeySha256,
  [string]$HttpsVerifierPath,[string]$ExpectedHttpsVerifierSha256,
  [string]$ExpectedHttpsCaCertificateSha256,[string]$ExpectedHttpsServerCertificateSha256,
  [string]$TargetReleaseRoot,[string]$TargetRuntimeConfigPath,[string]$ExpectedTargetRuntimeConfigSha256,[string]$TargetApiConfigPath,[string]$ExpectedTargetApiConfigSha256,
  [string]$TargetFileSystemEvidencePath,[string]$ExpectedTargetFileSystemEvidenceSha256,[string]$CoreLogRoot,[string]$EdgeLogRoot,
  [string]$ExpectedReleaseManifestSha256,[string]$ExpectedReleaseId,[string]$ConfirmProjectRef,[string]$ConfirmDatabaseHost,[string]$ConfirmDatabaseName,[string]$ConfirmDatabaseSchema,[string]$CompatibilityEvidencePath,[string]$ExpectedCompatibilityEvidenceSha256,
  [string]$CompatibilityGeneratorPath,[string]$ExpectedCompatibilityGeneratorSha256,
  [string]$MigrationEvidencePath,[string]$ExpectedMigrationEvidenceSha256,
  [string]$InternalProbeTokenFile,[string]$ExpectedInternalProbeTokenFileSha256,
  [string]$ReleaseSwitchJournalPath,[string]$ExpectedReleaseSwitchJournalSha256,
  [ValidateSet('Apply','Rollback','Finalize')][string]$PlannedAction,[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
$edgeDrainHelper=if($EdgeDrainHelperPath){[IO.Path]::GetFullPath($EdgeDrainHelperPath)}else{[IO.Path]::GetFullPath((Join-Path $PSScriptRoot 'edge-drain-identity.ps1'))};if($ExpectedEdgeDrainHelperSha256-notmatch'^[A-Fa-f0-9]{64}$'-or-not(Test-Path -LiteralPath $edgeDrainHelper -PathType Leaf)-or(Get-FileHash -LiteralPath $edgeDrainHelper -Algorithm SHA256).Hash.ToLowerInvariant()-cne$ExpectedEdgeDrainHelperSha256.ToLowerInvariant()){throw 'EDGE_DRAIN_HELPER_HASH_MISMATCH'};. $edgeDrainHelper
$coreServiceId='MetaAdsPerformanceCore';$edgeServiceId='MetaAdsPerformanceEdge'

function Existing([string]$Path,[bool]$Directory,[string]$Code){$kind=if($Directory){'Container'}else{'Leaf'};if(-not$Path-or-not(Test-Path -LiteralPath $Path -PathType $kind)){throw $Code};$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');$cursor=Get-Item -LiteralPath $full -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'RELEASE_REPARSE_REJECTED'};$cursor=$cursor.Parent};return $full}
function Hash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Sha256Text([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function UnderAny([string]$Path,$Roots){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\');return @($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function EdgeImmutable($Config){return([ordered]@{version=$Config.version;deploymentMode=$Config.deploymentMode;internalPorts=$Config.internalPorts;data=$Config.data;lan=$Config.lan;tls=$Config.tls;hostSecurity=$Config.hostSecurity;database=$Config.database;backup=$Config.backup}|ConvertTo-Json -Compress -Depth 12)}
function Assert-FilesystemCoverage($Config,[string]$Runtime,[string]$Api,[string]$Release,[string]$Node,[string]$Verifier,[string]$Log,[string]$EdgeLog){
  $evidencePath=Existing ([string]$Config.hostSecurity.filesystemEvidencePath) $false 'FILESYSTEM_EVIDENCE_REQUIRED';$e=Get-Content -Raw -LiteralPath $evidencePath|ConvertFrom-Json
  $age=(Get-Date).ToUniversalTime()-[datetime]$e.completedAt;if($e.result-ne'PASS'-or-not$e.leastPrivilege-or$age.TotalDays-gt7-or$age.TotalMinutes-lt-5-or[IO.Path]::GetFullPath([string]$e.dataRoot)-ine(Resolve-DataRoot $Config.data.root)){throw 'FILESYSTEM_EVIDENCE_REJECTED'}
  $classes=$e.classRoots;if(-not(UnderAny $Release $classes.SHARED_RUNTIME)-or-not(UnderAny $Runtime $classes.SHARED_RUNTIME)-or-not(UnderAny $Node $classes.SHARED_RUNTIME)-or-not(UnderAny $Verifier $classes.SHARED_RUNTIME)-or-not(UnderAny $Api $classes.CORE_READ)-or-not(UnderAny $Log $classes.CORE_MODIFY)-or-not(UnderAny $EdgeLog $classes.EDGE_MODIFY)-or-not(UnderAny $evidencePath $classes.ADMIN_EVIDENCE)){throw 'FILESYSTEM_EVIDENCE_PATH_COVERAGE_FAILED'}
  $latestReleaseWrite=(Get-ChildItem -LiteralPath $Release -File -Recurse -Force|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1).LastWriteTimeUtc
  if($latestReleaseWrite-and$latestReleaseWrite-gt[datetime]::Parse([string]$e.completedAt).ToUniversalTime()){throw 'FILESYSTEM_EVIDENCE_PREDATES_RELEASE'}
}
function Resolve-DataRoot($Value){if($Value){return [IO.Path]::GetFullPath([string]$Value)};$base=if($env:ProgramData){$env:ProgramData}else{$env:LOCALAPPDATA};if(-not$base){throw 'OS_APPLICATION_DATA_ROOT_UNAVAILABLE'};return [IO.Path]::GetFullPath((Join-Path $base 'MetaAdsPerformance'))}
function CoreXml($Node,$Launcher,$Release,$Runtime,$Api,$Log){$t=Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'service.xml.template');return $t.Replace('__NODE_PATH__',[Security.SecurityElement]::Escape($Node)).Replace('__LAUNCHER_PATH__',[Security.SecurityElement]::Escape($Launcher)).Replace('__RELEASE_ROOT__',[Security.SecurityElement]::Escape($Release)).Replace('__RUNTIME_CONFIG_PATH__',[Security.SecurityElement]::Escape($Runtime)).Replace('__API_CONFIG_PATH__',[Security.SecurityElement]::Escape($Api)).Replace('__LOG_PATH__',[Security.SecurityElement]::Escape($Log))}
function EdgeXml($Node,$Launcher,$Release,$Runtime,$Log){$t=Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'edge-service.xml.template');return $t.Replace('__NODE_PATH__',[Security.SecurityElement]::Escape($Node)).Replace('__EDGE_LAUNCHER_PATH__',[Security.SecurityElement]::Escape($Launcher)).Replace('__RELEASE_ROOT__',[Security.SecurityElement]::Escape($Release)).Replace('__RUNTIME_CONFIG_PATH__',[Security.SecurityElement]::Escape($Runtime)).Replace('__LOG_PATH__',[Security.SecurityElement]::Escape($Log))}
function EnvironmentValue([string]$XmlPath,[string]$Name){[xml]$xml=Get-Content -Raw -LiteralPath $XmlPath;$node=@($xml.service.env|Where-Object{$_.name-eq$Name});if($node.Count-ne1-or-not$node[0].value){throw 'SERVICE_XML_ENVIRONMENT_INVALID'};return [IO.Path]::GetFullPath([string]$node[0].value)}
function ReleaseRootValue([string]$XmlPath){return EnvironmentValue $XmlPath 'LOCAL_RELEASE_ROOT'}
function Atomic-ReplaceText([string]$Path,[string]$Text){$full=[IO.Path]::GetFullPath($Path);$parent=Split-Path -Parent $full;if(-not(Test-Path -LiteralPath $parent -PathType Container)){throw 'RELEASE_ATOMIC_PARENT_NOT_FOUND'};$pending=Join-Path $parent ('.release-switch-'+[guid]::NewGuid().ToString('N')+'.pending');$bytes=[Text.Encoding]::UTF8.GetBytes($Text);try{$stream=[IO.FileStream]::new($pending,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None,4096,[IO.FileOptions]::WriteThrough);try{$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()};[IO.File]::Move($pending,$full,$true)}finally{[Array]::Clear($bytes,0,$bytes.Length);if(Test-Path -LiteralPath $pending){Remove-Item -LiteralPath $pending -Force}}}
function Read-ProbeToken([string]$Path){$file=Existing $Path $false 'INTERNAL_PROBE_TOKEN_FILE_REQUIRED';$item=Get-Item -LiteralPath $file -Force;if($item.Length-lt32-or$item.Length-gt4096){throw 'INTERNAL_PROBE_TOKEN_FILE_INVALID'};$value=[IO.File]::ReadAllText($file).Trim();if($value.Length-lt32){throw 'INTERNAL_PROBE_TOKEN_INVALID'};return $value}
function Probe([int]$Port,[string]$Target,[string]$Status,[string]$ReleaseId,[string]$Token){try{$request=[Net.HttpWebRequest]::Create("http://127.0.0.1:$Port$Target");$request.Proxy=$null;$request.Timeout=1500;$request.Method='GET';if($Token){$request.Headers.Add('x-internal-probe-token',$Token)};$response=$request.GetResponse();try{$reader=New-Object IO.StreamReader($response.GetResponseStream());$body=$reader.ReadToEnd();if($body.Length-gt4096){return $false};$value=$body|ConvertFrom-Json;return [int]$response.StatusCode-eq200-and$value.status-eq$Status-and(-not$ReleaseId-or$value.releaseId-eq$ReleaseId)}finally{$response.Dispose()}}catch{return $false}}
function Wait-CoreHealth($Config,[string]$ReleaseId,[string]$Token,[int]$Seconds=60){$deadline=(Get-Date).AddSeconds($Seconds);do{if((Probe ([int]$Config.internalPorts.api) '/api/health/ready' 'ready' $null $Token)-and(Probe ([int]$Config.internalPorts.web) '/backend-api/health/live' 'live' $ReleaseId $null)){return};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw 'CORE_RELEASE_READY_FAILED'}
function Wait-State([string]$Name,[string]$State,[int]$Seconds=30){$deadline=(Get-Date).AddSeconds($Seconds);do{if((Get-Service -Name $Name -ErrorAction Stop).Status-eq$State){return};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw 'SERVICE_STATE_TIMEOUT'}
function Stop-Core{Stop-Service -Name $coreServiceId -ErrorAction Stop;Wait-State $coreServiceId 'Stopped'}
function Start-Core{Start-Service -Name $coreServiceId -ErrorAction Stop;Wait-State $coreServiceId 'Running'}
function Stop-Edge{Stop-Service -Name $edgeServiceId -ErrorAction Stop;Wait-State $edgeServiceId 'Stopped'}
function Start-Edge{Start-Service -Name $edgeServiceId -ErrorAction Stop;Wait-State $edgeServiceId 'Running'}
function Get-ServiceTreeIds([int]$RootId){$all=@(Get-CimInstance Win32_Process -ErrorAction Stop);$ids=[Collections.Generic.HashSet[int]]::new();[void]$ids.Add($RootId);do{$added=$false;foreach($item in $all){if(-not$ids.Contains([int]$item.ProcessId)-and$ids.Contains([int]$item.ParentProcessId)){[void]$ids.Add([int]$item.ProcessId);$added=$true}}}while($added);return @($ids)}
function Assert-ReleaseServiceIdentity([string]$ServiceId,[string]$ExpectedXml,[string]$ExpectedLauncher,[string]$ExpectedRelease,[string]$ExpectedRuntime,[string]$ExpectedApi){
  $deadline=(Get-Date).AddSeconds(30);do{$service=Get-CimInstance Win32_Service -Filter "Name='$ServiceId'" -ErrorAction Stop;if($service-and$service.State-ceq'Running'-and[int]$service.ProcessId-gt0){$tree=Get-ServiceTreeIds ([int]$service.ProcessId);$matches=@(Get-CimInstance Win32_Process -ErrorAction Stop|Where-Object{$tree-contains[int]$_.ProcessId-and$_.ExecutablePath-and[IO.Path]::GetFullPath([string]$_.ExecutablePath)-ieq[IO.Path]::GetFullPath($NodePath)-and[string]$_.CommandLine-and([string]$_.CommandLine).IndexOf([IO.Path]::GetFullPath($ExpectedLauncher),[StringComparison]::OrdinalIgnoreCase)-ge0});if($matches.Count-eq1){if($ServiceId-cne$edgeServiceId){break};$runtimeValue=Get-Content -Raw -LiteralPath $ExpectedRuntime|ConvertFrom-Json;$listeners=@(Get-NetTCPConnection -State Listen -LocalPort 443 -ErrorAction SilentlyContinue|Where-Object{[int]$_.OwningProcess-eq[int]$matches[0].ProcessId-and$_.LocalAddress-ceq[string]$runtimeValue.lan.bindAddress});if($listeners.Count-eq1){break}}};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline)
  if(-not$service-or$service.State-cne'Running'-or[int]$service.ProcessId-le0){throw 'RELEASE_SERVICE_PROCESS_IDENTITY_REJECTED'};if($matches.Count-ne1){throw 'RELEASE_NODE_PROCESS_IDENTITY_REJECTED'};if($ServiceId-ceq$edgeServiceId-and$listeners.Count-ne1){throw 'RELEASE_EDGE_LISTENER_IDENTITY_REJECTED'}
  $process=Get-Process -Id ([int]$matches[0].ProcessId) -ErrorAction Stop;$commandHash=Sha256Text ([string]$matches[0].CommandLine);$xmlHash=Sha256Text $ExpectedXml;$identity=Sha256Text (@('release-service-v1',$ServiceId,[string]$service.ProcessId,[string]$process.Id,$process.StartTime.ToUniversalTime().ToString('o'),(Hash $NodePath),$commandHash,$xmlHash,[IO.Path]::GetFullPath($ExpectedRelease),[IO.Path]::GetFullPath($ExpectedRuntime),$(if($ExpectedApi){[IO.Path]::GetFullPath($ExpectedApi)}else{''}))-join"`n")
  return [pscustomobject]@{serviceId=$ServiceId;serviceProcessId=[int]$service.ProcessId;nodeProcessId=$process.Id;nodeStartedAt=$process.StartTime.ToUniversalTime().ToString('o');nodeExecutableSha256=(Hash $NodePath);commandLineSha256=$commandHash;xmlSha256=$xmlHash;releaseRoot=[IO.Path]::GetFullPath($ExpectedRelease);runtimeConfigPath=[IO.Path]::GetFullPath($ExpectedRuntime);apiConfigPath=if($ExpectedApi){[IO.Path]::GetFullPath($ExpectedApi)}else{$null};identityDigest=$identity}
}
function Assert-Drain([string]$DataRoot){$statePath=Join-Path $DataRoot 'logs\edge\drain-state.json';$deadline=(Get-Date).AddMinutes(5);do{if(Test-Path -LiteralPath $statePath -PathType Leaf){$state=Get-Content -Raw -LiteralPath $statePath|ConvertFrom-Json;$completed=[datetime]::Parse([string]$state.completedAt).ToUniversalTime();if($state.version-eq1-and$state.result-eq'DRAINED'-and$state.activeRequests-eq0-and(Get-Process -Id ([int]$state.processId) -ErrorAction SilentlyContinue)-and$completed-gt(Get-Date).ToUniversalTime().AddSeconds(-30)){return}};Start-Sleep -Milliseconds 250}while((Get-Date)-lt$deadline);throw 'EDGE_DRAIN_TIMEOUT'}
function Validate-Compatibility([string]$Previous,[string]$Target,[string]$PreviousManifestHash,[string]$TargetManifestHash){if($Previous-eq$Target){return};$path=Existing $CompatibilityEvidencePath $false 'COMPATIBILITY_EVIDENCE_REQUIRED';$generator=Existing $CompatibilityGeneratorPath $false 'COMPATIBILITY_GENERATOR_REQUIRED';if($ExpectedCompatibilityEvidenceSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $path)-cne$ExpectedCompatibilityEvidenceSha256.ToLowerInvariant()){throw 'COMPATIBILITY_EVIDENCE_HASH_MISMATCH'};if($ExpectedCompatibilityGeneratorSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $generator)-cne$ExpectedCompatibilityGeneratorSha256.ToLowerInvariant()){throw 'COMPATIBILITY_GENERATOR_HASH_MISMATCH'};$filesystem=Get-Content -Raw -LiteralPath (Existing ([string]$targetRuntime.hostSecurity.filesystemEvidencePath) $false 'FILESYSTEM_EVIDENCE_REQUIRED')|ConvertFrom-Json;$latestPath=Existing ([string]$targetRuntime.backup.latestBackupEvidencePath) $false 'LATEST_BACKUP_EVIDENCE_REQUIRED';if(-not(UnderAny $path $filesystem.classRoots.ADMIN_EVIDENCE)-or-not(UnderAny $generator $filesystem.classRoots.SHARED_RUNTIME)-or-not(UnderAny $latestPath $filesystem.classRoots.BACKUP_RECEIPT)){throw 'COMPATIBILITY_FILESYSTEM_BOUNDARY_REJECTED'};$latest=Get-Content -Raw -LiteralPath $latestPath|ConvertFrom-Json;$e=Get-Content -Raw -LiteralPath $path|ConvertFrom-Json;$age=(Get-Date).ToUniversalTime()-[datetime]::Parse([string]$e.completedAt).ToUniversalTime();if($e.version-ne5-or$e.result-ne'PASS'-or$e.proofType-ne'release-compatibility'-or$e.generatorScriptSha256-cne(Hash $generator)-or$e.nodeSha256-cne$ExpectedNodeSha256.ToLowerInvariant()-or$e.attestationVerifierSha256-notmatch'^[0-9a-f]{64}$'-or$e.executorSetDigest-cne(Sha256Text (@($e.nodeSha256,$e.attestationVerifierSha256)-join"`n"))-or-not$e.backwardCompatible-or-not$e.rollbackCodeCompatible-or-not$e.previousMigrationChainUnchanged-or-not$e.additiveDeltaVerified-or-not$e.previousReleaseSmokeBeforeMigration-or-not$e.targetMigrationsAppliedToIsolatedRestore-or-not$e.previousReleaseSmokeAfterMigration-or-not$e.targetReleaseSmokeAfterMigration-or-not$e.isolatedRestoreVerified-or-not$e.authRoleMatrixVerified-or-not$e.businessKpiVerified-or-not$e.storageHashVerified-or-not$e.storageReferenceVerified-or-not$e.restoreTargetCleaned-or-not$e.freshBackupBound-or$e.latestBackupEvidenceSha256-cne(Hash $latestPath)-or$e.backupId-cne$latest.backupId-or$e.backupManifestSha256-cne$latest.manifestSha256-or$e.productionDatabaseMutated-or$e.previousMigrationDigest-ne$Previous-or$e.targetMigrationDigest-ne$Target-or$e.previousManifestSha256-ne$PreviousManifestHash-or$e.targetManifestSha256-ne$TargetManifestHash-or$e.restoreEvidenceSha256-notmatch'^[0-9a-f]{64}$'-or$e.restoreSigningKeyId-notmatch'^[0-9a-f]{64}$'-or$e.rehearsalEvidenceSha256-notmatch'^[0-9a-f]{64}$'-or$e.rehearsalSigningKeyId-notmatch'^[0-9a-f]{64}$'-or$age.TotalDays-gt30-or$age.TotalMinutes-lt-5){throw 'DATABASE_COMPATIBILITY_EVIDENCE_REJECTED'}}
function Validate-MigrationFinalized([string]$Previous,[string]$Target,[string]$TargetManifestHash){if($Previous-ceq$Target){return};$path=Existing $MigrationEvidencePath $false 'FINALIZED_MIGRATION_EVIDENCE_REQUIRED';if($ExpectedMigrationEvidenceSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $path)-cne$ExpectedMigrationEvidenceSha256.ToLowerInvariant()){throw 'FINALIZED_MIGRATION_EVIDENCE_HASH_MISMATCH'};$filesystem=Get-Content -Raw -LiteralPath (Existing ([string]$targetRuntime.hostSecurity.filesystemEvidencePath) $false 'FILESYSTEM_EVIDENCE_REQUIRED')|ConvertFrom-Json;if(-not(UnderAny $path $filesystem.classRoots.ADMIN_EVIDENCE)){throw 'FINALIZED_MIGRATION_EVIDENCE_BOUNDARY_REJECTED'};$e=Get-Content -Raw -LiteralPath $path|ConvertFrom-Json;if($e.version-ne4-or$e.result-cne'APPLIED'-or$e.provider-cne'supabase_postgres'-or$e.projectRef-cne$targetRuntime.database.projectRef-or$e.host-cne$targetRuntime.database.host-or$e.databaseName-cne$targetRuntime.database.name-or$e.databaseSchema-cne$targetRuntime.database.schema-or$e.previousMigrationDigest-cne$Previous-or$e.targetMigrationDigest-cne$Target-or$e.targetManifestSha256-cne$TargetManifestHash-or-not$e.maintenanceVerified-or-not$e.drainVerified-or$e.postBoundaryEvidenceSha256-notmatch'^[0-9a-f]{64}$'){throw 'FINALIZED_MIGRATION_EVIDENCE_REJECTED'}}

function New-ReleaseSwitchApprovalPlan([string]$IntendedAction){
  if($IntendedAction-notin@('Apply','Rollback','Finalize')){throw 'PLANNED_ACTION_REQUIRED'}
  if($ExpectedReleaseId-notmatch'^[a-z0-9][a-z0-9._-]{0,62}$'-or$ConfirmProjectRef-notmatch'^[a-z]{20}$'-or$ConfirmDatabaseHost-notmatch'^(?:db\.[a-z]{20}\.supabase\.co|[a-z0-9-]+\.pooler\.supabase\.com)$'-or$ConfirmDatabaseName-notmatch'^[a-z][a-z0-9_]{0,62}$'-or$ConfirmDatabaseSchema-notmatch'^[a-z][a-z0-9_]{0,62}$'){throw 'RELEASE_SWITCH_PLAN_IDENTITY_INVALID'}
  Assert-ApprovalOptionalArtifact $CompatibilityEvidencePath $ExpectedCompatibilityEvidenceSha256 'RELEASE_SWITCH_PLAN_COMPATIBILITY_PAIR_REQUIRED';Assert-ApprovalOptionalArtifact $CompatibilityGeneratorPath $ExpectedCompatibilityGeneratorSha256 'RELEASE_SWITCH_PLAN_COMPATIBILITY_GENERATOR_PAIR_REQUIRED';Assert-ApprovalOptionalArtifact $MigrationEvidencePath $ExpectedMigrationEvidenceSha256 'RELEASE_SWITCH_PLAN_MIGRATION_PAIR_REQUIRED'
  $parameters=[ordered]@{serviceRoot=(Get-ApprovalPath $ServiceRoot 'RELEASE_SWITCH_PLAN_SERVICE_ROOT_REQUIRED');coreServiceId=$coreServiceId;edgeServiceId=$edgeServiceId;targetReleaseId=$ExpectedReleaseId;targetReleaseRoot=(Get-ApprovalPath $TargetReleaseRoot 'RELEASE_SWITCH_PLAN_TARGET_ROOT_REQUIRED');targetManifestSha256=(Get-ApprovalHash $ExpectedReleaseManifestSha256 'RELEASE_SWITCH_PLAN_MANIFEST_HASH_REQUIRED');targetRuntimeConfigPath=(Get-ApprovalPath $TargetRuntimeConfigPath 'RELEASE_SWITCH_PLAN_RUNTIME_PATH_REQUIRED');targetRuntimeConfigSha256=(Get-ApprovalHash $ExpectedTargetRuntimeConfigSha256 'RELEASE_SWITCH_PLAN_RUNTIME_HASH_REQUIRED');targetApiConfigPath=(Get-ApprovalPath $TargetApiConfigPath 'RELEASE_SWITCH_PLAN_API_PATH_REQUIRED');targetApiConfigSha256=(Get-ApprovalHash $ExpectedTargetApiConfigSha256 'RELEASE_SWITCH_PLAN_API_HASH_REQUIRED');targetFileSystemEvidencePath=(Get-ApprovalPath $TargetFileSystemEvidencePath 'RELEASE_SWITCH_PLAN_FILESYSTEM_EVIDENCE_PATH_REQUIRED');targetFileSystemEvidenceSha256=(Get-ApprovalHash $ExpectedTargetFileSystemEvidenceSha256 'RELEASE_SWITCH_PLAN_FILESYSTEM_EVIDENCE_HASH_REQUIRED');coreLogRoot=(Get-ApprovalPath $CoreLogRoot 'RELEASE_SWITCH_PLAN_LOG_ROOT_REQUIRED');edgeLogRoot=(Get-ApprovalPath $EdgeLogRoot 'RELEASE_SWITCH_PLAN_EDGE_LOG_ROOT_REQUIRED');nodePath=(Get-ApprovalPath $NodePath 'RELEASE_SWITCH_PLAN_NODE_PATH_REQUIRED');nodeSha256=(Get-ApprovalHash $ExpectedNodeSha256 'RELEASE_SWITCH_PLAN_NODE_HASH_REQUIRED');releaseVerifierPath=(Get-ApprovalPath $ReleaseVerifierPath 'RELEASE_SWITCH_PLAN_RELEASE_VERIFIER_PATH_REQUIRED');releaseVerifierSha256=(Get-ApprovalHash $ExpectedReleaseVerifierSha256 'RELEASE_SWITCH_PLAN_RELEASE_VERIFIER_HASH_REQUIRED');runtimeReadinessVerifierPath=(Get-ApprovalPath $RuntimeReadinessVerifierPath 'RELEASE_SWITCH_PLAN_READINESS_VERIFIER_PATH_REQUIRED');runtimeReadinessVerifierSha256=(Get-ApprovalHash $ExpectedRuntimeReadinessVerifierSha256 'RELEASE_SWITCH_PLAN_READINESS_VERIFIER_HASH_REQUIRED');compatibilityEvidencePath=(Get-ApprovalOptionalPath $CompatibilityEvidencePath);compatibilityEvidenceSha256=(Get-ApprovalOptionalHash $ExpectedCompatibilityEvidenceSha256);compatibilityGeneratorPath=(Get-ApprovalOptionalPath $CompatibilityGeneratorPath);compatibilityGeneratorSha256=(Get-ApprovalOptionalHash $ExpectedCompatibilityGeneratorSha256);migrationEvidencePath=(Get-ApprovalOptionalPath $MigrationEvidencePath);migrationEvidenceSha256=(Get-ApprovalOptionalHash $ExpectedMigrationEvidenceSha256);internalProbeTokenFile=(Get-ApprovalPath $InternalProbeTokenFile 'RELEASE_SWITCH_PLAN_PROBE_PATH_REQUIRED');internalProbeTokenFileSha256=(Get-ApprovalHash $ExpectedInternalProbeTokenFileSha256 'RELEASE_SWITCH_PLAN_PROBE_HASH_REQUIRED');databaseProjectRef=$ConfirmProjectRef;databaseHost=$ConfirmDatabaseHost;databasePort=5432;databaseName=$ConfirmDatabaseName;databaseSchema=$ConfirmDatabaseSchema}
  $parameters.edgeDrainHelperPath=Get-ApprovalPath $edgeDrainHelper 'RELEASE_SWITCH_PLAN_DRAIN_HELPER_PATH_REQUIRED';$parameters.edgeDrainHelperSha256=Get-ApprovalHash $ExpectedEdgeDrainHelperSha256 'RELEASE_SWITCH_PLAN_DRAIN_HELPER_HASH_REQUIRED';$parameters.drainStatePath=Get-ApprovalPath $DrainStatePath 'RELEASE_SWITCH_PLAN_DRAIN_PATH_REQUIRED';$parameters.drainStateSha256=Get-ApprovalHash $ExpectedDrainStateSha256 'RELEASE_SWITCH_PLAN_DRAIN_HASH_REQUIRED';$parameters.attestationVerifierPath=Get-ApprovalPath $AttestationVerifierPath 'RELEASE_SWITCH_PLAN_ATTESTATION_PATH_REQUIRED';$parameters.attestationVerifierSha256=Get-ApprovalHash $ExpectedAttestationVerifierSha256 'RELEASE_SWITCH_PLAN_ATTESTATION_HASH_REQUIRED';$parameters.edgeSigningPublicKeyPath=Get-ApprovalPath $EdgeSigningPublicKeyPath 'RELEASE_SWITCH_PLAN_EDGE_PUBLIC_KEY_PATH_REQUIRED';$parameters.edgeSigningPublicKeySha256=Get-ApprovalHash $ExpectedEdgeSigningPublicKeySha256 'RELEASE_SWITCH_PLAN_EDGE_PUBLIC_KEY_HASH_REQUIRED';$parameters.httpsVerifierPath=Get-ApprovalPath $HttpsVerifierPath 'RELEASE_SWITCH_PLAN_HTTPS_PATH_REQUIRED';$parameters.httpsVerifierSha256=Get-ApprovalHash $ExpectedHttpsVerifierSha256 'RELEASE_SWITCH_PLAN_HTTPS_HASH_REQUIRED'
  $parameters.httpsCaCertificateSha256=Get-ApprovalHash $ExpectedHttpsCaCertificateSha256 'RELEASE_SWITCH_PLAN_HTTPS_CA_HASH_REQUIRED';$parameters.httpsServerCertificateSha256=Get-ApprovalHash $ExpectedHttpsServerCertificateSha256 'RELEASE_SWITCH_PLAN_HTTPS_SERVER_CERTIFICATE_HASH_REQUIRED'
  $planServiceRoot=Existing $ServiceRoot $true 'RELEASE_SWITCH_PLAN_SERVICE_ROOT_NOT_FOUND';$planCoreXml=Existing (Join-Path $planServiceRoot 'MetaAdsPerformanceCore.xml') $false 'RELEASE_SWITCH_PLAN_CORE_XML_REQUIRED';$planEdgeXml=Existing (Join-Path $planServiceRoot 'MetaAdsPerformanceEdge.xml') $false 'RELEASE_SWITCH_PLAN_EDGE_XML_REQUIRED';$planRuntime=Existing (EnvironmentValue $planEdgeXml 'LOCAL_RUNTIME_CONFIG_PATH') $false 'RELEASE_SWITCH_PLAN_CURRENT_RUNTIME_REQUIRED';$planApi=Existing (EnvironmentValue $planCoreXml 'CONFIG_PATH') $false 'RELEASE_SWITCH_PLAN_CURRENT_API_REQUIRED';$planRelease=Existing (ReleaseRootValue $planCoreXml) $true 'RELEASE_SWITCH_PLAN_CURRENT_RELEASE_REQUIRED';$planManifest=Existing (Join-Path $planRelease 'release-manifest.json') $false 'RELEASE_SWITCH_PLAN_CURRENT_MANIFEST_REQUIRED';$planNode=Existing $NodePath $false 'RELEASE_SWITCH_PLAN_NODE_NOT_FOUND';if((Hash $planNode)-cne$ExpectedNodeSha256.ToLowerInvariant()){throw 'RELEASE_SWITCH_PLAN_NODE_HASH_MISMATCH'};$currentCore=Assert-ReleaseServiceIdentity $coreServiceId (Get-Content -Raw -LiteralPath $planCoreXml) (Join-Path $planRelease 'deploy\local\launch-local-bundle.mjs') $planRelease $planRuntime $planApi;$currentEdge=Assert-ReleaseServiceIdentity $edgeServiceId (Get-Content -Raw -LiteralPath $planEdgeXml) (Join-Path $planRelease 'deploy\local\start-edge.mjs') $planRelease $planRuntime $null;$currentDrain=Assert-ExactEdgeDrainIdentity -EdgeServiceName $edgeServiceId -RuntimeConfigPath $planRuntime -ExpectedRuntimeConfigSha256 (Hash $planRuntime) -ReleaseRoot $planRelease -ExpectedReleaseManifestSha256 (Hash $planManifest) -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -DrainStatePath $DrainStatePath -ExpectedDrainStateSha256 $ExpectedDrainStateSha256 -AttestationVerifierPath $AttestationVerifierPath -ExpectedAttestationVerifierSha256 $ExpectedAttestationVerifierSha256 -EdgeSigningPublicKeyPath $EdgeSigningPublicKeyPath -ExpectedEdgeSigningPublicKeySha256 $ExpectedEdgeSigningPublicKeySha256
  $parameters.currentReleaseRoot=$planRelease;$parameters.currentManifestSha256=Hash $planManifest;$parameters.currentRuntimeConfigPath=$planRuntime;$parameters.currentRuntimeConfigSha256=Hash $planRuntime;$parameters.currentApiConfigPath=$planApi;$parameters.currentApiConfigSha256=Hash $planApi;$parameters.currentCoreXmlSha256=Hash $planCoreXml;$parameters.currentEdgeXmlSha256=Hash $planEdgeXml;$parameters.currentCoreIdentityDigest=$currentCore.identityDigest;$parameters.currentEdgeIdentityDigest=$currentEdge.identityDigest;$parameters.currentCoreNodeProcessId=$currentCore.nodeProcessId;$parameters.currentCoreNodeStartedAt=$currentCore.nodeStartedAt;$parameters.currentEdgeNodeProcessId=$currentEdge.nodeProcessId;$parameters.currentEdgeNodeStartedAt=$currentEdge.nodeStartedAt;$parameters.currentDrainIdentityDigest=$currentDrain.IdentityDigest;$parameters.currentDrainEdgeProcessId=$currentDrain.EdgeProcessId;$parameters.currentDrainEdgeProcessStartedAt=$currentDrain.EdgeProcessStartedAt;$parameters.currentDrainListenerAddress=$currentDrain.ListenerAddress;$parameters.currentDrainListenerPort=$currentDrain.ListenerPort;$parameters.currentDrainCompletedAt=$currentDrain.DrainCompletedAt
  if($IntendedAction-in@('Rollback','Finalize')){$parameters.releaseSwitchJournalPath=Get-ApprovalPath $ReleaseSwitchJournalPath 'RELEASE_SWITCH_PLAN_JOURNAL_PATH_REQUIRED';$parameters.releaseSwitchJournalSha256=Get-ApprovalHash $ExpectedReleaseSwitchJournalSha256 'RELEASE_SWITCH_PLAN_JOURNAL_HASH_REQUIRED'}
  $target="Exact Core and HTTPS Edge release $ExpectedReleaseId against Supabase $ConfirmProjectRef/$ConfirmDatabaseHost`:5432/$ConfirmDatabaseName schema $ConfirmDatabaseSchema"
  $impact=if($IntendedAction-eq'Apply'){'Under maintenance and a fresh drain, stops exact Edge and Core services, atomically switches runtime/API and both XML generations, restarts Core then Edge, and verifies exact process/release identity'}elseif($IntendedAction-eq'Rollback'){'Stops exact Edge and Core, restores the journal-bound prior XML/runtime/API generation for both, restarts Core then Edge, and verifies the previous release'}else{'Deletes only the verified release-switch journal and both services rollback artifacts after successful target verification'}
  $rollback=if($IntendedAction-eq'Apply'){'Use a separately approved Rollback plan bound to the exact prior artifacts; legacy 3100/4100 are never targeted'}elseif($IntendedAction-eq'Rollback'){'Re-apply only through a new approved Apply plan'}else{'Finalize removes local rollback artifacts; recover from the separately verified release/recovery kit and database backup'}
  return New-ApprovalPlan $PSCommandPath $IntendedAction $parameters $target $impact $rollback
}

if($Action-eq'Plan'){New-ReleaseSwitchApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0}
$releaseMutation=if($Action-in@('Apply','Rollback','Finalize')){$Action}else{$null};$approvedReleasePlan=$null;if($releaseMutation){$approvedReleasePlan=New-ReleaseSwitchApprovalPlan $releaseMutation;Assert-ApprovedPlan $approvedReleasePlan ([bool]$Approved) $ApprovedPlanSha256}

$serviceRoot=Existing $ServiceRoot $true 'SERVICE_ROOT_NOT_FOUND';$activeXml=Join-Path $serviceRoot 'MetaAdsPerformanceCore.xml';$edgeXml=Join-Path $serviceRoot 'MetaAdsPerformanceEdge.xml';$previousXml="$activeXml.previous";$previousEdgeXml="$edgeXml.previous";$journalPath=Join-Path $serviceRoot 'release-switch.json'
if($Action-in@('Rollback','Finalize')){if([IO.Path]::GetFullPath($ReleaseSwitchJournalPath)-ine[IO.Path]::GetFullPath($journalPath)){throw 'RELEASE_SWITCH_JOURNAL_PATH_MISMATCH'};if((Hash (Existing $journalPath $false 'RELEASE_SWITCH_JOURNAL_NOT_FOUND'))-cne$ExpectedReleaseSwitchJournalSha256.ToLowerInvariant()){throw 'RELEASE_SWITCH_JOURNAL_HASH_MISMATCH'}}
$activeRuntime=if(Test-Path -LiteralPath $edgeXml){EnvironmentValue $edgeXml 'LOCAL_RUNTIME_CONFIG_PATH'}else{$null};$activeApi=if(Test-Path -LiteralPath $activeXml){EnvironmentValue $activeXml 'CONFIG_PATH'}else{$null}
$probeTokenPath=Existing $InternalProbeTokenFile $false 'INTERNAL_PROBE_TOKEN_FILE_REQUIRED';if((Hash $probeTokenPath)-cne$ExpectedInternalProbeTokenFileSha256.ToLowerInvariant()){throw 'INTERNAL_PROBE_TOKEN_FILE_HASH_MISMATCH'};$probeToken=Read-ProbeToken $probeTokenPath

if($Action-eq'Rollback'){
  foreach($file in @($previousXml,$previousEdgeXml,$journalPath,"$activeRuntime.previous","$activeApi.previous")){Existing $file $false 'RELEASE_ROLLBACK_NOT_AVAILABLE'|Out-Null}
  $journal=Get-Content -Raw -LiteralPath $journalPath|ConvertFrom-Json
  if((Hash $previousXml)-cne$journal.previousXmlSha256-or(Hash $previousEdgeXml)-cne$journal.previousEdgeXmlSha256-or(Hash "$activeRuntime.previous")-cne$journal.previousRuntimeSha256-or(Hash "$activeApi.previous")-cne$journal.previousApiSha256){throw 'ROLLBACK_ARTIFACT_HASH_MISMATCH'}
  $node=Existing $NodePath $false 'NODE_BINARY_NOT_FOUND';$verifier=Existing $ReleaseVerifierPath $false 'RELEASE_VERIFIER_NOT_FOUND';if($ExpectedNodeSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $node)-cne$ExpectedNodeSha256.ToLowerInvariant()){throw 'NODE_HASH_MISMATCH'};if($ExpectedReleaseVerifierSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $verifier)-cne$ExpectedReleaseVerifierSha256.ToLowerInvariant()){throw 'RELEASE_VERIFIER_HASH_MISMATCH'}
  $previousConfig=Get-Content -Raw -LiteralPath "$activeRuntime.previous"|ConvertFrom-Json;$previousFs=Get-Content -Raw -LiteralPath (Existing ([string]$previousConfig.hostSecurity.filesystemEvidencePath) $false 'FILESYSTEM_EVIDENCE_REQUIRED')|ConvertFrom-Json;if(-not(UnderAny $node $previousFs.classRoots.SHARED_RUNTIME)-or-not(UnderAny $verifier $previousFs.classRoots.SHARED_RUNTIME)){throw 'ROLLBACK_EXECUTOR_OUTSIDE_SHARED_RUNTIME'}
  $previousReleaseRoot=Existing ([string]$journal.previousReleaseRoot) $true 'PREVIOUS_RELEASE_NOT_FOUND';&$node $verifier "--root=$previousReleaseRoot" "--manifest-sha256=$($journal.previousManifestSha256)"|Out-Null;if($LASTEXITCODE-ne0){throw 'PREVIOUS_RELEASE_VERIFICATION_FAILED'}
  $currentReleaseRoot=Existing (ReleaseRootValue $activeXml) $true 'CURRENT_RELEASE_NOT_FOUND';$currentCoreIdentity=Assert-ReleaseServiceIdentity $coreServiceId (Get-Content -Raw -LiteralPath $activeXml) (Join-Path $currentReleaseRoot 'deploy\local\launch-local-bundle.mjs') $currentReleaseRoot $activeRuntime $activeApi;$currentEdgeIdentity=Assert-ReleaseServiceIdentity $edgeServiceId (Get-Content -Raw -LiteralPath $edgeXml) (Join-Path $currentReleaseRoot 'deploy\local\start-edge.mjs') $currentReleaseRoot $activeRuntime $null;if($currentCoreIdentity.identityDigest-cne$approvedReleasePlan.exactParameters.currentCoreIdentityDigest-or$currentEdgeIdentity.identityDigest-cne$approvedReleasePlan.exactParameters.currentEdgeIdentityDigest){throw 'RELEASE_ROLLBACK_CURRENT_IDENTITY_DRIFT'}
  $dataRoot=Resolve-DataRoot ((Get-Content -Raw -LiteralPath "$activeRuntime.previous"|ConvertFrom-Json).data.root);if(-not(Test-Path -LiteralPath (Join-Path $dataRoot 'runtime-control\maintenance.enabled') -PathType Leaf)){throw 'MAINTENANCE_REQUIRED'};$actionDrain=Assert-ExactEdgeDrainIdentity -EdgeServiceName $edgeServiceId -RuntimeConfigPath $activeRuntime -ExpectedRuntimeConfigSha256 (Hash $activeRuntime) -ReleaseRoot $currentReleaseRoot -ExpectedReleaseManifestSha256 (Hash (Join-Path $currentReleaseRoot 'release-manifest.json')) -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -DrainStatePath $DrainStatePath -ExpectedDrainStateSha256 $ExpectedDrainStateSha256 -AttestationVerifierPath $AttestationVerifierPath -ExpectedAttestationVerifierSha256 $ExpectedAttestationVerifierSha256 -EdgeSigningPublicKeyPath $EdgeSigningPublicKeyPath -ExpectedEdgeSigningPublicKeySha256 $ExpectedEdgeSigningPublicKeySha256;if($actionDrain.IdentityDigest-cne$approvedReleasePlan.exactParameters.currentDrainIdentityDigest){throw 'RELEASE_ROLLBACK_DRAIN_IDENTITY_DRIFT'}
  $rollbackStartCoreXml=Get-Content -Raw -LiteralPath $activeXml;$rollbackStartEdgeXml=Get-Content -Raw -LiteralPath $edgeXml;$rollbackStartRuntime=Get-Content -Raw -LiteralPath $activeRuntime;$rollbackStartApi=Get-Content -Raw -LiteralPath $activeApi;$rollbackStartConfig=$rollbackStartRuntime|ConvertFrom-Json
  try{Stop-Edge;Stop-Core;Atomic-ReplaceText $activeRuntime (Get-Content -Raw -LiteralPath "$activeRuntime.previous");Atomic-ReplaceText $activeApi (Get-Content -Raw -LiteralPath "$activeApi.previous");Atomic-ReplaceText $activeXml (Get-Content -Raw -LiteralPath $previousXml);Atomic-ReplaceText $edgeXml (Get-Content -Raw -LiteralPath $previousEdgeXml);Start-Core;$previousConfig=Get-Content -Raw -LiteralPath $activeRuntime|ConvertFrom-Json;Wait-CoreHealth $previousConfig $journal.previousReleaseId $probeToken;Start-Edge;$coreIdentity=Assert-ReleaseServiceIdentity $coreServiceId (Get-Content -Raw -LiteralPath $activeXml) (Join-Path $previousReleaseRoot 'deploy\local\launch-local-bundle.mjs') $previousReleaseRoot $activeRuntime $activeApi;$edgeIdentity=Assert-ReleaseServiceIdentity $edgeServiceId (Get-Content -Raw -LiteralPath $edgeXml) (Join-Path $previousReleaseRoot 'deploy\local\start-edge.mjs') $previousReleaseRoot $activeRuntime $null;[void](Assert-ExactHttpsReleaseProbe -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -VerifierPath $HttpsVerifierPath -ExpectedVerifierSha256 $ExpectedHttpsVerifierSha256 -RuntimeConfigPath $activeRuntime -ExpectedRuntimeConfigSha256 (Hash $activeRuntime) -ExpectedReleaseId $journal.previousReleaseId -ExpectedStatus 503)}catch{try{if((Get-Service -Name $edgeServiceId).Status-ne'Stopped'){Stop-Edge};if((Get-Service -Name $coreServiceId).Status-ne'Stopped'){Stop-Core};Atomic-ReplaceText $activeRuntime $rollbackStartRuntime;Atomic-ReplaceText $activeApi $rollbackStartApi;Atomic-ReplaceText $activeXml $rollbackStartCoreXml;Atomic-ReplaceText $edgeXml $rollbackStartEdgeXml;Start-Core;Wait-CoreHealth $rollbackStartConfig $rollbackStartConfig.release.id $probeToken;Start-Edge;[void](Assert-ReleaseServiceIdentity $coreServiceId $rollbackStartCoreXml (Join-Path $currentReleaseRoot 'deploy\local\launch-local-bundle.mjs') $currentReleaseRoot $activeRuntime $activeApi);[void](Assert-ReleaseServiceIdentity $edgeServiceId $rollbackStartEdgeXml (Join-Path $currentReleaseRoot 'deploy\local\start-edge.mjs') $currentReleaseRoot $activeRuntime $null);[void](Assert-ExactHttpsReleaseProbe -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -VerifierPath $HttpsVerifierPath -ExpectedVerifierSha256 $ExpectedHttpsVerifierSha256 -RuntimeConfigPath $activeRuntime -ExpectedRuntimeConfigSha256 (Hash $activeRuntime) -ExpectedReleaseId $rollbackStartConfig.release.id -ExpectedStatus 503)}catch{throw 'RELEASE_ROLLBACK_AND_TARGET_RECOVERY_FAILED'};throw 'RELEASE_ROLLBACK_FAILED_TARGET_RECOVERED'}
  [pscustomobject]@{Result='ROLLED_BACK';ReleaseId=$journal.previousReleaseId;MaintenanceStillEnabled=$true;CoreIdentityDigest=$coreIdentity.identityDigest;EdgeIdentityDigest=$edgeIdentity.identityDigest;EdgeRestarted=$true;LegacyProcessesChanged=$false}|ConvertTo-Json;exit 0
}

$node=Existing $NodePath $false 'NODE_BINARY_NOT_FOUND';$verifier=Existing $ReleaseVerifierPath $false 'RELEASE_VERIFIER_NOT_FOUND';$readinessVerifier=Existing $RuntimeReadinessVerifierPath $false 'RUNTIME_READINESS_VERIFIER_NOT_FOUND';if($ExpectedNodeSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $node)-cne$ExpectedNodeSha256.ToLowerInvariant()){throw 'NODE_HASH_MISMATCH'};if($ExpectedReleaseVerifierSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $verifier)-cne$ExpectedReleaseVerifierSha256.ToLowerInvariant()){throw 'RELEASE_VERIFIER_HASH_MISMATCH'};if($ExpectedRuntimeReadinessVerifierSha256-notmatch'^[0-9a-f]{64}$'-or(Hash $readinessVerifier)-cne$ExpectedRuntimeReadinessVerifierSha256.ToLowerInvariant()){throw 'RUNTIME_READINESS_VERIFIER_HASH_MISMATCH'}
$targetRoot=Existing $TargetReleaseRoot $true 'TARGET_RELEASE_NOT_FOUND';$targetRuntimePath=Existing $TargetRuntimeConfigPath $false 'TARGET_RUNTIME_CONFIG_NOT_FOUND';$targetApiPath=Existing $TargetApiConfigPath $false 'TARGET_API_CONFIG_NOT_FOUND';$logRoot=Existing $CoreLogRoot $true 'CORE_LOG_ROOT_NOT_FOUND';$edgeLog=Existing $EdgeLogRoot $true 'EDGE_LOG_ROOT_NOT_FOUND'
if((Hash $targetRuntimePath)-cne$ExpectedTargetRuntimeConfigSha256.ToLowerInvariant()-or(Hash $targetApiPath)-cne$ExpectedTargetApiConfigSha256.ToLowerInvariant()){throw 'TARGET_CONFIG_HASH_MISMATCH'}
if($ExpectedReleaseManifestSha256-notmatch'^[0-9a-f]{64}$'){throw 'RELEASE_MANIFEST_HASH_INVALID'}
&$node $verifier "--root=$targetRoot" "--manifest-sha256=$ExpectedReleaseManifestSha256"|Out-Null;if($LASTEXITCODE-ne0){throw 'RELEASE_VERIFICATION_FAILED'}
$manifest=Get-Content -Raw -LiteralPath (Join-Path $targetRoot 'release-manifest.json')|ConvertFrom-Json;$targetRuntime=Get-Content -Raw -LiteralPath $targetRuntimePath|ConvertFrom-Json
if([IO.Path]::GetFullPath($HttpsVerifierPath)-ine[IO.Path]::GetFullPath((Join-Path $targetRoot 'deploy\local\verify-https-release.mjs'))-or$manifest.files.'deploy/local/verify-https-release.mjs'-cne$ExpectedHttpsVerifierSha256.ToLowerInvariant()){throw 'HTTPS_VERIFIER_NOT_BOUND_TO_TARGET_RELEASE'}
$targetFsPath=Existing $TargetFileSystemEvidencePath $false 'TARGET_FILESYSTEM_EVIDENCE_REQUIRED';if((Hash $targetFsPath)-cne$ExpectedTargetFileSystemEvidenceSha256.ToLowerInvariant()-or[IO.Path]::GetFullPath([string]$targetRuntime.hostSecurity.filesystemEvidencePath)-ine$targetFsPath){throw 'TARGET_FILESYSTEM_EVIDENCE_MISMATCH'}
if($targetRuntime.release.id-cne$ExpectedReleaseId-or$targetRuntime.release.id-ne$manifest.releaseId-or$targetRuntime.release.migrationDigest-ne$manifest.migrationDigest-or$targetRuntime.database.projectRef-cne$ConfirmProjectRef-or$targetRuntime.database.host-cne$ConfirmDatabaseHost-or$targetRuntime.database.name-cne$ConfirmDatabaseName-or$targetRuntime.database.schema-cne$ConfirmDatabaseSchema){throw 'RELEASE_RUNTIME_IDENTITY_MISMATCH'}
Assert-EdgeDrainPinned ([string]$targetRuntime.tls.caCertificatePath) $ExpectedHttpsCaCertificateSha256 'HTTPS_PROBE_CA_HASH_MISMATCH';Assert-EdgeDrainPinned ([string]$targetRuntime.tls.serverCertificatePath) $ExpectedHttpsServerCertificateSha256 'HTTPS_PROBE_SERVER_CERTIFICATE_HASH_MISMATCH'
$currentRuntimeForBoundary=if($activeRuntime-and(Test-Path -LiteralPath $activeRuntime -PathType Leaf)){Get-Content -Raw -LiteralPath $activeRuntime|ConvertFrom-Json}else{$null}
if($currentRuntimeForBoundary-and(EdgeImmutable $currentRuntimeForBoundary)-cne(EdgeImmutable $targetRuntime)){throw 'EDGE_IMMUTABLE_CONFIG_CHANGE_REQUIRES_SEPARATE_WORKFLOW'}
Assert-FilesystemCoverage $targetRuntime $targetRuntimePath $targetApiPath $targetRoot $node $verifier $logRoot $edgeLog
$targetFilesystem=Get-Content -Raw -LiteralPath $targetFsPath|ConvertFrom-Json;if(-not(UnderAny $readinessVerifier $targetFilesystem.classRoots.SHARED_RUNTIME)){throw 'RUNTIME_READINESS_VERIFIER_OUTSIDE_SHARED_RUNTIME'}
&$node $readinessVerifier "--runtime-config=$targetRuntimePath" "--release-root=$targetRoot" '--mode=operational' 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw 'TARGET_OPERATIONAL_READINESS_FAILED'}
$targetCoreLauncher=Join-Path $targetRoot 'deploy\local\launch-local-bundle.mjs';$targetEdgeLauncher=Join-Path $targetRoot 'deploy\local\start-edge.mjs';$targetXml=CoreXml $node $targetCoreLauncher $targetRoot $activeRuntime $activeApi $logRoot;$targetEdgeXml=EdgeXml $node $targetEdgeLauncher $targetRoot $activeRuntime $edgeLog
$core=Get-Service -Name $coreServiceId -ErrorAction SilentlyContinue;$edge=Get-Service -Name $edgeServiceId -ErrorAction SilentlyContinue

if($Action-eq'Verify'-or$Action-eq'Finalize'){
  if(-not$core-or$core.Status-ne'Running'-or-not$edge-or$edge.Status-ne'Running'-or(Get-Content -Raw -LiteralPath $activeXml)-cne$targetXml-or(Get-Content -Raw -LiteralPath $edgeXml)-cne$targetEdgeXml){throw 'ACTIVE_RELEASE_VERIFY_FAILED'}
  Wait-CoreHealth (Get-Content -Raw -LiteralPath $activeRuntime|ConvertFrom-Json) $manifest.releaseId $probeToken
  $coreIdentity=Assert-ReleaseServiceIdentity $coreServiceId $targetXml $targetCoreLauncher $targetRoot $activeRuntime $activeApi;$edgeIdentity=Assert-ReleaseServiceIdentity $edgeServiceId $targetEdgeXml $targetEdgeLauncher $targetRoot $activeRuntime $null;[void](Assert-ExactHttpsReleaseProbe -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -VerifierPath $HttpsVerifierPath -ExpectedVerifierSha256 $ExpectedHttpsVerifierSha256 -RuntimeConfigPath $activeRuntime -ExpectedRuntimeConfigSha256 (Hash $activeRuntime) -ExpectedReleaseId $manifest.releaseId -ExpectedStatus 503)
  if(Test-Path -LiteralPath $journalPath -PathType Leaf){$activeJournal=Get-Content -Raw -LiteralPath $journalPath|ConvertFrom-Json;if($activeJournal.version-ne4-or$activeJournal.targetReleaseId-cne$manifest.releaseId-or$activeJournal.targetManifestSha256-cne$ExpectedReleaseManifestSha256.ToLowerInvariant()-or$activeJournal.targetCoreXmlSha256-cne(Sha256Text $targetXml)-or$activeJournal.targetEdgeXmlSha256-cne(Sha256Text $targetEdgeXml)-or$activeJournal.targetCoreIdentityDigest-cne$coreIdentity.identityDigest-or$activeJournal.targetEdgeIdentityDigest-cne$edgeIdentity.identityDigest-or[int]$activeJournal.targetCoreNodeProcessId-ne[int]$coreIdentity.nodeProcessId-or[int]$activeJournal.targetEdgeNodeProcessId-ne[int]$edgeIdentity.nodeProcessId){throw 'RELEASE_SWITCH_JOURNAL_IDENTITY_MISMATCH'}}
  if($activeJournal-and($activeJournal.currentDrainIdentityDigest-notmatch'^[a-f0-9]{64}$'-or$activeJournal.currentDrainStateSha256-notmatch'^[a-f0-9]{64}$'-or[int]$activeJournal.currentDrainEdgeProcessId-le0-or-not$activeJournal.currentDrainEdgeProcessStartedAt-or$activeJournal.currentDrainListenerAddress-cne$targetRuntime.lan.bindAddress-or$activeJournal.currentDrainListenerPort-ne443-or-not$activeJournal.signedFreshDrainVerified)){throw 'RELEASE_SWITCH_JOURNAL_DRAIN_IDENTITY_MISMATCH'}
  if($Action-eq'Finalize'){foreach($file in @($previousXml,$previousEdgeXml,"$activeRuntime.previous","$activeApi.previous",$journalPath)){if(Test-Path -LiteralPath $file){Remove-Item -LiteralPath $file -Force}}}
  [pscustomobject]@{Result=if($Action-eq'Finalize'){'FINALIZED'}else{'PASS'};ReleaseId=$manifest.releaseId;CoreRunning=$true;EdgeRunning=$true;CoreIdentityDigest=$coreIdentity.identityDigest;EdgeIdentityDigest=$edgeIdentity.identityDigest;RollbackAvailable=(Test-Path -LiteralPath $journalPath)}|ConvertTo-Json;exit 0
}

if(-not$core-or-not$edge-or$core.Status-ne'Running'-or$edge.Status-ne'Running'-or-not(Test-Path -LiteralPath $activeXml -PathType Leaf)){throw 'CORE_EDGE_SERVICES_NOT_READY'}
foreach($file in @($previousXml,$previousEdgeXml,"$activeRuntime.previous","$activeApi.previous",$journalPath)){if(Test-Path -LiteralPath $file){throw 'UNFINISHED_RELEASE_SWITCH_PRESENT'}}
$currentRuntime=Get-Content -Raw -LiteralPath $activeRuntime|ConvertFrom-Json;$dataRoot=Resolve-DataRoot $currentRuntime.data.root
if(-not(Test-Path -LiteralPath (Join-Path $dataRoot 'runtime-control\maintenance.enabled') -PathType Leaf)){throw 'MAINTENANCE_REQUIRED'};$actionDrain=Assert-ExactEdgeDrainIdentity -EdgeServiceName $edgeServiceId -RuntimeConfigPath $activeRuntime -ExpectedRuntimeConfigSha256 (Hash $activeRuntime) -ReleaseRoot (ReleaseRootValue $activeXml) -ExpectedReleaseManifestSha256 (Hash (Join-Path (ReleaseRootValue $activeXml) 'release-manifest.json')) -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -DrainStatePath $DrainStatePath -ExpectedDrainStateSha256 $ExpectedDrainStateSha256 -AttestationVerifierPath $AttestationVerifierPath -ExpectedAttestationVerifierSha256 $ExpectedAttestationVerifierSha256 -EdgeSigningPublicKeyPath $EdgeSigningPublicKeyPath -ExpectedEdgeSigningPublicKeySha256 $ExpectedEdgeSigningPublicKeySha256;if($actionDrain.IdentityDigest-cne$approvedReleasePlan.exactParameters.currentDrainIdentityDigest){throw 'RELEASE_APPLY_DRAIN_IDENTITY_DRIFT'}
  $previousReleaseRoot=Existing (ReleaseRootValue $activeXml) $true 'PREVIOUS_RELEASE_NOT_FOUND';$previousManifestPath=Existing (Join-Path $previousReleaseRoot 'release-manifest.json') $false 'PREVIOUS_RELEASE_MANIFEST_NOT_FOUND';$previousManifestSha256=Hash $previousManifestPath
  &$node $verifier "--root=$previousReleaseRoot" "--manifest-sha256=$previousManifestSha256"|Out-Null;if($LASTEXITCODE-ne0){throw 'PREVIOUS_RELEASE_VERIFICATION_FAILED'}
  Assert-FilesystemCoverage $currentRuntime $activeRuntime $activeApi $previousReleaseRoot $node $verifier $logRoot $edgeLog
  Validate-Compatibility $currentRuntime.release.migrationDigest $manifest.migrationDigest $previousManifestSha256 $ExpectedReleaseManifestSha256.ToLowerInvariant()
  Validate-MigrationFinalized $currentRuntime.release.migrationDigest $manifest.migrationDigest $ExpectedReleaseManifestSha256.ToLowerInvariant()
Atomic-ReplaceText $previousXml (Get-Content -Raw -LiteralPath $activeXml);Atomic-ReplaceText $previousEdgeXml (Get-Content -Raw -LiteralPath $edgeXml);Atomic-ReplaceText "$activeRuntime.previous" (Get-Content -Raw -LiteralPath $activeRuntime);Atomic-ReplaceText "$activeApi.previous" (Get-Content -Raw -LiteralPath $activeApi)
$priorCoreIdentity=Assert-ReleaseServiceIdentity $coreServiceId (Get-Content -Raw -LiteralPath $activeXml) (Join-Path $previousReleaseRoot 'deploy\local\launch-local-bundle.mjs') $previousReleaseRoot $activeRuntime $activeApi;$priorEdgeIdentity=Assert-ReleaseServiceIdentity $edgeServiceId (Get-Content -Raw -LiteralPath $edgeXml) (Join-Path $previousReleaseRoot 'deploy\local\start-edge.mjs') $previousReleaseRoot $activeRuntime $null
if($priorCoreIdentity.identityDigest-cne$approvedReleasePlan.exactParameters.currentCoreIdentityDigest-or$priorEdgeIdentity.identityDigest-cne$approvedReleasePlan.exactParameters.currentEdgeIdentityDigest){throw 'RELEASE_APPLY_CURRENT_IDENTITY_DRIFT'}
$journal=[ordered]@{version=4;previousReleaseId=$currentRuntime.release.id;previousMigrationDigest=$currentRuntime.release.migrationDigest;previousReleaseRoot=$previousReleaseRoot;previousManifestSha256=$previousManifestSha256;previousXmlSha256=Hash $previousXml;previousEdgeXmlSha256=Hash $previousEdgeXml;previousRuntimeSha256=Hash "$activeRuntime.previous";previousApiSha256=Hash "$activeApi.previous";previousCoreIdentityDigest=$priorCoreIdentity.identityDigest;previousEdgeIdentityDigest=$priorEdgeIdentity.identityDigest;targetReleaseId=$manifest.releaseId;targetManifestSha256=$ExpectedReleaseManifestSha256.ToLowerInvariant();targetCoreXmlSha256=Sha256Text $targetXml;targetEdgeXmlSha256=Sha256Text $targetEdgeXml;switchedAt=(Get-Date).ToUniversalTime().ToString('o')}
$journal['currentDrainIdentityDigest']=$actionDrain.IdentityDigest;$journal['currentDrainStateSha256']=$actionDrain.DrainStateSha256;$journal['currentDrainEdgeProcessId']=$actionDrain.EdgeProcessId;$journal['currentDrainEdgeProcessStartedAt']=$actionDrain.EdgeProcessStartedAt;$journal['currentDrainListenerAddress']=$actionDrain.ListenerAddress;$journal['currentDrainListenerPort']=$actionDrain.ListenerPort;$journal['currentDrainCompletedAt']=$actionDrain.DrainCompletedAt;$journal['signedFreshDrainVerified']=$true
Atomic-ReplaceText $journalPath ($journal|ConvertTo-Json -Depth 4)
try{Stop-Edge;Stop-Core;Atomic-ReplaceText $activeRuntime (Get-Content -Raw -LiteralPath $targetRuntimePath);Atomic-ReplaceText $activeApi (Get-Content -Raw -LiteralPath $targetApiPath);Atomic-ReplaceText $activeXml $targetXml;Atomic-ReplaceText $edgeXml $targetEdgeXml;Start-Core;Wait-CoreHealth $targetRuntime $manifest.releaseId $probeToken;Start-Edge;$coreIdentity=Assert-ReleaseServiceIdentity $coreServiceId $targetXml $targetCoreLauncher $targetRoot $activeRuntime $activeApi;$edgeIdentity=Assert-ReleaseServiceIdentity $edgeServiceId $targetEdgeXml $targetEdgeLauncher $targetRoot $activeRuntime $null;[void](Assert-ExactHttpsReleaseProbe -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -VerifierPath $HttpsVerifierPath -ExpectedVerifierSha256 $ExpectedHttpsVerifierSha256 -RuntimeConfigPath $activeRuntime -ExpectedRuntimeConfigSha256 (Hash $activeRuntime) -ExpectedReleaseId $manifest.releaseId -ExpectedStatus 503)}catch{try{if((Get-Service -Name $edgeServiceId).Status-ne'Stopped'){Stop-Edge};if((Get-Service -Name $coreServiceId).Status-ne'Stopped'){Stop-Core};Atomic-ReplaceText $activeRuntime (Get-Content -Raw -LiteralPath "$activeRuntime.previous");Atomic-ReplaceText $activeApi (Get-Content -Raw -LiteralPath "$activeApi.previous");Atomic-ReplaceText $activeXml (Get-Content -Raw -LiteralPath $previousXml);Atomic-ReplaceText $edgeXml (Get-Content -Raw -LiteralPath $previousEdgeXml);Start-Core;Wait-CoreHealth $currentRuntime $currentRuntime.release.id $probeToken;Start-Edge;[void](Assert-ReleaseServiceIdentity $coreServiceId (Get-Content -Raw -LiteralPath $activeXml) (Join-Path $previousReleaseRoot 'deploy\local\launch-local-bundle.mjs') $previousReleaseRoot $activeRuntime $activeApi);[void](Assert-ReleaseServiceIdentity $edgeServiceId (Get-Content -Raw -LiteralPath $edgeXml) (Join-Path $previousReleaseRoot 'deploy\local\start-edge.mjs') $previousReleaseRoot $activeRuntime $null);[void](Assert-ExactHttpsReleaseProbe -NodePath $NodePath -ExpectedNodeSha256 $ExpectedNodeSha256 -VerifierPath $HttpsVerifierPath -ExpectedVerifierSha256 $ExpectedHttpsVerifierSha256 -RuntimeConfigPath $activeRuntime -ExpectedRuntimeConfigSha256 (Hash $activeRuntime) -ExpectedReleaseId $currentRuntime.release.id -ExpectedStatus 503)}catch{throw 'RELEASE_SWITCH_AND_AUTOMATIC_ROLLBACK_FAILED'};throw 'RELEASE_SWITCH_ROLLED_BACK'}
$journal['targetCoreIdentityDigest']=$coreIdentity.identityDigest;$journal['targetCoreNodeProcessId']=$coreIdentity.nodeProcessId;$journal['targetCoreNodeStartedAt']=$coreIdentity.nodeStartedAt;$journal['targetEdgeIdentityDigest']=$edgeIdentity.identityDigest;$journal['targetEdgeNodeProcessId']=$edgeIdentity.nodeProcessId;$journal['targetEdgeNodeStartedAt']=$edgeIdentity.nodeStartedAt;$journal['completedAt']=(Get-Date).ToUniversalTime().ToString('o');Atomic-ReplaceText $journalPath ($journal|ConvertTo-Json -Depth 6)
[pscustomobject]@{Result='APPLIED';ReleaseId=$manifest.releaseId;RollbackAvailable=$true;MaintenanceStillEnabled=$true;CoreIdentityDigest=$coreIdentity.identityDigest;EdgeIdentityDigest=$edgeIdentity.identityDigest;CoreRestarted=$true;EdgeRestarted=$true;LegacyProcessesChanged=$false}|ConvertTo-Json
