#Requires -Version 7.2
[CmdletBinding()]
param(
  [ValidateSet('Plan','Verify')][string]$Action='Plan',[string]$RuntimeConfigPath,[string]$ExpectedRuntimeConfigSha256,
  [string]$BackupTaskName='Meta Ads Performance Daily Backup',
  [string]$ReceiptTaskName='Meta Ads Performance Backup Receipt Publisher',
  [string]$InternalProbeTokenFile,[string]$ExpectedInternalProbeTokenSha256,[string]$ExpectedBackupScheduleEvidenceSha256,
  [string]$NodePath,[string]$ExpectedNodeSha256,[string]$ReleaseRoot,
  [string]$RuntimeReadinessVerifierPath,[string]$ExpectedRuntimeReadinessVerifierSha256,
  [string]$HttpsVerifierPath,[string]$ExpectedHttpsVerifierSha256,
  [string]$HostInstanceHelperPath,[string]$ExpectedHostInstanceHelperSha256,
  [string]$BackupAccount,[string]$SignerAccount,[string]$PrincipalRightsEvidencePath,[string]$ExpectedPrincipalRightsEvidenceSha256,[string]$PrincipalRightsScriptPath,[string]$ExpectedPrincipalRightsScriptSha256,[string]$EvidenceOutputPath,
  [ValidateSet('VerifyEvidence')][string]$PlannedAction,[string]$ApprovedPlanSha256,[string]$ApprovalNonce,[string]$ApprovalIssuedAt,[string]$ApprovalExpiresAt,[string]$ApprovalInstanceId,[string]$ApprovalLedgerPath,[switch]$Approved
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'approval-plan.ps1')
function Descendants([int]$RootPid){$all=@(Get-CimInstance Win32_Process);$ids=New-Object 'System.Collections.Generic.HashSet[int]';$ids.Add($RootPid)|Out-Null;do{$changed=$false;foreach($process in $all){if($ids.Contains([int]$process.ParentProcessId)-and-not$ids.Contains([int]$process.ProcessId)){$ids.Add([int]$process.ProcessId)|Out-Null;$changed=$true}}}while($changed);return $ids}
function Digest([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function FileHash([string]$Path){return(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Resolve-DataRoot($Value){if($Value){return [IO.Path]::GetFullPath([string]$Value)};$base=if($env:ProgramData){$env:ProgramData}else{$env:LOCALAPPDATA};if(-not$base){throw 'OS_APPLICATION_DATA_ROOT_UNAVAILABLE'};return [IO.Path]::GetFullPath((Join-Path $base 'MetaAdsPerformance'))}
function Under([string]$Candidate,[string[]]$Roots){$full=[IO.Path]::GetFullPath($Candidate);return @($Roots|Where-Object{$root=[IO.Path]::GetFullPath([string]$_).TrimEnd('\');$full-ieq$root-or$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)}).Count-gt0}
function Write-AtomicEvidence([string]$Path,$Value){$output=[IO.Path]::GetFullPath($Path);$parent=Split-Path -Parent $output;if(-not(Test-Path -LiteralPath $parent -PathType Container)){throw 'REBOOT_EVIDENCE_PARENT_REQUIRED'};$cursor=Get-Item -LiteralPath $parent -Force;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'REBOOT_EVIDENCE_REPARSE_REJECTED'};$cursor=$cursor.Parent};if(Test-Path -LiteralPath $output){$existing=Get-Item -LiteralPath $output -Force;if($existing.Attributes-band[IO.FileAttributes]::ReparsePoint-or$existing.PSIsContainer){throw 'REBOOT_EVIDENCE_PATH_INVALID'}};$temporary=Join-Path $parent ('.reboot-evidence-'+[guid]::NewGuid().ToString('N')+'.tmp');$stream=$null;$writer=$null;try{$stream=[IO.File]::Open($temporary,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$writer=[IO.StreamWriter]::new($stream,(New-Object Text.UTF8Encoding($false)),4096,$true);$writer.Write(($Value|ConvertTo-Json -Depth 12));$writer.Flush();$stream.Flush($true);$writer.Dispose();$writer=$null;$stream.Dispose();$stream=$null;[IO.File]::Move($temporary,$output,$true)}finally{if($writer){$writer.Dispose()};if($stream){$stream.Dispose()};if(Test-Path -LiteralPath $temporary){Remove-Item -LiteralPath $temporary -Force}}}
function AssertHash([string]$Path,[string]$Expected,[string]$Code){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)-or$Expected-notmatch'^[A-Fa-f0-9]{64}$'-or(FileHash $Path)-cne$Expected.ToLowerInvariant()){throw $Code}}
function Assert-Listener([int]$Port,[string]$Address,$Owners,[string]$Code){$listeners=@(Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue);if($listeners.Count-ne1-or$listeners[0].LocalAddress-ne$Address-or-not$Owners.Contains([int]$listeners[0].OwningProcess)){throw $Code}}
function ApiReady([int]$Port,[string]$Token){try{$request=[Net.HttpWebRequest]::Create("http://127.0.0.1:$Port/api/health/ready");$request.Proxy=$null;$request.Timeout=5000;$request.Headers.Add('x-internal-probe-token',$Token);$response=$request.GetResponse();try{$reader=New-Object IO.StreamReader($response.GetResponseStream());$value=($reader.ReadToEnd()|ConvertFrom-Json);return [int]$response.StatusCode-eq200-and$value.status-eq'ready'}finally{$response.Dispose()}}catch{return $false}}
function New-RebootApprovalPlan([string]$IntendedAction){if($IntendedAction-cne'VerifyEvidence'){throw 'REBOOT_PLAN_ACTION_REQUIRED'};$p=[ordered]@{runtimeConfigPath=Get-ApprovalPath $RuntimeConfigPath 'REBOOT_PLAN_RUNTIME_PATH_REQUIRED';runtimeConfigSha256=Get-ApprovalHash $ExpectedRuntimeConfigSha256 'REBOOT_PLAN_RUNTIME_HASH_REQUIRED';backupTaskName=$BackupTaskName;receiptTaskName=$ReceiptTaskName;internalProbeTokenFile=Get-ApprovalPath $InternalProbeTokenFile 'REBOOT_PLAN_TOKEN_PATH_REQUIRED';internalProbeTokenSha256=Get-ApprovalHash $ExpectedInternalProbeTokenSha256 'REBOOT_PLAN_TOKEN_HASH_REQUIRED';backupScheduleEvidenceSha256=Get-ApprovalHash $ExpectedBackupScheduleEvidenceSha256 'REBOOT_PLAN_SCHEDULE_HASH_REQUIRED';nodePath=Get-ApprovalPath $NodePath 'REBOOT_PLAN_NODE_PATH_REQUIRED';nodeSha256=Get-ApprovalHash $ExpectedNodeSha256 'REBOOT_PLAN_NODE_HASH_REQUIRED';releaseRoot=Get-ApprovalPath $ReleaseRoot 'REBOOT_PLAN_RELEASE_ROOT_REQUIRED';runtimeReadinessVerifierPath=Get-ApprovalPath $RuntimeReadinessVerifierPath 'REBOOT_PLAN_RUNTIME_VERIFIER_PATH_REQUIRED';runtimeReadinessVerifierSha256=Get-ApprovalHash $ExpectedRuntimeReadinessVerifierSha256 'REBOOT_PLAN_RUNTIME_VERIFIER_HASH_REQUIRED';httpsVerifierPath=Get-ApprovalPath $HttpsVerifierPath 'REBOOT_PLAN_HTTPS_VERIFIER_PATH_REQUIRED';httpsVerifierSha256=Get-ApprovalHash $ExpectedHttpsVerifierSha256 'REBOOT_PLAN_HTTPS_VERIFIER_HASH_REQUIRED';hostInstanceHelperPath=Get-ApprovalPath $HostInstanceHelperPath 'REBOOT_PLAN_HOST_HELPER_PATH_REQUIRED';hostInstanceHelperSha256=Get-ApprovalHash $ExpectedHostInstanceHelperSha256 'REBOOT_PLAN_HOST_HELPER_HASH_REQUIRED';backupAccount=Get-ApprovalText $BackupAccount '^.{1,256}$' 'REBOOT_PLAN_BACKUP_ACCOUNT_REQUIRED';signerAccount=Get-ApprovalText $SignerAccount '^.{1,256}$' 'REBOOT_PLAN_SIGNER_ACCOUNT_REQUIRED';principalRightsEvidencePath=Get-ApprovalPath $PrincipalRightsEvidencePath 'REBOOT_PLAN_RIGHTS_EVIDENCE_PATH_REQUIRED';principalRightsEvidenceSha256=Get-ApprovalHash $ExpectedPrincipalRightsEvidenceSha256 'REBOOT_PLAN_RIGHTS_EVIDENCE_HASH_REQUIRED';principalRightsScriptPath=Get-ApprovalPath $PrincipalRightsScriptPath 'REBOOT_PLAN_RIGHTS_SCRIPT_PATH_REQUIRED';principalRightsScriptSha256=Get-ApprovalHash $ExpectedPrincipalRightsScriptSha256 'REBOOT_PLAN_RIGHTS_SCRIPT_HASH_REQUIRED';evidenceOutputPath=Get-ApprovalPath $EvidenceOutputPath 'REBOOT_PLAN_OUTPUT_REQUIRED'};New-ApprovalPlan $PSCommandPath 'VerifyEvidence' $p 'Exact post-reboot Core service, stopped fail-closed Edge, Supabase readiness, backup tasks, helper pins, and evidence output' 'Performs read-only post-reboot pre-edge checks and atomically replaces only the approved non-secret reboot receipt after all checks pass' 'Keep Edge stopped; restore the prior exact reboot receipt from the protected evidence backup or repeat this approved verification'}
if($Action-eq'Plan'){New-RebootApprovalPlan $PlannedAction|ConvertTo-Json -Depth 12;exit 0};if($EvidenceOutputPath){$approvalPlan=New-RebootApprovalPlan 'VerifyEvidence';Assert-ApprovedPlan $approvalPlan ([bool]$Approved) $ApprovedPlanSha256}
$configPath=if(Test-Path -LiteralPath $RuntimeConfigPath -PathType Leaf){[IO.Path]::GetFullPath($RuntimeConfigPath)}else{throw 'RUNTIME_CONFIG_NOT_FOUND'};$config=Get-Content -Raw -LiteralPath $configPath|ConvertFrom-Json
AssertHash $configPath $ExpectedRuntimeConfigSha256 'RUNTIME_CONFIG_HASH_MISMATCH'
if($EvidenceOutputPath){$runtimeEvidencePath=if($config.hostSecurity.rebootEvidencePath){[IO.Path]::GetFullPath([string]$config.hostSecurity.rebootEvidencePath)}else{throw 'RUNTIME_REBOOT_EVIDENCE_PATH_REQUIRED'};$approvedEvidencePath=[IO.Path]::GetFullPath($EvidenceOutputPath);if($approvedEvidencePath-ine$runtimeEvidencePath){throw 'REBOOT_EVIDENCE_OUTPUT_PATH_MISMATCH'};$filesystemEvidencePath=if(Test-Path -LiteralPath $config.hostSecurity.filesystemEvidencePath -PathType Leaf){[IO.Path]::GetFullPath([string]$config.hostSecurity.filesystemEvidencePath)}else{throw 'FILESYSTEM_EVIDENCE_NOT_FOUND'};$filesystemEvidence=Get-Content -Raw -LiteralPath $filesystemEvidencePath|ConvertFrom-Json;if($filesystemEvidence.result-ne'PASS'-or-not$filesystemEvidence.exactAcl-or-not(Under $approvedEvidencePath @($filesystemEvidence.classRoots.ADMIN_EVIDENCE))){throw 'REBOOT_EVIDENCE_ADMIN_CLASS_REQUIRED'}}
AssertHash $NodePath $ExpectedNodeSha256 'NODE_HASH_MISMATCH';AssertHash $RuntimeReadinessVerifierPath $ExpectedRuntimeReadinessVerifierSha256 'RUNTIME_READINESS_VERIFIER_HASH_MISMATCH';AssertHash $HttpsVerifierPath $ExpectedHttpsVerifierSha256 'HTTPS_VERIFIER_HASH_MISMATCH'
AssertHash $HostInstanceHelperPath $ExpectedHostInstanceHelperSha256 'HOST_INSTANCE_HELPER_HASH_MISMATCH';. (Import-PinnedHelperScriptBlock $HostInstanceHelperPath $ExpectedHostInstanceHelperSha256 'HOST_INSTANCE_HELPER_HASH_MISMATCH')
if(-not(Test-Path -LiteralPath $ReleaseRoot -PathType Container)){throw 'RELEASE_ROOT_NOT_FOUND'};$releaseRootFull=[IO.Path]::GetFullPath($ReleaseRoot);$releaseManifestPath=Join-Path $releaseRootFull 'release-manifest.json';if(-not(Test-Path -LiteralPath $releaseManifestPath -PathType Leaf)){throw 'RELEASE_MANIFEST_NOT_FOUND'};$releaseManifest=Get-Content -Raw -LiteralPath $releaseManifestPath|ConvertFrom-Json
$preEdgeVerification=[bool]$EvidenceOutputPath;$readinessMode=if($preEdgeVerification){if($config.lan.enabled){'pre-edge'}else{'core-prepared'}}elseif($config.lan.enabled){'operational'}else{'core-prepared'};&$NodePath $RuntimeReadinessVerifierPath "--runtime-config=$configPath" "--release-root=$releaseRootFull" "--mode=$readinessMode" 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw 'SIGNED_RUNTIME_READINESS_FAILED'}
$core=Get-CimInstance Win32_Service -Filter "Name='MetaAdsPerformanceCore'" -ErrorAction SilentlyContinue;$edge=Get-CimInstance Win32_Service -Filter "Name='MetaAdsPerformanceEdge'" -ErrorAction SilentlyContinue
if(-not$core-or$core.StartMode-ne'Auto'-or$core.State-ne'Running'-or[int]$core.ProcessId-le0){throw 'AUTOMATIC_SERVICE_NOT_RECOVERED'}
if(-not$edge){throw 'EDGE_SERVICE_NOT_INSTALLED'};if($config.lan.enabled-and-not$preEdgeVerification){if($edge.StartMode-ne'Auto'-or$edge.State-ne'Running'-or[int]$edge.ProcessId-le0){throw 'AUTOMATIC_EDGE_NOT_RECOVERED'}}elseif($edge.StartMode-ne'Manual'-or$edge.State-ne'Stopped'-or[int]$edge.ProcessId-ne0){throw 'PRE_EDGE_STOPPED_STATE_INVALID'}
$coreOwners=Descendants ([int]$core.ProcessId);$edgeOwners=if($config.lan.enabled-and-not$preEdgeVerification){Descendants ([int]$edge.ProcessId)}else{New-Object 'System.Collections.Generic.HashSet[int]'}
Assert-Listener ([int]$config.internalPorts.web) '127.0.0.1' $coreOwners 'WEB_LISTENER_OWNERSHIP_FAILED'
Assert-Listener ([int]$config.internalPorts.api) '127.0.0.1' $coreOwners 'API_LISTENER_OWNERSHIP_FAILED'
AssertHash $InternalProbeTokenFile $ExpectedInternalProbeTokenSha256 'INTERNAL_PROBE_TOKEN_HASH_MISMATCH';$probeToken=[IO.File]::ReadAllText([IO.Path]::GetFullPath($InternalProbeTokenFile)).Trim();if($probeToken.Length-lt32-or-not(ApiReady ([int]$config.internalPorts.api) $probeToken)){throw 'API_READY_FAILED'}
foreach($forbiddenPort in @(3100,4100,5432,55432,6543)){if(Get-NetTCPConnection -LocalPort $forbiddenPort -State Listen -ErrorAction SilentlyContinue){throw 'FORBIDDEN_PORT_LISTENER_PRESENT'}}
$edgeListeners=@(Get-NetTCPConnection -LocalPort 443 -State Listen -ErrorAction SilentlyContinue)
if($config.lan.enabled-and-not$preEdgeVerification){if($edgeListeners.Count-ne1-or$edgeListeners[0].LocalAddress-ne$config.lan.bindAddress-or-not$edgeOwners.Contains([int]$edgeListeners[0].OwningProcess)){throw 'HTTPS_EDGE_LISTENER_OWNERSHIP_FAILED'};&$NodePath $HttpsVerifierPath "--connect-address=$($config.lan.bindAddress)" "--hostname=$($config.lan.hostname)" "--ca=$($config.tls.caCertificatePath)" "--certificate=$($config.tls.serverCertificatePath)" "--release-id=$($config.release.id)" '--expected-status=200' 2>$null|Out-Null;if($LASTEXITCODE-ne0){throw 'HTTPS_RELEASE_OR_PINNED_TRUST_VERIFY_FAILED'}}elseif($edgeListeners.Count){throw 'PRE_EDGE_HTTPS_LISTENER_PRESENT'}
$task=Get-ScheduledTask -TaskName $BackupTaskName -ErrorAction SilentlyContinue;$receiptTask=Get-ScheduledTask -TaskName $ReceiptTaskName -ErrorAction SilentlyContinue;if($config.backup.root-and(-not$task-or-not$receiptTask-or$task.State-eq'Disabled'-or$receiptTask.State-eq'Disabled'-or-not$task.Settings.StartWhenAvailable-or-not$receiptTask.Settings.StartWhenAvailable-or$task.Settings.ExecutionTimeLimit-ne'PT4H'-or$receiptTask.Settings.ExecutionTimeLimit-ne'PT4H')){throw 'BACKUP_TASK_NOT_READY'}
$schedule=if($config.backup.scheduledTaskEvidencePath){Get-Content -Raw -LiteralPath $config.backup.scheduledTaskEvidencePath|ConvertFrom-Json}else{$null}
if($config.backup.root){AssertHash $config.backup.scheduledTaskEvidencePath $ExpectedBackupScheduleEvidenceSha256 'BACKUP_SCHEDULE_EVIDENCE_HASH_MISMATCH';if(-not$schedule-or$schedule.version-ne8-or$schedule.scheduledAuthorizationVersion-ne4-or-not$schedule.scheduledAuthorizationBound-or-not$schedule.receiptSigningDelegatedToDistinctSigner-or-not$schedule.receiptPublisherRecurringVerified-or$schedule.receiptPublisherIntervalMinutes-ne15-or$schedule.result-ne'PASS'-or-not$schedule.dailyTriggerVerified-or-not$schedule.dailyTriggerEnabled-or$schedule.daysInterval-ne1-or$schedule.taskName-cne$BackupTaskName-or$schedule.receiptTaskName-cne$ReceiptTaskName-or@($task.Actions).Count-ne1-or[IO.Path]::GetFullPath([string]$task.Actions[0].Execute)-ine[IO.Path]::GetFullPath([string]$schedule.powerShellPath)-or(FileHash ([string]$task.Actions[0].Execute))-cne$schedule.powerShellSha256-or(Digest ([string]$task.Actions[0].Arguments))-cne$schedule.actionArgumentsSha256-or@($task.Triggers).Count-ne1-or[string]$task.Triggers[0].CimClass.CimClassName-cne'MSFT_TaskDailyTrigger'-or-not[bool]$task.Triggers[0].Enabled-or[int]$task.Triggers[0].DaysInterval-ne1-or([datetime]$task.Triggers[0].StartBoundary).TimeOfDay-ne[datetime]::ParseExact([string]$schedule.dailyTime,'HH:mm',$null).TimeOfDay-or@($receiptTask.Actions).Count-ne1-or[IO.Path]::GetFullPath([string]$receiptTask.Actions[0].Execute)-ine[IO.Path]::GetFullPath([string]$schedule.powerShellPath)-or(Digest ([string]$receiptTask.Actions[0].Arguments))-cne$schedule.receiptPublisherActionArgumentsSha256-or@($receiptTask.Triggers).Count-ne1-or[string]$receiptTask.Triggers[0].CimClass.CimClassName-cne'MSFT_TaskDailyTrigger'-or-not[bool]$receiptTask.Triggers[0].Enabled-or[string]$receiptTask.Triggers[0].Repetition.Interval-cne'PT15M'-or[string]$receiptTask.Triggers[0].Repetition.Duration-cne'P1D'){throw 'BACKUP_TASK_EXACT_CONFIGURATION_MISMATCH'}}
AssertHash $PrincipalRightsEvidencePath $ExpectedPrincipalRightsEvidenceSha256 'PRINCIPAL_RIGHTS_EVIDENCE_HASH_MISMATCH';$rights=Get-Content -Raw -LiteralPath $PrincipalRightsEvidencePath|ConvertFrom-Json;$boot=(Get-CimInstance Win32_OperatingSystem).LastBootUpTime.ToUniversalTime();$rightsAt=[datetime]::Parse([string]$rights.completedAt).ToUniversalTime()
$coreSid=([Security.Principal.NTAccount]$core.StartName).Translate([Security.Principal.SecurityIdentifier]).Value;$edgeSid=([Security.Principal.NTAccount]$edge.StartName).Translate([Security.Principal.SecurityIdentifier]).Value
$backupSid=([Security.Principal.NTAccount]$BackupAccount).Translate([Security.Principal.SecurityIdentifier]).Value
$signerSid=([Security.Principal.NTAccount]$SignerAccount).Translate([Security.Principal.SecurityIdentifier]).Value
if($rights.version-ne4-or$rights.result-ne'PASS'-or-not$rights.exactRights-or$rightsAt-lt$boot-or$rights.corePrincipalDigest-cne(Digest $coreSid)-or$rights.edgePrincipalDigest-cne(Digest $edgeSid)-or$rights.backupPrincipalDigest-cne(Digest $backupSid)-or$rights.signerPrincipalDigest-cne(Digest $signerSid)){throw 'POST_REBOOT_PRINCIPAL_RIGHTS_NOT_VERIFIED'}
if($ExpectedPrincipalRightsScriptSha256-notmatch'^[A-Fa-f0-9]{64}$'-or(Get-FileHash -LiteralPath $PrincipalRightsScriptPath -Algorithm SHA256).Hash-ine$ExpectedPrincipalRightsScriptSha256){throw 'PRINCIPAL_RIGHTS_SCRIPT_HASH_MISMATCH'}
if($task-and([Security.Principal.NTAccount]$task.Principal.UserId).Translate([Security.Principal.SecurityIdentifier]).Value-ne$backupSid){throw 'BACKUP_TASK_PRINCIPAL_MISMATCH'}
if($receiptTask-and([Security.Principal.NTAccount]$receiptTask.Principal.UserId).Translate([Security.Principal.SecurityIdentifier]).Value-ne$signerSid){throw 'BACKUP_RECEIPT_TASK_PRINCIPAL_MISMATCH'}
&$PrincipalRightsScriptPath -Action Verify -CoreServiceAccount ([string]$core.StartName) -EdgeServiceAccount ([string]$edge.StartName) -BackupAccount $BackupAccount -SignerAccount $SignerAccount 2>$null|Out-Null
$latest=if($config.backup.latestBackupEvidencePath){Get-Content -Raw -LiteralPath $config.backup.latestBackupEvidencePath|ConvertFrom-Json}else{$null};if($config.backup.root-and(-not$latest-or$latest.result-ne'COMPLETE'-or[datetime]::Parse([string]$latest.completedAt).ToUniversalTime()-lt(Get-Date).ToUniversalTime().AddHours(-24))){throw 'LATEST_BACKUP_NOT_FRESH'}
$manifestHash=FileHash $releaseManifestPath;if($releaseManifest.version-ne4-or$releaseManifest.releaseId-cne$config.release.id-or$releaseManifest.migrationDigest-cne$config.release.migrationDigest-or$releaseManifest.appliedMigrationDigest-cne$config.release.appliedMigrationDigest){throw 'RELEASE_MANIFEST_CONFIG_MISMATCH'};if($config.backup.root-and($schedule.releaseManifestSha256-cne$manifestHash)){throw 'RELEASE_MANIFEST_SCHEDULE_MISMATCH'}
$dataRoot=Resolve-DataRoot $config.data.root;$backupRoot=if($config.backup.root){[IO.Path]::GetFullPath([string]$config.backup.root)}else{''};$rebootContract=Digest (@('reboot-core-v2',[string]$config.deploymentMode,[string]$config.internalPorts.web,[string]$config.internalPorts.api,[string]$config.database.provider,[string]$config.database.projectRef,[string]$config.database.connectionMode,[string]$config.database.host,[string]$config.database.port,[string]$config.database.name,[string]$config.database.runtimeUser,[string]$config.database.schema,[string]$config.database.caCertificateSha256,$dataRoot,[string]$config.release.id,[string]$config.release.migrationDigest,[string]$config.release.appliedMigrationDigest,$backupRoot,[string]$config.backup.dailyTime,[string]$config.backup.rpoHours,[string]$config.backup.rtoHours,[string]$config.hostSecurity.nodeProgramSha256,[string]$config.hostSecurity.edgeServiceSid)-join"`n")
$completed=(Get-Date).ToUniversalTime();$result=[ordered]@{version=3;result='PASS';mode=if($config.lan.enabled){'PRE_EDGE_LAN'}else{'CORE_ONLY_CLI_BOOTSTRAP'};readinessMode=$readinessMode;releaseId=[string]$config.release.id;migrationDigest=[string]$config.release.migrationDigest;appliedMigrationDigest=[string]$config.release.appliedMigrationDigest;releaseManifestSha256=$manifestHash;sourceRuntimeConfigSha256=(FileHash $configPath);rebootContractFingerprint=$rebootContract;hostInstanceDigest=(Get-StableHostInstanceDigest);coreAutomatic=$true;edgeAutomatic=$false;edgeStoppedFailClosed=$true;supabaseDatabaseReadyAfterBoot=$true;principalRightsVerifiedAfterBoot=$true;listenerOwnershipVerified=$true;loopbackInternalPorts=$true;httpsReleaseVerified=$false;pinnedCaAndSniVerified=$false;forbiddenPortListenersAbsent=$true;backupTaskReady=[bool]$config.backup.root;backupTaskExactConfigurationVerified=[bool]$config.backup.root;backupDailyTriggerEnabled=[bool]$config.backup.root;backupScheduleEvidenceSha256=if($config.backup.root){FileHash $config.backup.scheduledTaskEvidencePath}else{$null};signedRuntimeReadinessVerified=$true;latestBackupFresh=[bool]$config.backup.root;bootedAt=$boot.ToString('o');completedAt=$completed.ToString('o')}
if($EvidenceOutputPath){Write-AtomicEvidence $EvidenceOutputPath $result}
$result|ConvertTo-Json
