import { Prisma } from "@prisma/client";
import { AdMetricImportInput, AdsetAggregateInput, MetricImportInput } from "./upload-contracts";
import { decimalOrNull } from "./upload-keys";

export function adDailyMetricCreateData(input: AdMetricImportInput, importVersion: number) {
  return {
    uploadBatchId: input.batchId,
    uploadRowId: input.uploadRowId,
    campaignRefId: input.campaignRefId,
    metaAdsetRefId: input.metaAdsetRefId,
    metaAdRefId: input.metaAdRefId,
    creativeId: input.creativeId,
    metricDate: input.parsedRow.metricDate,
    dateStart: input.parsedRow.dateStart,
    dateEnd: input.parsedRow.dateEnd,
    metaCampaignId: input.parsedRow.metaCampaignId,
    campaignNameSnapshot: input.parsedRow.campaignName,
    metaAdsetId: input.parsedRow.metaAdsetExternalId,
    adsetNameSnapshot: input.parsedRow.adsetName,
    metaAdId: input.parsedRow.metaAdId,
    syntheticAdKey: input.parsedRow.syntheticAdKey,
    adIdentityKey: input.parsedRow.adIdentityKey,
    adNameSnapshot: input.parsedRow.adName,
    adDeliveryStatus: input.parsedRow.adDeliveryStatus,
    attributionSetting: input.parsedRow.attributionSetting,
    resultIndicator: input.parsedRow.resultIndicator,
    resultCount: input.parsedRow.resultCount,
    purchaseCount: input.parsedRow.purchaseCount,
    reach: input.parsedRow.reach,
    videoPlay3sCount: input.parsedRow.videoPlay3sCount,
    videoPlay25Count: input.parsedRow.videoPlay25Count,
    videoPlay50Count: input.parsedRow.videoPlay50Count,
    videoPlay75Count: input.parsedRow.videoPlay75Count,
    videoPlay100Count: input.parsedRow.videoPlay100Count,
    addToCartCount: input.parsedRow.addToCartCount,
    frequency: decimalOrNull(input.parsedRow.frequency),
    costPerResultUsd: decimalOrNull(input.parsedRow.costPerResultUsd),
    adsetBudgetLabel: input.parsedRow.adsetBudgetLabel,
    adsetBudgetType: input.parsedRow.adsetBudgetType,
    spendUsd: new Prisma.Decimal(input.parsedRow.spendUsd),
    endStatus: input.parsedRow.endStatus,
    qualityRanking: input.parsedRow.qualityRanking,
    engagementRateRanking: input.parsedRow.engagementRateRanking,
    conversionRateRanking: input.parsedRow.conversionRateRanking,
    impressions: BigInt(input.parsedRow.impressions),
    cpmUsd: decimalOrNull(input.parsedRow.cpmUsd),
    linkClicks: input.parsedRow.linkClicks,
    shopClicks: input.parsedRow.shopClicks,
    cpcLinkUsd: decimalOrNull(input.parsedRow.cpcLinkUsd),
    ctrLinkPct: decimalOrNull(input.parsedRow.ctrLinkPct),
    clicksAll: input.parsedRow.clicksAll,
    ctrAllPct: decimalOrNull(input.parsedRow.ctrAllPct),
    cpcAllUsd: decimalOrNull(input.parsedRow.cpcAllUsd),
    landingPageViews: input.parsedRow.landingPageViews,
    costPerLandingPageViewUsd: decimalOrNull(input.parsedRow.costPerLandingPageViewUsd),
    productId: input.productId,
    stage: input.stage,
    productMatchSource: input.productMatchSource,
    stageMatchSource: input.stageMatchSource,
    productMatchRuleId: input.productMatchRuleId,
    importVersion,
    isCurrent: true,
    supersededByMetricId: null,
    rawRow: input.rawRow as Prisma.InputJsonObject
  };
}

export function adsetMetricCreateData(input: MetricImportInput, importVersion: number) {
  return {
    uploadBatchId: input.batchId,
    uploadRowId: input.uploadRowId,
    metaAdsetId: input.metaAdsetId,
    metricDate: input.parsedRow.metricDate,
    dateStart: input.parsedRow.dateStart,
    dateEnd: input.parsedRow.dateEnd,
    adsetName: input.parsedRow.adsetName,
    adsetNameKey: input.parsedRow.adsetNameKey,
    deliveryStatus: input.parsedRow.deliveryStatus,
    attributionSetting: input.parsedRow.attributionSetting,
    resultCount: input.parsedRow.resultCount,
    resultIndicator: input.parsedRow.resultIndicator,
    reach: input.parsedRow.reach,
    frequency: decimalOrNull(input.parsedRow.frequency),
    costPerResultUsd: decimalOrNull(input.parsedRow.costPerResultUsd),
    adsetBudgetLabel: input.parsedRow.adsetBudgetLabel,
    adsetBudgetType: input.parsedRow.adsetBudgetType,
    spendUsd: new Prisma.Decimal(input.parsedRow.spendUsd),
    endStatus: input.parsedRow.endStatus,
    startDate: input.parsedRow.startDate,
    impressions: BigInt(input.parsedRow.impressions),
    cpmUsd: decimalOrNull(input.parsedRow.cpmUsd),
    linkClicks: input.parsedRow.linkClicks,
    shopClicks: input.parsedRow.shopClicks,
    cpcLinkUsd: decimalOrNull(input.parsedRow.cpcLinkUsd),
    ctrLinkPct: decimalOrNull(input.parsedRow.ctrLinkPct),
    clicksAll: input.parsedRow.clicksAll,
    ctrAllPct: decimalOrNull(input.parsedRow.ctrAllPct),
    cpcAllUsd: decimalOrNull(input.parsedRow.cpcAllUsd),
    landingPageViews: input.parsedRow.landingPageViews,
    costPerLandingPageViewUsd: decimalOrNull(input.parsedRow.costPerLandingPageViewUsd),
    productId: input.productId,
    stage: input.stage,
    productMatchSource: input.productMatchSource,
    stageMatchSource: input.stageMatchSource,
    productMatchRuleId: input.productMatchRuleId,
    importVersion,
    isCurrent: true,
    supersededByMetricId: null,
    rawRow: input.rawRow as Prisma.InputJsonObject
  };
}

export function adsetAggregateMetricCreateData(batchId: string, input: AdsetAggregateInput, importVersion: number) {
  return {
    uploadBatchId: batchId,
    uploadRowId: null,
    metaAdsetId: input.metaAdsetId,
    metricDate: input.metricDate,
    dateStart: input.dateStart,
    dateEnd: input.dateEnd,
    adsetName: input.adsetName,
    adsetNameKey: input.adsetNameKey,
    deliveryStatus: input.deliveryStatus,
    attributionSetting: input.attributionSetting,
    resultCount: input.purchaseCount,
    resultIndicator: input.resultIndicator,
    reach: input.reach,
    frequency: decimalOrNull(input.frequency),
    costPerResultUsd: decimalOrNull(input.costPerResultUsd),
    adsetBudgetLabel: input.adsetBudgetLabel,
    adsetBudgetType: input.adsetBudgetType,
    spendUsd: new Prisma.Decimal(input.spendUsd),
    endStatus: input.endStatus,
    startDate: null,
    impressions: BigInt(input.impressions),
    cpmUsd: decimalOrNull(input.cpmUsd),
    linkClicks: input.linkClicks,
    shopClicks: input.shopClicks,
    cpcLinkUsd: decimalOrNull(input.cpcLinkUsd),
    ctrLinkPct: decimalOrNull(input.ctrLinkPct),
    clicksAll: input.clicksAll,
    ctrAllPct: decimalOrNull(input.ctrAllPct),
    cpcAllUsd: decimalOrNull(input.cpcAllUsd),
    landingPageViews: input.landingPageViews,
    costPerLandingPageViewUsd: decimalOrNull(input.costPerLandingPageViewUsd),
    productId: input.productId,
    stage: input.stage,
    productMatchSource: input.productMatchSource,
    stageMatchSource: input.stageMatchSource,
    productMatchRuleId: input.productMatchRuleId,
    importVersion,
    isCurrent: true,
    supersededByMetricId: null,
    rawRow: input.rawRow as Prisma.InputJsonObject
  };
}
